# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `mdb.term_to_html' in source file `term_to_html.m'.
# Generated by Mercury compiler version rotd-2019-03-28
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# source group names:
#   (unnamed)
#   parent deps
#   long deps
#   short deps
mdb.term_to_html.optdate mdb.term_to_html.trans_opt_date term_to_html.err mdb.term_to_html.c_date mdb.term_to_html.java_date : \
		term_to_html.m \
	\
		mdb.int0 \
	\
		bool.int \
		builtin.int \
		char.int \
		construct.int \
		deconstruct.int \
		dir.int \
		exception.int \
		int.int \
		io.int \
		list.int \
		maybe.int \
		private_builtin.int \
		string.int \
		type_desc.int \
		univ.int \
		mdb.browse.int \
		mdb.browser_term.int \
		mdb.percent_encoding.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		enum.int2 \
		getopt.int2 \
		integer.int2 \
		map.int2 \
		mdbcomp.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		random.int2 \
		rtti_implementation.int2 \
		set.int2 \
		set_ordlist.int2 \
		stm_builtin.int2 \
		store.int2 \
		stream.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		unit.int2 \
		mdb.browser_info.int2 \
		mdb.parse.int2 \
		mdb.term_rep.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.rtti_access.int2 \
		mdbcomp.sym_name.int2 \
		mdbcomp.trace_counts.int2

# RULE objs_on_mihs
mdb.term_to_html.pic_o mdb.term_to_html.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		dir.mih \
		enum.mih \
		exception.mih \
		getopt.mih \
		int.mih \
		integer.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdb.mih \
		mdbcomp.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		random.mih \
		rtti_implementation.mih \
		set.mih \
		set_ordlist.mih \
		stm_builtin.mih \
		store.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		mdb.browse.mih \
		mdb.browser_info.mih \
		mdb.browser_term.mih \
		mdb.parse.mih \
		mdb.percent_encoding.mih \
		mdb.term_rep.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.rtti_access.mih \
		mdbcomp.sym_name.mih \
		mdbcomp.trace_counts.mih

# RULE mh_and_mih_on_c
mdb.term_to_html.mh mdb.term_to_html.mih : mdb.term_to_html.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
mdb.term_to_html.module_dep : jmercury/mdb__term_to_html.java

else

# RULE module_dep_on_c
mdb.term_to_html.module_dep : mdb.term_to_html.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   parent dep int0
#   long dep int3s
#   short dep int3s
mdb.term_to_html.date mdb.term_to_html.date0 mdb.date : \
		term_to_html.m \
	\
		mdb.int0 \
	\
		bool.int3 \
		builtin.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		dir.int3 \
		exception.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		string.int3 \
		type_desc.int3 \
		univ.int3 \
		mdb.browse.int3 \
		mdb.browser_term.int3 \
		mdb.percent_encoding.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		map.int3 \
		mdbcomp.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		random.int3 \
		rtti_implementation.int3 \
		set.int3 \
		set_ordlist.int3 \
		stm_builtin.int3 \
		store.int3 \
		stream.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		unit.int3 \
		mdb.browser_info.int3 \
		mdb.parse.int3 \
		mdb.term_rep.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.rtti_access.int3 \
		mdbcomp.sym_name.int3 \
		mdbcomp.trace_counts.int3

# RULE self_and_parent_date0_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mdb.term_to_html.date0 mdb.date0 : \
		term_to_html.m \
	\
		bool.int3 \
		builtin.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		dir.int3 \
		exception.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		string.int3 \
		type_desc.int3 \
		univ.int3 \
		mdb.browse.int3 \
		mdb.browser_term.int3 \
		mdb.percent_encoding.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		map.int3 \
		mdbcomp.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		random.int3 \
		rtti_implementation.int3 \
		set.int3 \
		set_ordlist.int3 \
		stm_builtin.int3 \
		store.int3 \
		stream.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		unit.int3 \
		mdb.browser_info.int3 \
		mdb.parse.int3 \
		mdb.term_rep.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.rtti_access.int3 \
		mdbcomp.sym_name.int3 \
		mdbcomp.trace_counts.int3

# RULE foreign_deps_for_.mh
mdb.term_to_html.$O : \
		dir.mh \
		io.mh \
		mdb.mh \
		string.mh \
		time.mh \
		mdbcomp.rtti_access.mh

# RULE foreign_deps_for_.mh
mdb.term_to_html.pic_o : \
		dir.mh \
		io.mh \
		mdb.mh \
		string.mh \
		time.mh \
		mdbcomp.rtti_access.mh

mdb.term_to_html.int0 : mdb.term_to_html.date0
	@:

mdb.term_to_html.int : mdb.term_to_html.date
	@:

mdb.term_to_html.int2 : mdb.term_to_html.date
	@:

mdb.term_to_html.int3 : mdb.term_to_html.date3
	@:

mdb.term_to_html.opt : mdb.term_to_html.optdate
	@:

mdb.term_to_html.trans_opt : mdb.term_to_html.trans_opt_date
	@:

mdb.term_to_html.date0 : term_to_html.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) mdb.term_to_html

mdb.term_to_html.date : term_to_html.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) mdb.term_to_html

mdb.term_to_html.date3 : term_to_html.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) mdb.term_to_html

mdb.term_to_html.optdate : term_to_html.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) mdb.term_to_html

mdb.term_to_html.trans_opt_date : term_to_html.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) mdb.term_to_html

mdb.term_to_html.c_date : term_to_html.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) mdb.term_to_html $(ERR_REDIRECT)

mdb.term_to_html.java_date : term_to_html.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only mdb.term_to_html $(ERR_REDIRECT)

