# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `options' in source file `options.m'.
# Generated by Mercury compiler version rotd-2024-12-21
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   direct deps
#   indirect deps
#   type_repn self dep
options.optdate options.trans_opt_date options.err options.c_date options.java_date : \
		options.m \
	\
		bool.int \
		builtin.int \
		getopt.int \
		io.int \
		list.int \
		map.int \
		private_builtin.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		maybe.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		options.int

# RULE objs_on_mihs
options.pic_o options.$O : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		getopt.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih

# RULE mh_and_mih_on_c
options.mh options.mih : options.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
options.module_dep : jmercury/options.java

else

# RULE module_dep_on_c
options.module_dep : options.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
options.date options.date0 : \
		options.m \
	\
		bool.int3 \
		builtin.int3 \
		getopt.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		private_builtin.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
options.date0 : \
		options.m \
	\
		bool.int3 \
		builtin.int3 \
		getopt.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		private_builtin.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
options.$O options.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
options.int0 : options.date0
	@:

# RULE int_on_date
options.int : options.date
	@:

# RULE int2_on_date
options.int2 : options.date
	@:

# RULE int3_on_date3
options.int3 : options.date3
	@:

# RULE opt_on_opt_date
options.opt : options.optdate
	@:

# RULE trans_opt_on_trans_opt_date
options.trans_opt : options.trans_opt_date
	@:

