# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `snapshots' in source file `snapshots.m'.
# Generated by Mercury compiler version rotd-2022-06-28
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
snapshots.optdate snapshots.trans_opt_date snapshots.err snapshots.c_date snapshots.java_date : \
		snapshots.m \
	\
		bool.int \
		builtin.int \
		demangle.int \
		float.int \
		globals.int \
		int.int \
		io.int \
		list.int \
		map.int \
		options.int \
		private_builtin.int \
		require.int \
		string.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		getopt.int2 \
		maybe.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		snapshots.int

# RULE objs_on_mihs
snapshots.pic_o snapshots.$O : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		demangle.mih \
		enum.mih \
		float.mih \
		getopt.mih \
		globals.mih \
		int.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		ops.mih \
		options.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
snapshots.mh snapshots.mih : snapshots.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
snapshots.module_dep : jmercury/snapshots.java

else

# RULE module_dep_on_c
snapshots.module_dep : snapshots.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
snapshots.date snapshots.date0 : \
		snapshots.m \
	\
		bool.int3 \
		builtin.int3 \
		demangle.int3 \
		float.int3 \
		globals.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		options.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
snapshots.date0 : \
		snapshots.m \
	\
		bool.int3 \
		builtin.int3 \
		demangle.int3 \
		float.int3 \
		globals.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		options.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
snapshots.$O snapshots.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
snapshots.int0 : snapshots.date0
	@:

# RULE int_on_date
snapshots.int : snapshots.date
	@:

# RULE int2_on_date
snapshots.int2 : snapshots.date
	@:

# RULE int3_on_date3
snapshots.int3 : snapshots.date3
	@:

# RULE opt_on_opt_date
snapshots.opt : snapshots.optdate
	@:

# RULE trans_opt_on_trans_opt_date
snapshots.trans_opt : snapshots.trans_opt_date
	@:

