# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `apply_exclusion' in source file `apply_exclusion.m'.
# Generated by Mercury compiler version rotd-2018-01-09
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# source group names:
#   (unnamed)
#   long deps
#   short deps
apply_exclusion.optdate apply_exclusion.trans_opt_date apply_exclusion.err apply_exclusion.c_date apply_exclusion.java_date : \
		apply_exclusion.m \
	\
		assoc_list.int \
		builtin.int \
		exclude.int \
		list.int \
		map.int \
		measurements.int \
		pair.int \
		private_builtin.int \
		profile.int \
	\
		array.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		integer.int2 \
		io.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		measurement_units.int2 \
		ops.int2 \
		pretty_printer.int2 \
		random.int2 \
		rtti_implementation.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.rtti_access.int2 \
		mdbcomp.sym_name.int2 \
		mdbcomp.trace_counts.int2 \
		mdbcomp.feedback.automatic_parallelism.int2

# RULE objs_on_mihs
apply_exclusion.pic_o apply_exclusion.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		exclude.mih \
		integer.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		measurement_units.mih \
		measurements.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		profile.mih \
		random.mih \
		rtti_implementation.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		mdbcomp.feedback.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.rtti_access.mih \
		mdbcomp.sym_name.mih \
		mdbcomp.trace_counts.mih \
		mdbcomp.feedback.automatic_parallelism.mih

# RULE mh_and_mih_on_c
apply_exclusion.mh apply_exclusion.mih : apply_exclusion.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
apply_exclusion.module_dep : jmercury/apply_exclusion.java

else

# RULE module_dep_on_c
apply_exclusion.module_dep : apply_exclusion.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
apply_exclusion.date apply_exclusion.date0 : \
		apply_exclusion.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		exclude.int3 \
		list.int3 \
		map.int3 \
		measurements.int3 \
		pair.int3 \
		private_builtin.int3 \
		profile.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		io.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		measurement_units.int3 \
		ops.int3 \
		pretty_printer.int3 \
		random.int3 \
		rtti_implementation.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.rtti_access.int3 \
		mdbcomp.sym_name.int3 \
		mdbcomp.trace_counts.int3 \
		mdbcomp.feedback.automatic_parallelism.int3

# RULE self_and_parent_date0_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
apply_exclusion.date0 : \
		apply_exclusion.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		exclude.int3 \
		list.int3 \
		map.int3 \
		measurements.int3 \
		pair.int3 \
		private_builtin.int3 \
		profile.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		io.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		measurement_units.int3 \
		ops.int3 \
		pretty_printer.int3 \
		random.int3 \
		rtti_implementation.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.rtti_access.int3 \
		mdbcomp.sym_name.int3 \
		mdbcomp.trace_counts.int3 \
		mdbcomp.feedback.automatic_parallelism.int3

# RULE foreign_deps_for_.mh
apply_exclusion.$O : \
		io.mh \
		profile.mh \
		string.mh \
		time.mh \
		mdbcomp.rtti_access.mh

# RULE foreign_deps_for_.mh
apply_exclusion.pic_o : \
		io.mh \
		profile.mh \
		string.mh \
		time.mh \
		mdbcomp.rtti_access.mh

apply_exclusion.int0 : apply_exclusion.date0
	@:

apply_exclusion.int : apply_exclusion.date
	@:

apply_exclusion.int2 : apply_exclusion.date
	@:

apply_exclusion.int3 : apply_exclusion.date3
	@:

apply_exclusion.opt : apply_exclusion.optdate
	@:

apply_exclusion.trans_opt : apply_exclusion.trans_opt_date
	@:

