# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `array_util' in source file `array_util.m'.
# Generated by Mercury compiler version rotd-2022-12-09
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
array_util.optdate array_util.trans_opt_date array_util.err array_util.c_date array_util.java_date : \
		array_util.m \
	\
		array.int \
		builtin.int \
		int.int \
		list.int \
		private_builtin.int \
	\
		assoc_list.int2 \
		enum.int2 \
		map.int2 \
		maybe.int2 \
		pair.int2 \
		pretty_printer.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		array_util.int

# RULE objs_on_mihs
array_util.pic_o array_util.$O : \
		array.mih \
		assoc_list.mih \
		builtin.mih \
		enum.mih \
		int.mih \
		list.mih \
		map.mih \
		maybe.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih

# RULE mh_and_mih_on_c
array_util.mh array_util.mih : array_util.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
array_util.module_dep : jmercury/array_util.java

else

# RULE module_dep_on_c
array_util.module_dep : array_util.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
array_util.date array_util.date0 : \
		array_util.m \
	\
		array.int3 \
		builtin.int3 \
		int.int3 \
		list.int3 \
		private_builtin.int3 \
	\
		assoc_list.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
array_util.date0 : \
		array_util.m \
	\
		array.int3 \
		builtin.int3 \
		int.int3 \
		list.int3 \
		private_builtin.int3 \
	\
		assoc_list.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
array_util.$O array_util.pic_o : \
		array.mh \
		array_util.mh

# RULE int0_on_date0
array_util.int0 : array_util.date0
	@:

# RULE int_on_date
array_util.int : array_util.date
	@:

# RULE int2_on_date
array_util.int2 : array_util.date
	@:

# RULE int3_on_date3
array_util.int3 : array_util.date3
	@:

# RULE opt_on_opt_date
array_util.opt : array_util.optdate
	@:

# RULE trans_opt_on_trans_opt_date
array_util.trans_opt : array_util.trans_opt_date
	@:

