# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `conf' in source file `conf.m'.
# Generated by Mercury compiler version rotd-2022-12-03
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
conf.optdate conf.trans_opt_date conf.err conf.c_date conf.java_date : \
		conf.m \
	\
		builtin.int \
		io.int \
		list.int \
		maybe.int \
		private_builtin.int \
		require.int \
		stream.int \
		string.int \
		io.call_system.int \
		io.environment.int \
		io.file.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		conf.int

# RULE objs_on_mihs
conf.pic_o conf.$O : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		io.call_system.mih \
		io.environment.mih \
		io.file.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
conf.mh conf.mih : conf.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
conf.module_dep : jmercury/conf.java

else

# RULE module_dep_on_c
conf.module_dep : conf.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
conf.date conf.date0 : \
		conf.m \
	\
		builtin.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		require.int3 \
		stream.int3 \
		string.int3 \
		io.call_system.int3 \
		io.environment.int3 \
		io.file.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
conf.date0 : \
		conf.m \
	\
		builtin.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		require.int3 \
		stream.int3 \
		string.int3 \
		io.call_system.int3 \
		io.environment.int3 \
		io.file.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
conf.$O conf.pic_o : \
		array.mh \
		bitmap.mh \
		conf.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
conf.int0 : conf.date0
	@:

# RULE int_on_date
conf.int : conf.date
	@:

# RULE int2_on_date
conf.int2 : conf.date
	@:

# RULE int3_on_date3
conf.int3 : conf.date3
	@:

# RULE opt_on_opt_date
conf.opt : conf.optdate
	@:

# RULE trans_opt_on_trans_opt_date
conf.trans_opt : conf.trans_opt_date
	@:

