# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `exclude' in source file `exclude.m'.
# Generated by Mercury compiler version rotd-2024-02-22
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   long deps
#   short deps
#   type_repn self dep
exclude.optdate exclude.trans_opt_date exclude.err exclude.c_date exclude.java_date : \
		exclude.m \
	\
		bool.int \
		builtin.int \
		char.int \
		io.int \
		list.int \
		map.int \
		maybe.int \
		private_builtin.int \
		profile.int \
		set.int \
		stream.int \
		string.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		mdbcomp.int2 \
		measurements.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set_ordlist.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
	\
		exclude.int

# RULE objs_on_mihs
exclude.pic_o exclude.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		exclude.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		measurements.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		profile.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.program_representation.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
exclude.mh exclude.mih : exclude.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
exclude.module_dep : jmercury/exclude.java

else

# RULE module_dep_on_c
exclude.module_dep : exclude.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   long dep int3s
#   short dep int3s
exclude.date exclude.date0 : \
		exclude.m \
	\
		bool.int3 \
		builtin.int3 \
		char.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		private_builtin.int3 \
		profile.int3 \
		set.int3 \
		stream.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		mdbcomp.int3 \
		measurements.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   long dep int3s
#   short dep int3s
exclude.date0 : \
		exclude.m \
	\
		bool.int3 \
		builtin.int3 \
		char.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		private_builtin.int3 \
		profile.int3 \
		set.int3 \
		stream.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		mdbcomp.int3 \
		measurements.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3

# RULE foreign_deps_for_mh
exclude.$O exclude.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		profile.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
exclude.int0 : exclude.date0
	@:

# RULE int_on_date
exclude.int : exclude.date
	@:

# RULE int2_on_date
exclude.int2 : exclude.date
	@:

# RULE int3_on_date3
exclude.int3 : exclude.date3
	@:

# RULE opt_on_opt_date
exclude.opt : exclude.optdate
	@:

# RULE trans_opt_on_trans_opt_date
exclude.trans_opt : exclude.trans_opt_date
	@:

