/*
** Automatically generated from `autopar_annotate.m'
** by the Mercury compiler,
** version rotd-2017-08-02
** configured for x86_64-apple-darwin13.4.0.
** Do not edit.
**
** The autoconfigured grade settings governing
** the generation of this C file were
**
** TAG_BITS=2
** UNBOXED_FLOAT=no
** PREGENERATED_DIST=yes
** HIGHLEVEL_CODE=yes
**
** END_OF_C_GRADE_INFO
*/


/* :- module mdprof_fb.automatic_parallelism.autopar_annotate. */
/* :- implementation. */

/*
INIT mercury__mdprof_fb__automatic_parallelism__autopar_annotate__init
ENDINIT
*/

#include "mdprof_fb.automatic_parallelism.autopar_annotate.mih"


#include "analysis_utils.mih"
#include "coverage.mih"
#include "exclude.mih"
#include "mdbcomp.mih"
#include "mdprof_fb.mih"
#include "measurement_units.mih"
#include "measurements.mih"
#include "profile.mih"
#include "program_representation_utils.mih"
#include "query.mih"
#include "report.mih"
#include "var_use_analysis.mih"
#include "mdbcomp.feedback.mih"
#include "mdbcomp.goal_path.mih"
#include "mdbcomp.prim_data.mih"
#include "mdbcomp.program_representation.mih"
#include "mdbcomp.rtti_access.mih"
#include "mdbcomp.sym_name.mih"
#include "mdbcomp.trace_counts.mih"
#include "mdprof_fb.automatic_parallelism.mih"
#include "array.mih"
#include "assoc_list.mih"
#include "bimap.mih"
#include "bitmap.mih"
#include "bool.mih"
#include "builtin.mih"
#include "char.mih"
#include "construct.mih"
#include "cord.mih"
#include "deconstruct.mih"
#include "digraph.mih"
#include "enum.mih"
#include "integer.mih"
#include "io.mih"
#include "lazy.mih"
#include "list.mih"
#include "map.mih"
#include "maybe.mih"
#include "ops.mih"
#include "pair.mih"
#include "pretty_printer.mih"
#include "private_builtin.mih"
#include "random.mih"
#include "rtti_implementation.mih"
#include "set.mih"
#include "set_ordlist.mih"
#include "sparse_bitset.mih"
#include "stream.mih"
#include "string.mih"
#include "term.mih"
#include "time.mih"
#include "tree234.mih"
#include "type_desc.mih"
#include "unit.mih"
#include "univ.mih"
#include "mdbcomp.feedback.automatic_parallelism.mih"
#include "mdprof_fb.automatic_parallelism.autopar_types.mih"




static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__ite_annotate_with_instmap_10_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Cond_11,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Then_12,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Else_13,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_14,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_15,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_16,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMap0_17,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__InstMap_18,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_35,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_36);

static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__switch_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8);

static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__disj_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8);

static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__conj_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_5,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_6,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8);







#include "io.mh"
#include "string.mh"
#include "time.mh"
#include "mdbcomp.program_representation.mh"
#include "mdbcomp.rtti_access.mh"



static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__ite_annotate_with_instmap_10_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Cond_11,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Then_12,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Else_13,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_14,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_15,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_16,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMap0_17,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__InstMap_18,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_35,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_36)
{
  {
    MR_bool mdprof_fb__automatic_parallelism__autopar_annotate__succeeded;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationCond_20;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsCond_21;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterCond_23;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationThen_24;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsThen_25;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsThen_26;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterThen_27;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationElse_28;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsElse_29;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsElse_30;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterElse_31;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsCondThen_32;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ThenDetism_33;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ElseDetism_34;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_37_37;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_38_38;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate___BoundVarsCond_22;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_40;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_41;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_42;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_43;

    mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Cond_11, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationCond_20, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsCond_21, &mdprof_fb__automatic_parallelism__autopar_annotate___BoundVarsCond_22, mdprof_fb__automatic_parallelism__autopar_annotate__InstMap0_17, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterCond_23, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_35, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_37_37);
    mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Then_12, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationThen_24, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsThen_25, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsThen_26, mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterCond_23, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterThen_27, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_37_37, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_38_38);
    mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Else_13, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationElse_28, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsElse_29, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsElse_30, mdprof_fb__automatic_parallelism__autopar_annotate__InstMap0_17, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterElse_31, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_38_38, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_36);
    mdprof_fb__automatic_parallelism__autopar_annotate__succeeded = (mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationCond_20 == (MR_Integer) 1);
    if (mdprof_fb__automatic_parallelism__autopar_annotate__succeeded)
    {
      mdprof_fb__automatic_parallelism__autopar_annotate__succeeded = (mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationThen_24 == (MR_Integer) 1);
      if (mdprof_fb__automatic_parallelism__autopar_annotate__succeeded)
        mdprof_fb__automatic_parallelism__autopar_annotate__succeeded = (mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationElse_28 == (MR_Integer) 1);
    }
    if (mdprof_fb__automatic_parallelism__autopar_annotate__succeeded)
      *mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_14 = (MR_Integer) 1;
    else
      *mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_14 = (MR_Integer) 0;
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    mercury__set__union_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsCond_21, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsThen_25, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsCondThen_32);
    mercury__set__union_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsCondThen_32, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsElse_29, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_15);
    mercury__set__intersect_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsThen_26, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsElse_30, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_16);
    mdprof_fb__automatic_parallelism__autopar_annotate__Var_40 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Then_12, (MR_Integer) 0)));
    mdprof_fb__automatic_parallelism__autopar_annotate__ThenDetism_33 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Then_12, (MR_Integer) 1)));
    mdprof_fb__automatic_parallelism__autopar_annotate__Var_41 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Then_12, (MR_Integer) 2)));
    mdprof_fb__automatic_parallelism__autopar_annotate__Var_42 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Else_13, (MR_Integer) 0)));
    mdprof_fb__automatic_parallelism__autopar_annotate__ElseDetism_34 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Else_13, (MR_Integer) 1)));
    mdprof_fb__automatic_parallelism__autopar_annotate__Var_43 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Else_13, (MR_Integer) 2)));
    *mdprof_fb__automatic_parallelism__autopar_annotate__InstMap_18 = program_representation_utils__merge_inst_map_4_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterThen_27, mdprof_fb__automatic_parallelism__autopar_annotate__ThenDetism_33, mdprof_fb__automatic_parallelism__autopar_annotate__InstMapAfterElse_31, mdprof_fb__automatic_parallelism__autopar_annotate__ElseDetism_34);
  }
}

static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__switch_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8)
{
  if ((mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1 == ((MR_Word) MR_mkword(MR_mktag(0), MR_mkbody((MR_Integer) 0)))))
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44;

    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2 = (MR_Integer) 1;
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3 = mercury__set__init_0_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44);
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4 = mercury__set__init_0_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_44_44);
    *mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8 = mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7;
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6 = mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5;
  }
  else
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_45_45;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Case_15 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Cases_16 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1, (MR_Integer) 1)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Goal_25 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Case_15, (MR_Integer) 2)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadDetism_26 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Goal_25, (MR_Integer) 1)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_27;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_28;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_29;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapHead_30;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_31;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_32;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_33;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapTail_34;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_35;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_40_40;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_23 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Case_15, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_24 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Case_15, (MR_Integer) 1)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_42 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Goal_25, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_43 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Goal_25, (MR_Integer) 2)));

    mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Goal_25, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_27, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_28, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_29, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapHead_30, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_40_40);
    mdprof_fb__automatic_parallelism__autopar_annotate__switch_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Cases_16, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_31, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_32, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_33, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapTail_34, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_40_40, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8);
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_45_45 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    mercury__set__union_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_45_45, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_32, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_28, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3);
    if ((mdprof_fb__automatic_parallelism__autopar_annotate__Cases_16 == ((MR_Word) MR_mkword(MR_mktag(0), MR_mkbody((MR_Integer) 0)))))
    {
      mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_35 = (MR_Integer) 7;
      *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4 = mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_29;
    }
    else
    {
      mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_35 = (MR_Integer) 0;
      mercury__set__intersect_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_45_45, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_33, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_29, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4);
    }
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6 = program_representation_utils__merge_inst_map_4_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__InstMapHead_30, mdprof_fb__automatic_parallelism__autopar_annotate__HeadDetism_26, mdprof_fb__automatic_parallelism__autopar_annotate__InstMapTail_34, mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_35);
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2 = program_representation_utils__merge_seen_duplicate_instantiation_2_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_27, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_31);
  }
}

static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__disj_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8)
{
  if ((mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1 == ((MR_Word) MR_mkword(MR_mktag(0), MR_mkbody((MR_Integer) 0)))))
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_41_41;

    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2 = (MR_Integer) 1;
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_41_41 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3 = mercury__set__init_0_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_41_41);
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4 = mercury__set__init_0_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_41_41);
    *mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8 = mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7;
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6 = mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5;
  }
  else
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_42_42;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Disj_15 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Disjs_16 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1, (MR_Integer) 1)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadDetism_23 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Disj_15, (MR_Integer) 1)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_24;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_25;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_26;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapHead_27;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_28;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_29;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_30;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapTail_31;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_32;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_37_37;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_39 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Disj_15, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_40 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Disj_15, (MR_Integer) 2)));

    mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Disj_15, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_24, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_25, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_26, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapHead_27, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_37_37);
    mdprof_fb__automatic_parallelism__autopar_annotate__disj_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Disjs_16, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_28, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_29, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_30, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__5_5, &mdprof_fb__automatic_parallelism__autopar_annotate__InstMapTail_31, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_37_37, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8);
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_42_42 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    mercury__set__union_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_42_42, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_29, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_25, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3);
    if ((mdprof_fb__automatic_parallelism__autopar_annotate__Disjs_16 == ((MR_Word) MR_mkword(MR_mktag(0), MR_mkbody((MR_Integer) 0)))))
    {
      mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_32 = (MR_Integer) 7;
      *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4 = mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_26;
    }
    else
    {
      mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_32 = (MR_Integer) 0;
      mercury__set__intersect_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_42_42, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_30, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_26, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4);
    }
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__6_6 = program_representation_utils__merge_inst_map_4_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__InstMapHead_27, mdprof_fb__automatic_parallelism__autopar_annotate__HeadDetism_23, mdprof_fb__automatic_parallelism__autopar_annotate__InstMapTail_31, mdprof_fb__automatic_parallelism__autopar_annotate__TailDetism_32);
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2 = program_representation_utils__merge_seen_duplicate_instantiation_2_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_24, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_28);
  }
}

static void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__conj_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_5,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_6,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8)
{
  if ((mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1 == ((MR_Word) MR_mkword(MR_mktag(0), MR_mkbody((MR_Integer) 0)))))
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_36_36;

    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2 = (MR_Integer) 1;
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_36_36 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3 = mercury__set__init_0_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_36_36);
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4 = mercury__set__init_0_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_36_36);
    *mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8 = mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7;
    *mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_6 = mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_5;
  }
  else
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_37_37;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Conj_15 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Conjs_16 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__1_1, (MR_Integer) 1)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_22;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_23;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_24;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_25;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_26;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_27;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_32_32;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_33_33;

    mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Conj_15, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_22, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_23, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_24, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_5, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_32_32, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_7, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_33_33);
    mdprof_fb__automatic_parallelism__autopar_annotate__conj_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Conjs_16, &mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_25, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_26, &mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_27, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_32_32, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_6, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_33_33, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_8);
    mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_37_37 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
    mercury__set__union_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_37_37, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsTail_26, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVarsHead_23, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__3_3);
    mercury__set__union_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_37_37, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsTail_27, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsHead_24, mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__4_4);
    *mdprof_fb__automatic_parallelism__autopar_annotate__HeadVar__2_2 = program_representation_utils__merge_seen_duplicate_instantiation_2_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationHead_22, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiationTail_25);
  }
}

void MR_CALL 
mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Goal_9,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40,
  MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41,
  MR_Word * mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_42)
{
  {
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Goal_9, (MR_Integer) 0)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__GoalId_17 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Goal_9, (MR_Integer) 2)));
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54;
    MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_16 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__Goal_9, (MR_Integer) 1)));

    switch (MR_tag((MR_Word) mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15)) {
      default: /*NOTREACHED*/ MR_assert(0);
      case (MR_Integer) 0:
        {
          MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Conjs_19 = ((MR_Word) (MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 0)));

          mdprof_fb__automatic_parallelism__autopar_annotate__conj_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Conjs_19, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54);
        }
        break;
      case (MR_Integer) 1:
        {
          MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Disjs_20 = ((MR_Word) (MR_hl_field(MR_mktag(1), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 0)));

          mdprof_fb__automatic_parallelism__autopar_annotate__disj_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Disjs_20, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54);
        }
        break;
      case (MR_Integer) 2:
        {
          MR_Integer mdprof_fb__automatic_parallelism__autopar_annotate__Var_21 = ((MR_Integer) (MR_hl_field(MR_mktag(2), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 0)));
          MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Cases_23 = ((MR_Word) (MR_hl_field(MR_mktag(2), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 2)));
          MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars0_24;
          MR_Word mdprof_fb__automatic_parallelism__autopar_annotate___CanFail_22 = ((MR_Word) (MR_hl_field(MR_mktag(2), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 1)));

          mdprof_fb__automatic_parallelism__autopar_annotate__switch_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Cases_23, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10, &mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars0_24, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54);
          mercury__set__insert_3_p_0((MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0, ((MR_Box) (mdprof_fb__automatic_parallelism__autopar_annotate__Var_21)), mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars0_24, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11);
        }
        break;
      case (MR_Integer) 3:
        switch (((MR_Integer) (MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 0)))) {
          default: /*NOTREACHED*/ MR_assert(0);
          case (MR_Integer) 0:
            {
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Cond_25 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 1)));
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Then_26 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 2)));
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Else_27 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 3)));

              mdprof_fb__automatic_parallelism__autopar_annotate__ite_annotate_with_instmap_10_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Cond_25, mdprof_fb__automatic_parallelism__autopar_annotate__Then_26, mdprof_fb__automatic_parallelism__autopar_annotate__Else_27, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54);
            }
            break;
          case (MR_Integer) 1:
            {
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Subgoal_56 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 1)));
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Var_30;
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate___InstMap_31;

              mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Subgoal_56, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11, &mdprof_fb__automatic_parallelism__autopar_annotate__Var_30, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, &mdprof_fb__automatic_parallelism__autopar_annotate___InstMap_31, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54);
              *mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12 = mercury__set__init_0_f_0((MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0);
              *mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40 = mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39;
            }
            break;
          case (MR_Integer) 2:
            {
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Subgoal_28 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 1)));
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate___MaybeCut_29 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 2)));

              mdprof_fb__automatic_parallelism__autopar_annotate__goal_annotate_with_instmap_8_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__Subgoal_28, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41, &mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54);
            }
            break;
          case (MR_Integer) 3:
            {
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_59_59;
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsList_34 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 3)));
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__AtomicGoal_35 = ((MR_Word) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 4)));
              MR_Word mdprof_fb__automatic_parallelism__autopar_annotate__Vars_36;
              MR_String mdprof_fb__automatic_parallelism__autopar_annotate___File_32 = ((MR_String) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 1)));
              MR_Integer mdprof_fb__automatic_parallelism__autopar_annotate___Line_33 = ((MR_Integer) (MR_hl_field(MR_mktag(3), mdprof_fb__automatic_parallelism__autopar_annotate__GoalExpr_15, (MR_Integer) 2)));

              program_representation_utils__atomic_goal_get_vars_2_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__AtomicGoal_35, &mdprof_fb__automatic_parallelism__autopar_annotate__Vars_36);
              mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_59_59 = (MR_Word) &mercury__builtin__builtin__type_ctor_info_int_0;
              *mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12 = mercury__set__from_list_1_f_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_59_59, mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsList_34);
              mercury__set__difference_3_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__TypeCtorInfo_59_59, mdprof_fb__automatic_parallelism__autopar_annotate__Vars_36, *mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12, mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11);
              program_representation_utils__inst_map_ground_vars_5_p_0(mdprof_fb__automatic_parallelism__autopar_annotate__BoundVarsList_34, *mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40, mdprof_fb__automatic_parallelism__autopar_annotate__SeenDuplicateInstantiation_10);
              mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54 = mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_0_41;
            }
            break;
        }
        break;
    }
    {
      mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38 = (MR_Word) MR_new_object(MR_Word, ((MR_Integer) 4 * sizeof(MR_Word)), NULL, NULL);
      MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38, 0) = ((MR_Box) (mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_0_39));
      MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38, 1) = ((MR_Box) (*mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMap_40));
      MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38, 2) = ((MR_Box) (*mdprof_fb__automatic_parallelism__autopar_annotate__ConsumedVars_11));
      MR_hl_field(MR_mktag(0), mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38, 3) = ((MR_Box) (*mdprof_fb__automatic_parallelism__autopar_annotate__BoundVars_12));
    }
    mdbcomp__goal_path__update_goal_attribute_4_p_0((MR_Word) &mdprof_fb__automatic_parallelism__autopar_types__mdprof_fb__automatic_parallelism__autopar_types__type_ctor_info_inst_map_info_0, mdprof_fb__automatic_parallelism__autopar_annotate__GoalId_17, ((MR_Box) (mdprof_fb__automatic_parallelism__autopar_annotate__InstMapInfo_38)), mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_54_54, mdprof_fb__automatic_parallelism__autopar_annotate__STATE_VARIABLE_InstMapArray_42);
  }
}

void mercury__mdprof_fb__automatic_parallelism__autopar_annotate__init(void)
{
}

void mercury__mdprof_fb__automatic_parallelism__autopar_annotate__init_type_tables(void)
{
}

void mercury__mdprof_fb__automatic_parallelism__autopar_annotate__init_debugger(void)
{
	MR_fatal_error("debugger initialization in MLDS grade");
}

// Ensure everything is compiled with the same grade.
const char *mercury__mdprof_fb__automatic_parallelism__autopar_annotate__grade_check(void)
{
    return &MR_GRADE_VAR;
}

/* :- end_module mdprof_fb.automatic_parallelism.autopar_annotate. */
