# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `mdprof_dump' in source file `mdprof_dump.m'.
# Generated by Mercury compiler version 22.01.6-beta-2023-02-04
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
mdprof_dump.optdate mdprof_dump.trans_opt_date mdprof_dump.err mdprof_dump.c_date mdprof_dump.java_date : \
		mdprof_dump.m \
	\
		bool.int \
		builtin.int \
		char.int \
		dump.int \
		getopt.int \
		io.int \
		list.int \
		maybe.int \
		private_builtin.int \
		read_profile.int \
		string.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		map.int2 \
		measurements.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		profile.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		mdprof_dump.int

# RULE objs_on_mihs
mdprof_dump.pic_o mdprof_dump.$O : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		dump.mih \
		enum.mih \
		getopt.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		measurements.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		profile.mih \
		read_profile.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
mdprof_dump.mh mdprof_dump.mih : mdprof_dump.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
mdprof_dump.module_dep : jmercury/mdprof_dump.java

else

# RULE module_dep_on_c
mdprof_dump.module_dep : mdprof_dump.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mdprof_dump.date mdprof_dump.date0 : \
		mdprof_dump.m \
	\
		bool.int3 \
		builtin.int3 \
		char.int3 \
		dump.int3 \
		getopt.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		read_profile.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		measurements.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		profile.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mdprof_dump.date0 : \
		mdprof_dump.m \
	\
		bool.int3 \
		builtin.int3 \
		char.int3 \
		dump.int3 \
		getopt.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		read_profile.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		measurements.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		profile.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
mdprof_dump.$O mdprof_dump.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		read_profile.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
mdprof_dump.int0 : mdprof_dump.date0
	@:

# RULE int_on_date
mdprof_dump.int : mdprof_dump.date
	@:

# RULE int2_on_date
mdprof_dump.int2 : mdprof_dump.date
	@:

# RULE int3_on_date3
mdprof_dump.int3 : mdprof_dump.date3
	@:

# RULE opt_on_opt_date
mdprof_dump.opt : mdprof_dump.optdate
	@:

# RULE trans_opt_on_trans_opt_date
mdprof_dump.trans_opt : mdprof_dump.trans_opt_date
	@:

