MR_define_extern_entry(mercury__do_call_closure_compact);
MR_define_extern_entry(mercury__do_call_closure_0);
MR_define_extern_entry(mercury__do_call_closure_1);
MR_define_extern_entry(mercury__do_call_closure_2);
MR_define_extern_entry(mercury__do_call_closure_3);
MR_define_extern_entry(mercury__do_call_closure_4);
MR_define_extern_entry(mercury__do_call_closure_5);
