# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `grade_lib.grade_vars' in source file `grade_vars.m'.
# Generated by Mercury compiler version rotd-2025-08-01
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
grade_lib.grade_vars.optdate grade_lib.grade_vars.trans_opt_date grade_vars.err grade_lib.grade_vars.c_date grade_lib.grade_vars.java_date : \
		grade_vars.m \
	\
		grade_lib.int0 \
	\
		builtin.int \
		map.int \
		private_builtin.int \
		require.int \
		grade_lib.grade_solver.int \
		grade_lib.grade_spec.int \
	\
		assoc_list.int2 \
		enum.int2 \
		list.int2 \
		maybe.int2 \
		one_or_more.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		grade_lib.grade_state.int2 \
	\
		grade_lib.grade_vars.int \
	\
		grade_lib.int

# RULE objs_on_mihs
grade_lib.grade_vars.pic_o grade_lib.grade_vars.$O : \
		assoc_list.mih \
		builtin.mih \
		enum.mih \
		grade_lib.mih \
		list.mih \
		map.mih \
		maybe.mih \
		one_or_more.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		grade_lib.grade_solver.mih \
		grade_lib.grade_spec.mih \
		grade_lib.grade_state.mih

# RULE mh_and_mih_on_c
grade_lib.grade_vars.mh grade_lib.grade_vars.mih : grade_lib.grade_vars.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
grade_lib.grade_vars.module_dep : jmercury/grade_lib__grade_vars.java

else

# RULE module_dep_on_c
grade_lib.grade_vars.module_dep : grade_lib.grade_vars.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
grade_lib.grade_vars.date grade_lib.grade_vars.date0 grade_lib.date : \
		grade_vars.m \
	\
		grade_lib.int0 \
	\
		builtin.int3 \
		map.int3 \
		private_builtin.int3 \
		require.int3 \
		grade_lib.grade_solver.int3 \
		grade_lib.grade_spec.int3 \
	\
		assoc_list.int3 \
		enum.int3 \
		list.int3 \
		maybe.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		grade_lib.grade_state.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
grade_lib.grade_vars.date0 grade_lib.date0 : \
		grade_vars.m \
	\
		builtin.int3 \
		map.int3 \
		private_builtin.int3 \
		require.int3 \
		grade_lib.grade_solver.int3 \
		grade_lib.grade_spec.int3 \
	\
		assoc_list.int3 \
		enum.int3 \
		list.int3 \
		maybe.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		grade_lib.grade_state.int3

# RULE int0_on_date0
grade_lib.grade_vars.int0 : grade_lib.grade_vars.date0
	@:

# RULE int_on_date
grade_lib.grade_vars.int : grade_lib.grade_vars.date
	@:

# RULE int2_on_date
grade_lib.grade_vars.int2 : grade_lib.grade_vars.date
	@:

# RULE int3_on_date3
grade_lib.grade_vars.int3 : grade_lib.grade_vars.date3
	@:

# RULE opt_on_opt_date
grade_lib.grade_vars.opt : grade_lib.grade_vars.optdate
	@:

# RULE trans_opt_on_trans_opt_date
grade_lib.grade_vars.trans_opt : grade_lib.grade_vars.trans_opt_date
	@:

# RULE date0_on_src
grade_lib.grade_vars.date0 : grade_vars.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) grade_lib.grade_vars

# RULE date_on_src
grade_lib.grade_vars.date : grade_vars.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) grade_lib.grade_vars

# RULE date3_on_src
grade_lib.grade_vars.date3 : grade_vars.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) grade_lib.grade_vars

# RULE opt_date_on_src
grade_lib.grade_vars.optdate : grade_vars.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) grade_lib.grade_vars

# RULE trans_opt_date_on_src
grade_lib.grade_vars.trans_opt_date : grade_vars.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) grade_lib.grade_vars

# RULE c_date_on_src
grade_lib.grade_vars.c_date : grade_vars.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) grade_lib.grade_vars $(ERR_REDIRECT)

# RULE java_date_on_src
grade_lib.grade_vars.java_date : grade_vars.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only grade_lib.grade_vars $(ERR_REDIRECT)

