# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `backend_libs' in source file `backend_libs.m'.
# Generated by Mercury compiler version rotd-2026-02-04
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   int0
#   direct deps
#   type_repn self dep
backend_libs.optdate backend_libs.trans_opt_date backend_libs.err backend_libs.c_date backend_libs.java_date : \
		backend_libs.m \
	\
		backend_libs.int0 \
	\
		builtin.int \
		private_builtin.int \
	\
		backend_libs.int

# RULE objs_on_mihs
backend_libs.$O backend_libs.pic_o : \
		builtin.mih \
		private_builtin.mih

# RULE mh_and_mih_on_c
backend_libs.mh backend_libs.mih : backend_libs.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
backend_libs.module_dep : jmercury/backend_libs.java

else

# RULE module_dep_on_c
backend_libs.module_dep : backend_libs.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   direct dep int3s
backend_libs.date backend_libs.date0 : \
		backend_libs.m \
	\
		builtin.int3 \
		private_builtin.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
backend_libs.date0 : \
		backend_libs.m \
	\
		builtin.int3 \
		private_builtin.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
backend_libs.$O backend_libs.pic_o : \
		builtin.mh \
		private_builtin.mh

# RULE int0_on_date0
backend_libs.int0 : backend_libs.date0
	@:

# RULE int_on_date
backend_libs.int : backend_libs.date
	@:

# RULE int2_on_date
backend_libs.int2 : backend_libs.date
	@:

# RULE int3_on_date3
backend_libs.int3 : backend_libs.date3
	@:

# RULE opt_on_opt_date
backend_libs.opt : backend_libs.optdate
	@:

# RULE trans_opt_on_trans_opt_date
backend_libs.trans_opt : backend_libs.trans_opt_date
	@:

