# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `backend_libs.string_switch_util' in source file `string_switch_util.m'.
# Generated by Mercury compiler version rotd-2025-10-10
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
backend_libs.string_switch_util.optdate backend_libs.string_switch_util.trans_opt_date string_switch_util.err backend_libs.string_switch_util.c_date backend_libs.string_switch_util.java_date : \
		string_switch_util.m \
	\
		backend_libs.int0 \
	\
		assoc_list.int \
		builtin.int \
		cord.int \
		hlds.int \
		int.int \
		io.int \
		list.int \
		map.int \
		maybe.int \
		pair.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		string.int \
		backend_libs.builtin_ops.int \
		backend_libs.string_encoding.int \
		hlds.hlds_data.int \
		hlds.hlds_goal.int \
		parse_tree.prog_data.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		libs.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		ops.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_markers.int2 \
		hlds.hlds_pred.int2 \
		hlds.instmap.int2 \
		hlds.status.int2 \
		libs.file_util.int2 \
		libs.globals.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.set_of_var.int2 \
	\
		backend_libs.string_switch_util.int \
	\
		backend_libs.int

# RULE objs_on_mihs
backend_libs.string_switch_util.$O backend_libs.string_switch_util.pic_o : \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		enum.mih \
		hlds.mih \
		int.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		backend_libs.builtin_ops.mih \
		backend_libs.string_encoding.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_markers.mih \
		hlds.hlds_pred.mih \
		hlds.instmap.mih \
		hlds.status.mih \
		libs.file_util.mih \
		libs.globals.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
backend_libs.string_switch_util.mh backend_libs.string_switch_util.mih : backend_libs.string_switch_util.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
backend_libs.string_switch_util.module_dep : jmercury/backend_libs__string_switch_util.java

else

# RULE module_dep_on_c
backend_libs.string_switch_util.module_dep : backend_libs.string_switch_util.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
backend_libs.string_switch_util.date backend_libs.string_switch_util.date0 backend_libs.date : \
		string_switch_util.m \
	\
		backend_libs.int0 \
	\
		assoc_list.int3 \
		builtin.int3 \
		cord.int3 \
		hlds.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.string_encoding.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		parse_tree.prog_data.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		libs.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		hlds.status.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
backend_libs.string_switch_util.date0 backend_libs.date0 : \
		string_switch_util.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		cord.int3 \
		hlds.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.string_encoding.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		parse_tree.prog_data.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		libs.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		hlds.status.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
backend_libs.string_switch_util.$O backend_libs.string_switch_util.pic_o : \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		deconstruct.mh \
		enum.mh \
		hlds.mh \
		int.mh \
		io.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		ops.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		backend_libs.builtin_ops.mh \
		backend_libs.string_encoding.mh \
		hlds.goal_mode.mh \
		hlds.hlds_class.mh \
		hlds.hlds_data.mh \
		hlds.hlds_goal.mh \
		hlds.hlds_llds.mh \
		hlds.hlds_markers.mh \
		hlds.hlds_pred.mh \
		hlds.instmap.mh \
		hlds.status.mh \
		io.stream_ops.mh \
		libs.file_util.mh \
		libs.globals.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_rename.mh \
		parse_tree.set_of_var.mh \
		string.format.mh \
		string.parse_util.mh

# RULE int0_on_date0
backend_libs.string_switch_util.int0 : backend_libs.string_switch_util.date0
	@:

# RULE int_on_date
backend_libs.string_switch_util.int : backend_libs.string_switch_util.date
	@:

# RULE int2_on_date
backend_libs.string_switch_util.int2 : backend_libs.string_switch_util.date
	@:

# RULE int3_on_date3
backend_libs.string_switch_util.int3 : backend_libs.string_switch_util.date3
	@:

# RULE opt_on_opt_date
backend_libs.string_switch_util.opt : backend_libs.string_switch_util.optdate
	@:

# RULE trans_opt_on_trans_opt_date
backend_libs.string_switch_util.trans_opt : backend_libs.string_switch_util.trans_opt_date
	@:

# RULE date0_on_src
backend_libs.string_switch_util.date0 : string_switch_util.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) backend_libs.string_switch_util

# RULE date_on_src
backend_libs.string_switch_util.date : string_switch_util.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) backend_libs.string_switch_util

# RULE date3_on_src
backend_libs.string_switch_util.date3 : string_switch_util.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) backend_libs.string_switch_util

# RULE opt_date_on_src
backend_libs.string_switch_util.optdate : string_switch_util.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) backend_libs.string_switch_util

# RULE trans_opt_date_on_src
backend_libs.string_switch_util.trans_opt_date : string_switch_util.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) backend_libs.string_switch_util

# RULE c_date_on_src
backend_libs.string_switch_util.c_date : string_switch_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) backend_libs.string_switch_util $(ERR_REDIRECT)

# RULE java_date_on_src
backend_libs.string_switch_util.java_date : string_switch_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only backend_libs.string_switch_util $(ERR_REDIRECT)

