# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `check_hlds.delay_info' in source file `delay_info.m'.
# Generated by Mercury compiler version rotd-2026-02-27
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
check_hlds.delay_info.optdate check_hlds.delay_info.trans_opt_date delay_info.err check_hlds.delay_info.c_date check_hlds.delay_info.java_date : \
		delay_info.m \
	\
		check_hlds.int0 \
	\
		builtin.int \
		cord.int \
		hlds.int \
		int.int \
		list.int \
		map.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		set.int \
		stack.int \
		check_hlds.mode_errors.int \
		hlds.hlds_goal.int \
		parse_tree.prog_data.int \
		parse_tree.set_of_var.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bool.int2 \
		char.int2 \
		enum.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		check_hlds.mode_info.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_markers.int2 \
		hlds.hlds_pred.int2 \
		hlds.instmap.int2 \
		hlds.pred_name.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.parse_tree_out_info.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
	\
		check_hlds.delay_info.int \
	\
		check_hlds.int

# RULE objs_on_mihs
check_hlds.delay_info.$O check_hlds.delay_info.pic_o : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		cord.mih \
		enum.mih \
		hlds.mih \
		int.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stack.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.mode_errors.mih \
		check_hlds.mode_info.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_markers.mih \
		hlds.hlds_pred.mih \
		hlds.instmap.mih \
		hlds.pred_name.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.parse_tree_out_info.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih

# RULE mh_and_mih_on_c
check_hlds.delay_info.mh check_hlds.delay_info.mih : check_hlds.delay_info.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
check_hlds.delay_info.module_dep : jmercury/check_hlds__delay_info.java

else

# RULE module_dep_on_c
check_hlds.delay_info.module_dep : check_hlds.delay_info.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
check_hlds.delay_info.date check_hlds.delay_info.date0 check_hlds.date : \
		delay_info.m \
	\
		check_hlds.int0 \
	\
		builtin.int3 \
		cord.int3 \
		hlds.int3 \
		int.int3 \
		list.int3 \
		map.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		stack.int3 \
		check_hlds.mode_errors.int3 \
		hlds.hlds_goal.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		enum.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		check_hlds.mode_info.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
check_hlds.delay_info.date0 check_hlds.date0 : \
		delay_info.m \
	\
		builtin.int3 \
		cord.int3 \
		hlds.int3 \
		int.int3 \
		list.int3 \
		map.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		stack.int3 \
		check_hlds.mode_errors.int3 \
		hlds.hlds_goal.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		enum.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		check_hlds.mode_info.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
check_hlds.delay_info.$O check_hlds.delay_info.pic_o : \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		cord.mh \
		enum.mh \
		hlds.mh \
		int.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		stack.mh \
		term.mh \
		term_context.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		check_hlds.mode_errors.mh \
		check_hlds.mode_info.mh \
		hlds.goal_mode.mh \
		hlds.hlds_class.mh \
		hlds.hlds_data.mh \
		hlds.hlds_goal.mh \
		hlds.hlds_llds.mh \
		hlds.hlds_markers.mh \
		hlds.hlds_pred.mh \
		hlds.instmap.mh \
		hlds.pred_name.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.error_spec.mh \
		parse_tree.parse_tree_out_info.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_rename.mh \
		parse_tree.set_of_var.mh

# RULE int0_on_date0
check_hlds.delay_info.int0 : check_hlds.delay_info.date0
	@:

# RULE int_on_date
check_hlds.delay_info.int : check_hlds.delay_info.date
	@:

# RULE int2_on_date
check_hlds.delay_info.int2 : check_hlds.delay_info.date
	@:

# RULE int3_on_date3
check_hlds.delay_info.int3 : check_hlds.delay_info.date3
	@:

# RULE opt_on_opt_date
check_hlds.delay_info.opt : check_hlds.delay_info.optdate
	@:

# RULE trans_opt_on_trans_opt_date
check_hlds.delay_info.trans_opt : check_hlds.delay_info.trans_opt_date
	@:

# RULE date0_on_src
check_hlds.delay_info.date0 : delay_info.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) check_hlds.delay_info

# RULE date_on_src
check_hlds.delay_info.date : delay_info.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) check_hlds.delay_info

# RULE date3_on_src
check_hlds.delay_info.date3 : delay_info.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) check_hlds.delay_info

# RULE opt_date_on_src
check_hlds.delay_info.optdate : delay_info.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) check_hlds.delay_info

# RULE trans_opt_date_on_src
check_hlds.delay_info.trans_opt_date : delay_info.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) check_hlds.delay_info

# RULE c_date_on_src
check_hlds.delay_info.c_date : delay_info.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) check_hlds.delay_info $(ERR_REDIRECT)

# RULE java_date_on_src
check_hlds.delay_info.java_date : delay_info.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only check_hlds.delay_info $(ERR_REDIRECT)

