# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `check_hlds.mode_debug' in source file `mode_debug.m'.
# Generated by Mercury compiler version rotd-2020-01-16
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
check_hlds.mode_debug.optdate check_hlds.mode_debug.trans_opt_date mode_debug.err check_hlds.mode_debug.c_date check_hlds.mode_debug.java_date : \
		mode_debug.m \
	\
		check_hlds.int0 \
	\
		assoc_list.int \
		bool.int \
		builtin.int \
		hlds.int \
		io.int \
		libs.int \
		list.int \
		maybe.int \
		pair.int \
		parse_tree.int \
		private_builtin.int \
		term.int \
		varset.int \
		check_hlds.mode_info.int \
		hlds.hlds_out.int \
		hlds.instmap.int \
		libs.file_util.int \
		parse_tree.parse_tree_out_info.int \
		parse_tree.parse_tree_out_term.int \
		parse_tree.prog_data.int \
		hlds.hlds_out.hlds_out_mode.int \
	\
		array.int2 \
		bag.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		enum.int2 \
		integer.int2 \
		map.int2 \
		mdbcomp.int2 \
		multi_map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		string.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		check_hlds.delay_info.int2 \
		check_hlds.mode_errors.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_goal.int2 \
		hlds.hlds_inst_mode.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		hlds.pred_table.int2 \
		hlds.vartypes.int2 \
		libs.globals.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.set_of_var.int2

# RULE objs_on_mihs
check_hlds.mode_debug.pic_o check_hlds.mode_debug.$O : \
		array.mih \
		assoc_list.mih \
		bag.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		enum.mih \
		hlds.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		multi_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.delay_info.mih \
		check_hlds.mode_errors.mih \
		check_hlds.mode_info.mih \
		hlds.goal_mode.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_inst_mode.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_out.mih \
		hlds.hlds_pred.mih \
		hlds.instmap.mih \
		hlds.pred_table.mih \
		hlds.vartypes.mih \
		libs.file_util.mih \
		libs.globals.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.parse_tree_out_info.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih \
		hlds.hlds_out.hlds_out_mode.mih

# RULE mh_and_mih_on_c
check_hlds.mode_debug.mh check_hlds.mode_debug.mih : check_hlds.mode_debug.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
check_hlds.mode_debug.module_dep : jmercury/check_hlds__mode_debug.java

else

# RULE module_dep_on_c
check_hlds.mode_debug.module_dep : check_hlds.mode_debug.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
check_hlds.mode_debug.date check_hlds.mode_debug.date0 check_hlds.date : \
		mode_debug.m \
	\
		check_hlds.int0 \
	\
		assoc_list.int3 \
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		term.int3 \
		varset.int3 \
		check_hlds.mode_info.int3 \
		hlds.hlds_out.int3 \
		hlds.instmap.int3 \
		libs.file_util.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.prog_data.int3 \
		hlds.hlds_out.hlds_out_mode.int3 \
	\
		array.int3 \
		bag.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		map.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.delay_info.int3 \
		check_hlds.mode_errors.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.pred_table.int3 \
		hlds.vartypes.int3 \
		libs.globals.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
check_hlds.mode_debug.date0 check_hlds.date0 : \
		mode_debug.m \
	\
		assoc_list.int3 \
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		term.int3 \
		varset.int3 \
		check_hlds.mode_info.int3 \
		hlds.hlds_out.int3 \
		hlds.instmap.int3 \
		libs.file_util.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.prog_data.int3 \
		hlds.hlds_out.hlds_out_mode.int3 \
	\
		array.int3 \
		bag.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		map.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.delay_info.int3 \
		check_hlds.mode_errors.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.pred_table.int3 \
		hlds.vartypes.int3 \
		libs.globals.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3

# RULE foreign_deps_for_.mh
check_hlds.mode_debug.$O : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		check_hlds.mode_debug.mh

# RULE foreign_deps_for_.mh
check_hlds.mode_debug.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		check_hlds.mode_debug.mh

check_hlds.mode_debug.int0 : check_hlds.mode_debug.date0
	@:

check_hlds.mode_debug.int : check_hlds.mode_debug.date
	@:

check_hlds.mode_debug.int2 : check_hlds.mode_debug.date
	@:

check_hlds.mode_debug.int3 : check_hlds.mode_debug.date3
	@:

check_hlds.mode_debug.opt : check_hlds.mode_debug.optdate
	@:

check_hlds.mode_debug.trans_opt : check_hlds.mode_debug.trans_opt_date
	@:

check_hlds.mode_debug.date0 : mode_debug.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) check_hlds.mode_debug

check_hlds.mode_debug.date : mode_debug.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) check_hlds.mode_debug

check_hlds.mode_debug.date3 : mode_debug.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) check_hlds.mode_debug

check_hlds.mode_debug.optdate : mode_debug.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) check_hlds.mode_debug

check_hlds.mode_debug.trans_opt_date : mode_debug.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) check_hlds.mode_debug

check_hlds.mode_debug.c_date : mode_debug.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) check_hlds.mode_debug $(ERR_REDIRECT)

check_hlds.mode_debug.java_date : mode_debug.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only check_hlds.mode_debug $(ERR_REDIRECT)

