# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `check_hlds.typecheck_errors' in source file `typecheck_errors.m'.
# Generated by Mercury compiler version rotd-2024-03-01
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
check_hlds.typecheck_errors.optdate check_hlds.typecheck_errors.trans_opt_date typecheck_errors.err check_hlds.typecheck_errors.c_date check_hlds.typecheck_errors.java_date : \
		typecheck_errors.m \
	\
		check_hlds.int0 \
	\
		assoc_list.int \
		builtin.int \
		hlds.int \
		int.int \
		list.int \
		maybe.int \
		mdbcomp.int \
		pair.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		set.int \
		set_tree234.int \
		string.int \
		term.int \
		varset.int \
		check_hlds.type_assign.int \
		check_hlds.typecheck_error_type_assign.int \
		check_hlds.typecheck_error_util.int \
		check_hlds.typecheck_info.int \
		hlds.hlds_class.int \
		hlds.hlds_error_util.int \
		hlds.hlds_goal.int \
		hlds.hlds_module.int \
		hlds.hlds_out.int \
		hlds.hlds_pred.int \
		mdbcomp.builtin_modules.int \
		mdbcomp.prim_data.int \
		mdbcomp.sym_name.int \
		parse_tree.error_spec.int \
		parse_tree.error_type_util.int \
		parse_tree.parse_tree_out_cons_id.int \
		parse_tree.parse_tree_out_misc.int \
		parse_tree.parse_tree_out_term.int \
		parse_tree.parse_tree_out_type.int \
		parse_tree.prog_data.int \
		parse_tree.prog_type.int \
		parse_tree.prog_type_subst.int \
		parse_tree.prog_type_test.int \
		parse_tree.prog_type_unify.int \
		parse_tree.prog_util.int \
		parse_tree.var_db.int \
		hlds.hlds_out.hlds_out_util.int \
	\
		analysis.int2 \
		array.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		digraph.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		integer.int2 \
		io.int2 \
		libs.int2 \
		map.int2 \
		mode_robdd.int2 \
		multi_map.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		queue.int2 \
		recompilation.int2 \
		robdd.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stack.int2 \
		stream.int2 \
		term_context.int2 \
		time.int2 \
		transform_hlds.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		check_hlds.mode_constraint_robdd.int2 \
		check_hlds.proc_requests.int2 \
		hlds.const_struct.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_clauses.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_dependency_graph.int2 \
		hlds.hlds_inst_mode.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_promise.int2 \
		hlds.hlds_rtti.int2 \
		hlds.inst_graph.int2 \
		hlds.instmap.int2 \
		hlds.pred_name.int2 \
		hlds.pred_table.int2 \
		hlds.special_pred.int2 \
		hlds.status.int2 \
		libs.dependency_graph.int2 \
		libs.globals.int2 \
		libs.indent.int2 \
		libs.options.int2 \
		libs.polyhedron.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
		mode_robdd.tfeirn.int2 \
		parse_tree.module_qual.int2 \
		parse_tree.parse_tree_out_info.int2 \
		parse_tree.parse_tree_output.int2 \
		parse_tree.prog_data_event.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_data_used_modules.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_table.int2 \
		parse_tree.vartypes.int2 \
		recompilation.record_uses.int2 \
		string.builder.int2 \
		transform_hlds.term_constr_errors.int2 \
		transform_hlds.term_constr_main_types.int2 \
		transform_hlds.term_errors.int2 \
		transform_hlds.term_util.int2 \
	\
		check_hlds.typecheck_errors.int \
	\
		check_hlds.int

# RULE objs_on_mihs
check_hlds.typecheck_errors.pic_o check_hlds.typecheck_errors.$O : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		digraph.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		int.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		mode_robdd.mih \
		multi_map.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		queue.mih \
		recompilation.mih \
		require.mih \
		robdd.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		stack.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.mode_constraint_robdd.mih \
		check_hlds.proc_requests.mih \
		check_hlds.type_assign.mih \
		check_hlds.typecheck_error_type_assign.mih \
		check_hlds.typecheck_error_util.mih \
		check_hlds.typecheck_info.mih \
		hlds.const_struct.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_clauses.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_dependency_graph.mih \
		hlds.hlds_error_util.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_inst_mode.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_out.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.hlds_rtti.mih \
		hlds.inst_graph.mih \
		hlds.instmap.mih \
		hlds.pred_name.mih \
		hlds.pred_table.mih \
		hlds.special_pred.mih \
		hlds.status.mih \
		libs.dependency_graph.mih \
		libs.globals.mih \
		libs.indent.mih \
		libs.options.mih \
		libs.polyhedron.mih \
		mdbcomp.builtin_modules.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		mode_robdd.tfeirn.mih \
		parse_tree.error_spec.mih \
		parse_tree.error_type_util.mih \
		parse_tree.module_qual.mih \
		parse_tree.parse_tree_out_cons_id.mih \
		parse_tree.parse_tree_out_info.mih \
		parse_tree.parse_tree_out_misc.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.parse_tree_out_type.mih \
		parse_tree.parse_tree_output.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_event.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_data_used_modules.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_type_subst.mih \
		parse_tree.prog_type_test.mih \
		parse_tree.prog_type_unify.mih \
		parse_tree.prog_util.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih \
		parse_tree.vartypes.mih \
		recompilation.record_uses.mih \
		string.builder.mih \
		transform_hlds.term_constr_errors.mih \
		transform_hlds.term_constr_main_types.mih \
		transform_hlds.term_errors.mih \
		transform_hlds.term_util.mih \
		hlds.hlds_out.hlds_out_util.mih

# RULE mh_and_mih_on_c
check_hlds.typecheck_errors.mh check_hlds.typecheck_errors.mih : check_hlds.typecheck_errors.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
check_hlds.typecheck_errors.module_dep : jmercury/check_hlds__typecheck_errors.java

else

# RULE module_dep_on_c
check_hlds.typecheck_errors.module_dep : check_hlds.typecheck_errors.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   long dep int3s
#   short dep int3s
check_hlds.typecheck_errors.date check_hlds.typecheck_errors.date0 check_hlds.date : \
		typecheck_errors.m \
	\
		check_hlds.int0 \
	\
		assoc_list.int3 \
		builtin.int3 \
		hlds.int3 \
		int.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		set_tree234.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		check_hlds.type_assign.int3 \
		check_hlds.typecheck_error_type_assign.int3 \
		check_hlds.typecheck_error_util.int3 \
		check_hlds.typecheck_info.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_error_util.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_out.int3 \
		hlds.hlds_pred.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.error_type_util.int3 \
		parse_tree.parse_tree_out_cons_id.int3 \
		parse_tree.parse_tree_out_misc.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_out_type.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_type_test.int3 \
		parse_tree.prog_type_unify.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.var_db.int3 \
		hlds.hlds_out.hlds_out_util.int3 \
	\
		analysis.int3 \
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		digraph.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		libs.int3 \
		map.int3 \
		mode_robdd.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		robdd.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		stream.int3 \
		term_context.int3 \
		time.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.proc_requests.int3 \
		hlds.const_struct.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		hlds.pred_table.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.dependency_graph.int3 \
		libs.globals.int3 \
		libs.indent.int3 \
		libs.options.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
		recompilation.record_uses.int3 \
		string.builder.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   long dep int3s
#   short dep int3s
check_hlds.typecheck_errors.date0 check_hlds.date0 : \
		typecheck_errors.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		hlds.int3 \
		int.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		set_tree234.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		check_hlds.type_assign.int3 \
		check_hlds.typecheck_error_type_assign.int3 \
		check_hlds.typecheck_error_util.int3 \
		check_hlds.typecheck_info.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_error_util.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_out.int3 \
		hlds.hlds_pred.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.error_type_util.int3 \
		parse_tree.parse_tree_out_cons_id.int3 \
		parse_tree.parse_tree_out_misc.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_out_type.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_type_test.int3 \
		parse_tree.prog_type_unify.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.var_db.int3 \
		hlds.hlds_out.hlds_out_util.int3 \
	\
		analysis.int3 \
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		digraph.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		libs.int3 \
		map.int3 \
		mode_robdd.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		robdd.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		stream.int3 \
		term_context.int3 \
		time.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.proc_requests.int3 \
		hlds.const_struct.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		hlds.pred_table.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.dependency_graph.int3 \
		libs.globals.int3 \
		libs.indent.int3 \
		libs.options.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
		recompilation.record_uses.int3 \
		string.builder.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE foreign_deps_for_mh
check_hlds.typecheck_errors.$O check_hlds.typecheck_errors.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
check_hlds.typecheck_errors.int0 : check_hlds.typecheck_errors.date0
	@:

# RULE int_on_date
check_hlds.typecheck_errors.int : check_hlds.typecheck_errors.date
	@:

# RULE int2_on_date
check_hlds.typecheck_errors.int2 : check_hlds.typecheck_errors.date
	@:

# RULE int3_on_date3
check_hlds.typecheck_errors.int3 : check_hlds.typecheck_errors.date3
	@:

# RULE opt_on_opt_date
check_hlds.typecheck_errors.opt : check_hlds.typecheck_errors.optdate
	@:

# RULE trans_opt_on_trans_opt_date
check_hlds.typecheck_errors.trans_opt : check_hlds.typecheck_errors.trans_opt_date
	@:

# RULE date0_on_src
check_hlds.typecheck_errors.date0 : typecheck_errors.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) check_hlds.typecheck_errors

# RULE date_on_src
check_hlds.typecheck_errors.date : typecheck_errors.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) check_hlds.typecheck_errors

# RULE date3_on_src
check_hlds.typecheck_errors.date3 : typecheck_errors.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) check_hlds.typecheck_errors

# RULE opt_date_on_src
check_hlds.typecheck_errors.optdate : typecheck_errors.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) check_hlds.typecheck_errors

# RULE trans_opt_date_on_src
check_hlds.typecheck_errors.trans_opt_date : typecheck_errors.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) check_hlds.typecheck_errors

# RULE c_date_on_src
check_hlds.typecheck_errors.c_date : typecheck_errors.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) check_hlds.typecheck_errors $(ERR_REDIRECT)

# RULE java_date_on_src
check_hlds.typecheck_errors.java_date : typecheck_errors.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only check_hlds.typecheck_errors $(ERR_REDIRECT)

