# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `check_hlds.find_bind_var' in source file `find_bind_var.m'.
# Generated by Mercury compiler version rotd-2026-09-06
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
check_hlds.find_bind_var.optdate check_hlds.find_bind_var.trans_opt_date find_bind_var.err check_hlds.find_bind_var.c_date check_hlds.find_bind_var.java_date : \
		find_bind_var.m \
	\
		check_hlds.int0 \
	\
		builtin.int \
		hlds.int \
		list.int \
		map.int \
		maybe.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		term.int \
		term_context.int \
		term_subst.int \
		check_hlds.det_util.int \
		hlds.goal_list_util.int \
		hlds.hlds_goal.int \
		hlds.hlds_markers.int \
		parse_tree.prog_data.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		char.int2 \
		cord.int2 \
		enum.int2 \
		integer.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		set_tree234.int2 \
		sparse_bitset.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		hlds.hlds_proc.int2 \
		hlds.instmap.int2 \
		hlds.pred_proc_id.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_item_pragma.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_db.int2 \
		parse_tree.var_table.int2 \
	\
		check_hlds.find_bind_var.int \
	\
		check_hlds.int

# RULE objs_on_mihs
check_hlds.find_bind_var.$O check_hlds.find_bind_var.pic_o : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		cord.mih \
		enum.mih \
		hlds.mih \
		integer.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		term.mih \
		term_context.mih \
		term_subst.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.det_util.mih \
		hlds.goal_list_util.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_markers.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_proc.mih \
		hlds.instmap.mih \
		hlds.pred_proc_id.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_item_pragma.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih

# RULE mh_and_mih_on_c
check_hlds.find_bind_var.mh check_hlds.find_bind_var.mih : check_hlds.find_bind_var.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
check_hlds.find_bind_var.module_dep : jmercury/check_hlds__find_bind_var.java

else

# RULE module_dep_on_c
check_hlds.find_bind_var.module_dep : check_hlds.find_bind_var.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
check_hlds.find_bind_var.date check_hlds.find_bind_var.date0 check_hlds.date : \
		find_bind_var.m \
	\
		check_hlds.int0 \
	\
		builtin.int3 \
		hlds.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		term.int3 \
		term_context.int3 \
		term_subst.int3 \
		check_hlds.det_util.int3 \
		hlds.goal_list_util.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_markers.int3 \
		parse_tree.prog_data.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_proc.int3 \
		hlds.instmap.int3 \
		hlds.pred_proc_id.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_item_pragma.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
check_hlds.find_bind_var.date0 check_hlds.date0 : \
		find_bind_var.m \
	\
		builtin.int3 \
		hlds.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		term.int3 \
		term_context.int3 \
		term_subst.int3 \
		check_hlds.det_util.int3 \
		hlds.goal_list_util.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_markers.int3 \
		parse_tree.prog_data.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_proc.int3 \
		hlds.instmap.int3 \
		hlds.pred_proc_id.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_item_pragma.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
check_hlds.find_bind_var.$O check_hlds.find_bind_var.pic_o : \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		builtin.mh \
		char.mh \
		cord.mh \
		enum.mh \
		hlds.mh \
		integer.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		set_tree234.mh \
		sparse_bitset.mh \
		term.mh \
		term_context.mh \
		term_subst.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		check_hlds.det_util.mh \
		hlds.goal_list_util.mh \
		hlds.goal_mode.mh \
		hlds.hlds_class.mh \
		hlds.hlds_data.mh \
		hlds.hlds_goal.mh \
		hlds.hlds_llds.mh \
		hlds.hlds_markers.mh \
		hlds.hlds_module.mh \
		hlds.hlds_pred.mh \
		hlds.hlds_proc.mh \
		hlds.instmap.mh \
		hlds.pred_proc_id.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.error_spec.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_item_pragma.mh \
		parse_tree.prog_rename.mh \
		parse_tree.set_of_var.mh \
		parse_tree.var_db.mh \
		parse_tree.var_table.mh

# RULE int0_on_date0
check_hlds.find_bind_var.int0 : check_hlds.find_bind_var.date0
	@:

# RULE int_on_date
check_hlds.find_bind_var.int : check_hlds.find_bind_var.date
	@:

# RULE int2_on_date
check_hlds.find_bind_var.int2 : check_hlds.find_bind_var.date
	@:

# RULE int3_on_date3
check_hlds.find_bind_var.int3 : check_hlds.find_bind_var.date3
	@:

# RULE opt_on_opt_date
check_hlds.find_bind_var.opt : check_hlds.find_bind_var.optdate
	@:

# RULE trans_opt_on_trans_opt_date
check_hlds.find_bind_var.trans_opt : check_hlds.find_bind_var.trans_opt_date
	@:

# RULE date0_on_src
check_hlds.find_bind_var.date0 : find_bind_var.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) check_hlds.find_bind_var

# RULE date_on_src
check_hlds.find_bind_var.date : find_bind_var.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) check_hlds.find_bind_var

# RULE date3_on_src
check_hlds.find_bind_var.date3 : find_bind_var.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) check_hlds.find_bind_var

# RULE opt_date_on_src
check_hlds.find_bind_var.optdate : find_bind_var.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) check_hlds.find_bind_var

# RULE trans_opt_date_on_src
check_hlds.find_bind_var.trans_opt_date : find_bind_var.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) check_hlds.find_bind_var

# RULE c_date_on_src
check_hlds.find_bind_var.c_date : find_bind_var.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) check_hlds.find_bind_var $(ERR_REDIRECT)

# RULE java_date_on_src
check_hlds.find_bind_var.java_date : find_bind_var.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only check_hlds.find_bind_var $(ERR_REDIRECT)

