# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `check_hlds.typecheck_debug' in source file `typecheck_debug.m'.
# Generated by Mercury compiler version rotd-2025-09-05
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
check_hlds.typecheck_debug.optdate check_hlds.typecheck_debug.trans_opt_date typecheck_debug.err check_hlds.typecheck_debug.c_date check_hlds.typecheck_debug.java_date : \
		typecheck_debug.m \
	\
		check_hlds.int0 \
	\
		bool.int \
		builtin.int \
		hlds.int \
		io.int \
		libs.int \
		list.int \
		map.int \
		parse_tree.int \
		private_builtin.int \
		string.int \
		varset.int \
		check_hlds.type_assign.int \
		check_hlds.type_util.int \
		check_hlds.typecheck_info.int \
		hlds.hlds_class.int \
		libs.file_util.int \
		parse_tree.parse_tree_out_term.int \
		parse_tree.parse_tree_out_type.int \
		parse_tree.prog_data.int \
		parse_tree.prog_type.int \
		parse_tree.prog_type_subst.int \
		parse_tree.prog_util.int \
		parse_tree.vartypes.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		enum.int2 \
		integer.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		set_tree234.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_markers.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		hlds.pred_table.int2 \
		hlds.status.int2 \
		libs.globals.int2 \
		libs.maybe_util.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.parse_tree_output.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_db.int2 \
		parse_tree.var_table.int2 \
		string.builder.int2 \
	\
		check_hlds.typecheck_debug.int \
	\
		check_hlds.int

# RULE objs_on_mihs
check_hlds.typecheck_debug.$O check_hlds.typecheck_debug.pic_o : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		enum.mih \
		hlds.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		check_hlds.type_assign.mih \
		check_hlds.type_util.mih \
		check_hlds.typecheck_info.mih \
		hlds.hlds_class.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_markers.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.pred_table.mih \
		hlds.status.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.maybe_util.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.parse_tree_out_type.mih \
		parse_tree.parse_tree_output.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_type_subst.mih \
		parse_tree.prog_util.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih \
		parse_tree.vartypes.mih \
		string.builder.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
check_hlds.typecheck_debug.mh check_hlds.typecheck_debug.mih : check_hlds.typecheck_debug.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
check_hlds.typecheck_debug.module_dep : jmercury/check_hlds__typecheck_debug.java

else

# RULE module_dep_on_c
check_hlds.typecheck_debug.module_dep : check_hlds.typecheck_debug.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
check_hlds.typecheck_debug.date check_hlds.typecheck_debug.date0 check_hlds.date : \
		typecheck_debug.m \
	\
		check_hlds.int0 \
	\
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		string.int3 \
		varset.int3 \
		check_hlds.type_assign.int3 \
		check_hlds.type_util.int3 \
		check_hlds.typecheck_info.int3 \
		hlds.hlds_class.int3 \
		libs.file_util.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_out_type.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.vartypes.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.pred_table.int3 \
		hlds.status.int3 \
		libs.globals.int3 \
		libs.maybe_util.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		string.builder.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
check_hlds.typecheck_debug.date0 check_hlds.date0 : \
		typecheck_debug.m \
	\
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		string.int3 \
		varset.int3 \
		check_hlds.type_assign.int3 \
		check_hlds.type_util.int3 \
		check_hlds.typecheck_info.int3 \
		hlds.hlds_class.int3 \
		libs.file_util.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_out_type.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.vartypes.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.pred_table.int3 \
		hlds.status.int3 \
		libs.globals.int3 \
		libs.maybe_util.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		string.builder.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
check_hlds.typecheck_debug.$O check_hlds.typecheck_debug.pic_o : \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		deconstruct.mh \
		enum.mh \
		hlds.mh \
		integer.mh \
		io.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		ops.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		set.mh \
		set_ordlist.mh \
		set_tree234.mh \
		sparse_bitset.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		univ.mh \
		varset.mh \
		check_hlds.type_assign.mh \
		check_hlds.type_util.mh \
		check_hlds.typecheck_info.mh \
		hlds.hlds_class.mh \
		hlds.hlds_cons.mh \
		hlds.hlds_data.mh \
		hlds.hlds_markers.mh \
		hlds.hlds_module.mh \
		hlds.hlds_pred.mh \
		hlds.pred_table.mh \
		hlds.status.mh \
		io.stream_ops.mh \
		libs.file_util.mh \
		libs.globals.mh \
		libs.maybe_util.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.error_spec.mh \
		parse_tree.parse_tree_out_term.mh \
		parse_tree.parse_tree_out_type.mh \
		parse_tree.parse_tree_output.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_type.mh \
		parse_tree.prog_type_subst.mh \
		parse_tree.prog_util.mh \
		parse_tree.set_of_var.mh \
		parse_tree.var_db.mh \
		parse_tree.var_table.mh \
		parse_tree.vartypes.mh \
		string.builder.mh \
		string.format.mh \
		string.parse_util.mh

# RULE int0_on_date0
check_hlds.typecheck_debug.int0 : check_hlds.typecheck_debug.date0
	@:

# RULE int_on_date
check_hlds.typecheck_debug.int : check_hlds.typecheck_debug.date
	@:

# RULE int2_on_date
check_hlds.typecheck_debug.int2 : check_hlds.typecheck_debug.date
	@:

# RULE int3_on_date3
check_hlds.typecheck_debug.int3 : check_hlds.typecheck_debug.date3
	@:

# RULE opt_on_opt_date
check_hlds.typecheck_debug.opt : check_hlds.typecheck_debug.optdate
	@:

# RULE trans_opt_on_trans_opt_date
check_hlds.typecheck_debug.trans_opt : check_hlds.typecheck_debug.trans_opt_date
	@:

# RULE date0_on_src
check_hlds.typecheck_debug.date0 : typecheck_debug.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) check_hlds.typecheck_debug

# RULE date_on_src
check_hlds.typecheck_debug.date : typecheck_debug.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) check_hlds.typecheck_debug

# RULE date3_on_src
check_hlds.typecheck_debug.date3 : typecheck_debug.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) check_hlds.typecheck_debug

# RULE opt_date_on_src
check_hlds.typecheck_debug.optdate : typecheck_debug.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) check_hlds.typecheck_debug

# RULE trans_opt_date_on_src
check_hlds.typecheck_debug.trans_opt_date : typecheck_debug.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) check_hlds.typecheck_debug

# RULE c_date_on_src
check_hlds.typecheck_debug.c_date : typecheck_debug.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) check_hlds.typecheck_debug $(ERR_REDIRECT)

# RULE java_date_on_src
check_hlds.typecheck_debug.java_date : typecheck_debug.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only check_hlds.typecheck_debug $(ERR_REDIRECT)

