# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.hlds_clauses' in source file `hlds_clauses.m'.
# Generated by Mercury compiler version rotd-2026-08-27
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.hlds_clauses.optdate hlds.hlds_clauses.trans_opt_date hlds_clauses.err hlds.hlds_clauses.c_date hlds.hlds_clauses.java_date : \
		hlds_clauses.m \
	\
		hlds.int0 \
	\
		bool.int \
		builtin.int \
		cord.int \
		int.int \
		libs.int \
		list.int \
		map.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		string.int \
		term.int \
		varset.int \
		hlds.hlds_args.int \
		hlds.hlds_goal.int \
		hlds.hlds_rtti.int \
		hlds.pred_proc_id.int \
		libs.globals.int \
		mdbcomp.prim_data.int \
		parse_tree.error_spec.int \
		parse_tree.prog_data.int \
		parse_tree.prog_util.int \
		parse_tree.var_table.int \
		parse_tree.vartypes.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		counter.int2 \
		deconstruct.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		integer.int2 \
		io.int2 \
		maybe.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_markers.int2 \
		hlds.hlds_module.int2 \
		hlds.instmap.int2 \
		hlds.pred_name.int2 \
		libs.file_util.int2 \
		libs.op_mode.int2 \
		libs.optimization_options.int2 \
		libs.options.int2 \
		libs.trace_params.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.file_names.int2 \
		parse_tree.find_module.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_item_pragma.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.prog_type.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_db.int2 \
		mdbcomp.feedback.feedback_info.int2 \
	\
		hlds.hlds_clauses.int \
	\
		hlds.int

# RULE objs_on_mihs
hlds.hlds_clauses.$O hlds.hlds_clauses.pic_o : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		counter.mih \
		deconstruct.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		int.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		hlds.goal_mode.mih \
		hlds.hlds_args.mih \
		hlds.hlds_class.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_markers.mih \
		hlds.hlds_module.mih \
		hlds.hlds_rtti.mih \
		hlds.instmap.mih \
		hlds.pred_name.mih \
		hlds.pred_proc_id.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.op_mode.mih \
		libs.optimization_options.mih \
		libs.options.mih \
		libs.trace_params.mih \
		mdbcomp.feedback.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.file_names.mih \
		parse_tree.find_module.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_item_pragma.mih \
		parse_tree.prog_rename.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_util.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih \
		parse_tree.vartypes.mih \
		mdbcomp.feedback.feedback_info.mih

# RULE mh_and_mih_on_c
hlds.hlds_clauses.mh hlds.hlds_clauses.mih : hlds.hlds_clauses.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.hlds_clauses.module_dep : jmercury/hlds__hlds_clauses.java

else

# RULE module_dep_on_c
hlds.hlds_clauses.module_dep : hlds.hlds_clauses.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
hlds.hlds_clauses.date hlds.hlds_clauses.date0 hlds.date : \
		hlds_clauses.m \
	\
		hlds.int0 \
	\
		bool.int3 \
		builtin.int3 \
		cord.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		hlds.hlds_args.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_rtti.int3 \
		hlds.pred_proc_id.int3 \
		libs.globals.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		counter.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		maybe.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_module.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		libs.file_util.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.file_names.int3 \
		parse_tree.find_module.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_item_pragma.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		mdbcomp.feedback.feedback_info.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
hlds.hlds_clauses.date0 hlds.date0 : \
		hlds_clauses.m \
	\
		bool.int3 \
		builtin.int3 \
		cord.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		hlds.hlds_args.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_rtti.int3 \
		hlds.pred_proc_id.int3 \
		libs.globals.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		counter.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		maybe.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_module.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		libs.file_util.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.file_names.int3 \
		parse_tree.find_module.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_item_pragma.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		mdbcomp.feedback.feedback_info.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
hlds.hlds_clauses.$O hlds.hlds_clauses.pic_o : \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		counter.mh \
		deconstruct.mh \
		edit_seq.mh \
		enum.mh \
		getopt.mh \
		int.mh \
		integer.mh \
		io.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		ops.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		hlds.goal_mode.mh \
		hlds.hlds_args.mh \
		hlds.hlds_class.mh \
		hlds.hlds_data.mh \
		hlds.hlds_goal.mh \
		hlds.hlds_llds.mh \
		hlds.hlds_markers.mh \
		hlds.hlds_module.mh \
		hlds.hlds_rtti.mh \
		hlds.instmap.mh \
		hlds.pred_name.mh \
		hlds.pred_proc_id.mh \
		io.stream_ops.mh \
		libs.file_util.mh \
		libs.globals.mh \
		libs.op_mode.mh \
		libs.optimization_options.mh \
		libs.options.mh \
		libs.trace_params.mh \
		mdbcomp.feedback.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.error_spec.mh \
		parse_tree.file_names.mh \
		parse_tree.find_module.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_item_pragma.mh \
		parse_tree.prog_rename.mh \
		parse_tree.prog_type.mh \
		parse_tree.prog_util.mh \
		parse_tree.set_of_var.mh \
		parse_tree.var_db.mh \
		parse_tree.var_table.mh \
		parse_tree.vartypes.mh \
		mdbcomp.feedback.feedback_info.mh

# RULE int0_on_date0
hlds.hlds_clauses.int0 : hlds.hlds_clauses.date0
	@:

# RULE int_on_date
hlds.hlds_clauses.int : hlds.hlds_clauses.date
	@:

# RULE int2_on_date
hlds.hlds_clauses.int2 : hlds.hlds_clauses.date
	@:

# RULE int3_on_date3
hlds.hlds_clauses.int3 : hlds.hlds_clauses.date3
	@:

# RULE opt_on_opt_date
hlds.hlds_clauses.opt : hlds.hlds_clauses.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.hlds_clauses.trans_opt : hlds.hlds_clauses.trans_opt_date
	@:

# RULE date0_on_src
hlds.hlds_clauses.date0 : hlds_clauses.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.hlds_clauses

# RULE date_on_src
hlds.hlds_clauses.date : hlds_clauses.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.hlds_clauses

# RULE date3_on_src
hlds.hlds_clauses.date3 : hlds_clauses.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.hlds_clauses

# RULE opt_date_on_src
hlds.hlds_clauses.optdate : hlds_clauses.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.hlds_clauses

# RULE trans_opt_date_on_src
hlds.hlds_clauses.trans_opt_date : hlds_clauses.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.hlds_clauses

# RULE c_date_on_src
hlds.hlds_clauses.c_date : hlds_clauses.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.hlds_clauses $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.hlds_clauses.java_date : hlds_clauses.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.hlds_clauses $(ERR_REDIRECT)

