# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.pred_proc_id' in source file `pred_proc_id.m'.
# Generated by Mercury compiler version rotd-2026-08-22
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.pred_proc_id.optdate hlds.pred_proc_id.trans_opt_date pred_proc_id.err hlds.pred_proc_id.c_date hlds.pred_proc_id.java_date : \
		pred_proc_id.m \
	\
		hlds.int0 \
	\
		builtin.int \
		int.int \
		parse_tree.int \
		private_builtin.int \
		set.int \
		parse_tree.prog_data.int \
	\
		array.int2 \
		assoc_list.int2 \
		bool.int2 \
		char.int2 \
		cord.int2 \
		enum.int2 \
		list.int2 \
		map.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set_ordlist.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_item.int2 \
	\
		hlds.pred_proc_id.int \
	\
		hlds.int

# RULE objs_on_mihs
hlds.pred_proc_id.$O hlds.pred_proc_id.pic_o : \
		array.mih \
		assoc_list.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		cord.mih \
		enum.mih \
		hlds.mih \
		int.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih

# RULE mh_and_mih_on_c
hlds.pred_proc_id.mh hlds.pred_proc_id.mih : hlds.pred_proc_id.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.pred_proc_id.module_dep : jmercury/hlds__pred_proc_id.java

else

# RULE module_dep_on_c
hlds.pred_proc_id.module_dep : hlds.pred_proc_id.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
hlds.pred_proc_id.date hlds.pred_proc_id.date0 hlds.date : \
		pred_proc_id.m \
	\
		hlds.int0 \
	\
		builtin.int3 \
		int.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		set.int3 \
		parse_tree.prog_data.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bool.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_item.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
hlds.pred_proc_id.date0 hlds.date0 : \
		pred_proc_id.m \
	\
		builtin.int3 \
		int.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		set.int3 \
		parse_tree.prog_data.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bool.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_item.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
hlds.pred_proc_id.$O hlds.pred_proc_id.pic_o : \
		array.mh \
		assoc_list.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		cord.mh \
		enum.mh \
		int.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		set.mh \
		set_ordlist.mh \
		term.mh \
		term_context.mh \
		tree234.mh \
		type_desc.mh \
		univ.mh \
		varset.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_item.mh

# RULE int0_on_date0
hlds.pred_proc_id.int0 : hlds.pred_proc_id.date0
	@:

# RULE int_on_date
hlds.pred_proc_id.int : hlds.pred_proc_id.date
	@:

# RULE int2_on_date
hlds.pred_proc_id.int2 : hlds.pred_proc_id.date
	@:

# RULE int3_on_date3
hlds.pred_proc_id.int3 : hlds.pred_proc_id.date3
	@:

# RULE opt_on_opt_date
hlds.pred_proc_id.opt : hlds.pred_proc_id.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.pred_proc_id.trans_opt : hlds.pred_proc_id.trans_opt_date
	@:

# RULE date0_on_src
hlds.pred_proc_id.date0 : pred_proc_id.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.pred_proc_id

# RULE date_on_src
hlds.pred_proc_id.date : pred_proc_id.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.pred_proc_id

# RULE date3_on_src
hlds.pred_proc_id.date3 : pred_proc_id.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.pred_proc_id

# RULE opt_date_on_src
hlds.pred_proc_id.optdate : pred_proc_id.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.pred_proc_id

# RULE trans_opt_date_on_src
hlds.pred_proc_id.trans_opt_date : pred_proc_id.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.pred_proc_id

# RULE c_date_on_src
hlds.pred_proc_id.c_date : pred_proc_id.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.pred_proc_id $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.pred_proc_id.java_date : pred_proc_id.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.pred_proc_id $(ERR_REDIRECT)

