# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.from_ground_term_util' in source file `from_ground_term_util.m'.
# Generated by Mercury compiler version 22.01.4-beta-2022-07-30
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.from_ground_term_util.optdate hlds.from_ground_term_util.trans_opt_date from_ground_term_util.err hlds.from_ground_term_util.c_date hlds.from_ground_term_util.java_date : \
		from_ground_term_util.m \
	\
		hlds.int0 \
	\
		builtin.int \
		cord.int \
		int.int \
		libs.int \
		list.int \
		map.int \
		maybe.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		hlds.goal_util.int \
		hlds.hlds_goal.int \
		libs.globals.int \
		parse_tree.prog_data.int \
		parse_tree.set_of_var.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		getopt.int2 \
		io.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_clauses.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		hlds.hlds_rtti.int2 \
		hlds.instmap.int2 \
		hlds.pred_table.int2 \
		hlds.vartypes.int2 \
		libs.op_mode.int2 \
		libs.optimization_options.int2 \
		libs.options.int2 \
		libs.trace_params.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
	\
		hlds.from_ground_term_util.int \
	\
		hlds.int

# RULE objs_on_mihs
hlds.from_ground_term_util.pic_o hlds.from_ground_term_util.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		int.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		hlds.goal_mode.mih \
		hlds.goal_util.mih \
		hlds.hlds_clauses.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_rtti.mih \
		hlds.instmap.mih \
		hlds.pred_table.mih \
		hlds.vartypes.mih \
		libs.globals.mih \
		libs.op_mode.mih \
		libs.optimization_options.mih \
		libs.options.mih \
		libs.trace_params.mih \
		mdbcomp.feedback.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih

# RULE mh_and_mih_on_c
hlds.from_ground_term_util.mh hlds.from_ground_term_util.mih : hlds.from_ground_term_util.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.from_ground_term_util.module_dep : jmercury/hlds__from_ground_term_util.java

else

# RULE module_dep_on_c
hlds.from_ground_term_util.module_dep : hlds.from_ground_term_util.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
hlds.from_ground_term_util.date hlds.from_ground_term_util.date0 hlds.date : \
		from_ground_term_util.m \
	\
		hlds.int0 \
	\
		builtin.int3 \
		cord.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		hlds.goal_util.int3 \
		hlds.hlds_goal.int3 \
		libs.globals.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_rtti.int3 \
		hlds.instmap.int3 \
		hlds.pred_table.int3 \
		hlds.vartypes.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
hlds.from_ground_term_util.date0 hlds.date0 : \
		from_ground_term_util.m \
	\
		builtin.int3 \
		cord.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		hlds.goal_util.int3 \
		hlds.hlds_goal.int3 \
		libs.globals.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_rtti.int3 \
		hlds.instmap.int3 \
		hlds.pred_table.int3 \
		hlds.vartypes.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3

# RULE foreign_deps_for_mh
hlds.from_ground_term_util.$O hlds.from_ground_term_util.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
hlds.from_ground_term_util.int0 : hlds.from_ground_term_util.date0
	@:

# RULE int_on_date
hlds.from_ground_term_util.int : hlds.from_ground_term_util.date
	@:

# RULE int2_on_date
hlds.from_ground_term_util.int2 : hlds.from_ground_term_util.date
	@:

# RULE int3_on_date3
hlds.from_ground_term_util.int3 : hlds.from_ground_term_util.date3
	@:

# RULE opt_on_opt_date
hlds.from_ground_term_util.opt : hlds.from_ground_term_util.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.from_ground_term_util.trans_opt : hlds.from_ground_term_util.trans_opt_date
	@:

# RULE date0_on_src
hlds.from_ground_term_util.date0 : from_ground_term_util.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.from_ground_term_util

# RULE date_on_src
hlds.from_ground_term_util.date : from_ground_term_util.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.from_ground_term_util

# RULE date3_on_src
hlds.from_ground_term_util.date3 : from_ground_term_util.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.from_ground_term_util

# RULE opt_date_on_src
hlds.from_ground_term_util.optdate : from_ground_term_util.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.from_ground_term_util

# RULE trans_opt_date_on_src
hlds.from_ground_term_util.trans_opt_date : from_ground_term_util.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.from_ground_term_util

# RULE c_date_on_src
hlds.from_ground_term_util.c_date : from_ground_term_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.from_ground_term_util $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.from_ground_term_util.java_date : from_ground_term_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.from_ground_term_util $(ERR_REDIRECT)

