# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.default_func_mode' in source file `default_func_mode.m'.
# Generated by Mercury compiler version rotd-2022-01-28
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.default_func_mode.optdate hlds.default_func_mode.trans_opt_date default_func_mode.err hlds.default_func_mode.c_date hlds.default_func_mode.java_date : \
		default_func_mode.m \
	\
		hlds.int0 \
	\
		builtin.int \
		int.int \
		list.int \
		map.int \
		maybe.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		term.int \
		varset.int \
		hlds.add_pred.int \
		hlds.hlds_pred.int \
		hlds.pred_table.int \
		mdbcomp.prim_data.int \
		parse_tree.prog_data.int \
		parse_tree.prog_mode.int \
	\
		analysis.int2 \
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bool.int2 \
		char.int2 \
		check_hlds.int2 \
		cord.int2 \
		enum.int2 \
		integer.int2 \
		libs.int2 \
		mode_robdd.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		robdd.int2 \
		set.int2 \
		set_ordlist.int2 \
		set_tree234.int2 \
		sparse_bitset.int2 \
		stack.int2 \
		transform_hlds.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		check_hlds.mode_constraint_robdd.int2 \
		check_hlds.mode_errors.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_clauses.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_goal.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_promise.int2 \
		hlds.hlds_rtti.int2 \
		hlds.inst_graph.int2 \
		hlds.instmap.int2 \
		hlds.make_hlds.int2 \
		hlds.status.int2 \
		hlds.vartypes.int2 \
		libs.globals.int2 \
		libs.polyhedron.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.sym_name.int2 \
		mode_robdd.tfeirn.int2 \
		parse_tree.error_util.int2 \
		parse_tree.module_qual.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.set_of_var.int2 \
		transform_hlds.term_constr_errors.int2 \
		transform_hlds.term_constr_main_types.int2 \
		transform_hlds.term_errors.int2 \
		transform_hlds.term_util.int2 \
	\
		hlds.default_func_mode.int \
	\
		hlds.int

# RULE objs_on_mihs
hlds.default_func_mode.pic_o hlds.default_func_mode.$O : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		cord.mih \
		enum.mih \
		hlds.mih \
		int.mih \
		integer.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		mode_robdd.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		robdd.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		stack.mih \
		term.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.mode_constraint_robdd.mih \
		check_hlds.mode_errors.mih \
		hlds.add_pred.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_clauses.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.hlds_rtti.mih \
		hlds.inst_graph.mih \
		hlds.instmap.mih \
		hlds.make_hlds.mih \
		hlds.pred_table.mih \
		hlds.status.mih \
		hlds.vartypes.mih \
		libs.globals.mih \
		libs.polyhedron.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		mode_robdd.tfeirn.mih \
		parse_tree.error_util.mih \
		parse_tree.module_qual.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_mode.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih \
		transform_hlds.term_constr_errors.mih \
		transform_hlds.term_constr_main_types.mih \
		transform_hlds.term_errors.mih \
		transform_hlds.term_util.mih

# RULE mh_and_mih_on_c
hlds.default_func_mode.mh hlds.default_func_mode.mih : hlds.default_func_mode.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.default_func_mode.module_dep : jmercury/hlds__default_func_mode.java

else

# RULE module_dep_on_c
hlds.default_func_mode.module_dep : hlds.default_func_mode.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
hlds.default_func_mode.date hlds.default_func_mode.date0 hlds.date : \
		default_func_mode.m \
	\
		hlds.int0 \
	\
		builtin.int3 \
		int.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		term.int3 \
		varset.int3 \
		hlds.add_pred.int3 \
		hlds.hlds_pred.int3 \
		hlds.pred_table.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_mode.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		check_hlds.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		libs.int3 \
		mode_robdd.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		robdd.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.mode_errors.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.make_hlds.int3 \
		hlds.status.int3 \
		hlds.vartypes.int3 \
		libs.globals.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_util.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
hlds.default_func_mode.date0 hlds.date0 : \
		default_func_mode.m \
	\
		builtin.int3 \
		int.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		term.int3 \
		varset.int3 \
		hlds.add_pred.int3 \
		hlds.hlds_pred.int3 \
		hlds.pred_table.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_mode.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		check_hlds.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		libs.int3 \
		mode_robdd.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		robdd.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.mode_errors.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.make_hlds.int3 \
		hlds.status.int3 \
		hlds.vartypes.int3 \
		libs.globals.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_util.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE foreign_deps_for_mh
hlds.default_func_mode.$O hlds.default_func_mode.pic_o : array.mh

# RULE int0_on_date0
hlds.default_func_mode.int0 : hlds.default_func_mode.date0
	@:

# RULE int_on_date
hlds.default_func_mode.int : hlds.default_func_mode.date
	@:

# RULE int2_on_date
hlds.default_func_mode.int2 : hlds.default_func_mode.date
	@:

# RULE int3_on_date3
hlds.default_func_mode.int3 : hlds.default_func_mode.date3
	@:

# RULE opt_on_opt_date
hlds.default_func_mode.opt : hlds.default_func_mode.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.default_func_mode.trans_opt : hlds.default_func_mode.trans_opt_date
	@:

# RULE date0_on_src
hlds.default_func_mode.date0 : default_func_mode.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.default_func_mode

# RULE date_on_src
hlds.default_func_mode.date : default_func_mode.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.default_func_mode

# RULE date3_on_src
hlds.default_func_mode.date3 : default_func_mode.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.default_func_mode

# RULE opt_date_on_src
hlds.default_func_mode.optdate : default_func_mode.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.default_func_mode

# RULE trans_opt_date_on_src
hlds.default_func_mode.trans_opt_date : default_func_mode.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.default_func_mode

# RULE c_date_on_src
hlds.default_func_mode.c_date : default_func_mode.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.default_func_mode $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.default_func_mode.java_date : default_func_mode.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.default_func_mode $(ERR_REDIRECT)

