# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.var_table' in source file `var_table.m'.
# Generated by Mercury compiler version rotd-2022-04-02
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.var_table.optdate hlds.var_table.trans_opt_date var_table.err hlds.var_table.c_date hlds.var_table.java_date : \
		var_table.m \
	\
		hlds.int0 \
	\
		assoc_list.int \
		builtin.int \
		check_hlds.int \
		list.int \
		map.int \
		maybe.int \
		pair.int \
		parse_tree.int \
		private_builtin.int \
		set.int \
		string.int \
		term.int \
		varset.int \
		check_hlds.type_util.int \
		hlds.hlds_module.int \
		hlds.vartypes.int \
		parse_tree.prog_data.int \
		parse_tree.prog_type.int \
		parse_tree.prog_type_subst.int \
		string.format.int \
		string.parse_util.int \
	\
		analysis.int2 \
		bimap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		digraph.int2 \
		enum.int2 \
		integer.int2 \
		libs.int2 \
		mdbcomp.int2 \
		multi_map.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		queue.int2 \
		recompilation.int2 \
		set_ordlist.int2 \
		set_tree234.int2 \
		sparse_bitset.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		check_hlds.proc_requests.int2 \
		hlds.const_struct.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_dependency_graph.int2 \
		hlds.hlds_inst_mode.int2 \
		hlds.hlds_pred.int2 \
		hlds.hlds_promise.int2 \
		hlds.pred_table.int2 \
		hlds.special_pred.int2 \
		hlds.status.int2 \
		libs.dependency_graph.int2 \
		libs.globals.int2 \
		libs.timestamp.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.file_names.int2 \
		parse_tree.module_qual.int2 \
		parse_tree.prog_data_event.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_data_used_modules.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.set_of_var.int2 \
	\
		hlds.var_table.int \
	\
		hlds.int

# RULE objs_on_mihs
hlds.var_table.pic_o hlds.var_table.$O : \
		analysis.mih \
		assoc_list.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		digraph.mih \
		enum.mih \
		hlds.mih \
		integer.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		multi_map.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		queue.mih \
		recompilation.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		string.mih \
		term.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.proc_requests.mih \
		check_hlds.type_util.mih \
		hlds.const_struct.mih \
		hlds.hlds_class.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_dependency_graph.mih \
		hlds.hlds_inst_mode.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.pred_table.mih \
		hlds.special_pred.mih \
		hlds.status.mih \
		hlds.var_table.mih \
		hlds.vartypes.mih \
		libs.dependency_graph.mih \
		libs.globals.mih \
		libs.timestamp.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.file_names.mih \
		parse_tree.module_qual.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_event.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_data_used_modules.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_type_subst.mih \
		parse_tree.set_of_var.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
hlds.var_table.mh hlds.var_table.mih : hlds.var_table.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.var_table.module_dep : jmercury/hlds__var_table.java

else

# RULE module_dep_on_c
hlds.var_table.module_dep : hlds.var_table.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
hlds.var_table.date hlds.var_table.date0 hlds.date : \
		var_table.m \
	\
		hlds.int0 \
	\
		assoc_list.int3 \
		builtin.int3 \
		check_hlds.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		set.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		check_hlds.type_util.int3 \
		hlds.hlds_module.int3 \
		hlds.vartypes.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		analysis.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		digraph.int3 \
		enum.int3 \
		integer.int3 \
		libs.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.proc_requests.int3 \
		hlds.const_struct.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_promise.int3 \
		hlds.pred_table.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.dependency_graph.int3 \
		libs.globals.int3 \
		libs.timestamp.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.file_names.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
hlds.var_table.date0 hlds.date0 : \
		var_table.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		check_hlds.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		set.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		check_hlds.type_util.int3 \
		hlds.hlds_module.int3 \
		hlds.vartypes.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		analysis.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		digraph.int3 \
		enum.int3 \
		integer.int3 \
		libs.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		check_hlds.proc_requests.int3 \
		hlds.const_struct.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_promise.int3 \
		hlds.pred_table.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.dependency_graph.int3 \
		libs.globals.int3 \
		libs.timestamp.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.file_names.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.set_of_var.int3

# RULE int0_on_date0
hlds.var_table.int0 : hlds.var_table.date0
	@:

# RULE int_on_date
hlds.var_table.int : hlds.var_table.date
	@:

# RULE int2_on_date
hlds.var_table.int2 : hlds.var_table.date
	@:

# RULE int3_on_date3
hlds.var_table.int3 : hlds.var_table.date3
	@:

# RULE opt_on_opt_date
hlds.var_table.opt : hlds.var_table.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.var_table.trans_opt : hlds.var_table.trans_opt_date
	@:

# RULE date0_on_src
hlds.var_table.date0 : var_table.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.var_table

# RULE date_on_src
hlds.var_table.date : var_table.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.var_table

# RULE date3_on_src
hlds.var_table.date3 : var_table.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.var_table

# RULE opt_date_on_src
hlds.var_table.optdate : var_table.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.var_table

# RULE trans_opt_date_on_src
hlds.var_table.trans_opt_date : var_table.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.var_table

# RULE c_date_on_src
hlds.var_table.c_date : var_table.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.var_table $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.var_table.java_date : var_table.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.var_table $(ERR_REDIRECT)

