# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.hlds_promise' in source file `hlds_promise.m'.
# Generated by Mercury compiler version rotd-2026-08-20
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.hlds_promise.optdate hlds.hlds_promise.trans_opt_date hlds_promise.err hlds.hlds_promise.c_date hlds.hlds_promise.java_date : \
		hlds_promise.m \
	\
		hlds.int0 \
	\
		builtin.int \
		counter.int \
		list.int \
		map.int \
		multi_map.int \
		private_builtin.int \
		hlds.pred_proc_id.int \
	\
		assoc_list.int2 \
		char.int2 \
		cord.int2 \
		enum.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		pair.int2 \
		parse_tree.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_item.int2 \
	\
		hlds.hlds_promise.int \
	\
		hlds.int

# RULE objs_on_mihs
hlds.hlds_promise.$O hlds.hlds_promise.pic_o : \
		assoc_list.mih \
		builtin.mih \
		char.mih \
		cord.mih \
		counter.mih \
		enum.mih \
		hlds.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		multi_map.mih \
		one_or_more.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		hlds.pred_proc_id.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih

# RULE mh_and_mih_on_c
hlds.hlds_promise.mh hlds.hlds_promise.mih : hlds.hlds_promise.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.hlds_promise.module_dep : jmercury/hlds__hlds_promise.java

else

# RULE module_dep_on_c
hlds.hlds_promise.module_dep : hlds.hlds_promise.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
hlds.hlds_promise.date hlds.hlds_promise.date0 hlds.date : \
		hlds_promise.m \
	\
		hlds.int0 \
	\
		builtin.int3 \
		counter.int3 \
		list.int3 \
		map.int3 \
		multi_map.int3 \
		private_builtin.int3 \
		hlds.pred_proc_id.int3 \
	\
		assoc_list.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		parse_tree.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
hlds.hlds_promise.date0 hlds.date0 : \
		hlds_promise.m \
	\
		builtin.int3 \
		counter.int3 \
		list.int3 \
		map.int3 \
		multi_map.int3 \
		private_builtin.int3 \
		hlds.pred_proc_id.int3 \
	\
		assoc_list.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		parse_tree.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
hlds.hlds_promise.$O hlds.hlds_promise.pic_o : \
		assoc_list.mh \
		builtin.mh \
		char.mh \
		cord.mh \
		counter.mh \
		enum.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		multi_map.mh \
		one_or_more.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		set.mh \
		set_ordlist.mh \
		term.mh \
		term_context.mh \
		tree234.mh \
		type_desc.mh \
		univ.mh \
		varset.mh \
		hlds.pred_proc_id.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_item.mh

# RULE int0_on_date0
hlds.hlds_promise.int0 : hlds.hlds_promise.date0
	@:

# RULE int_on_date
hlds.hlds_promise.int : hlds.hlds_promise.date
	@:

# RULE int2_on_date
hlds.hlds_promise.int2 : hlds.hlds_promise.date
	@:

# RULE int3_on_date3
hlds.hlds_promise.int3 : hlds.hlds_promise.date3
	@:

# RULE opt_on_opt_date
hlds.hlds_promise.opt : hlds.hlds_promise.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.hlds_promise.trans_opt : hlds.hlds_promise.trans_opt_date
	@:

# RULE date0_on_src
hlds.hlds_promise.date0 : hlds_promise.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.hlds_promise

# RULE date_on_src
hlds.hlds_promise.date : hlds_promise.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.hlds_promise

# RULE date3_on_src
hlds.hlds_promise.date3 : hlds_promise.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.hlds_promise

# RULE opt_date_on_src
hlds.hlds_promise.optdate : hlds_promise.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.hlds_promise

# RULE trans_opt_date_on_src
hlds.hlds_promise.trans_opt_date : hlds_promise.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.hlds_promise

# RULE c_date_on_src
hlds.hlds_promise.c_date : hlds_promise.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.hlds_promise $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.hlds_promise.java_date : hlds_promise.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.hlds_promise $(ERR_REDIRECT)

