# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hlds.make_hlds.superhomogeneous_util' in source file `superhomogeneous_util.m'.
# Generated by Mercury compiler version rotd-2026-01-26
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
hlds.make_hlds.superhomogeneous_util.optdate hlds.make_hlds.superhomogeneous_util.trans_opt_date superhomogeneous_util.err hlds.make_hlds.superhomogeneous_util.c_date hlds.make_hlds.superhomogeneous_util.java_date : \
		superhomogeneous_util.m \
	\
		hlds.int0 \
		hlds.make_hlds.int0 \
	\
		builtin.int \
		cord.int \
		list.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		term.int \
		hlds.hlds_goal.int \
		hlds.hlds_pred.int \
		mdbcomp.prim_data.int \
		parse_tree.prog_data.int \
		hlds.make_hlds.state_var.int \
	\
		analysis.int2 \
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bool.int2 \
		char.int2 \
		check_hlds.int2 \
		enum.int2 \
		integer.int2 \
		libs.int2 \
		map.int2 \
		maybe.int2 \
		mode_robdd.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		robdd.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stack.int2 \
		term_context.int2 \
		transform_hlds.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		analysis.framework.int2 \
		check_hlds.mode_constraint_robdd.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_clauses.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_markers.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_promise.int2 \
		hlds.hlds_rtti.int2 \
		hlds.inst_graph.int2 \
		hlds.instmap.int2 \
		hlds.pred_name.int2 \
		hlds.pred_table.int2 \
		hlds.status.int2 \
		libs.file_util.int2 \
		libs.globals.int2 \
		libs.polyhedron.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.sym_name.int2 \
		mode_robdd.tfeirn.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_db.int2 \
		parse_tree.var_table.int2 \
		transform_hlds.term_constr_errors.int2 \
		transform_hlds.term_constr_main_types.int2 \
		transform_hlds.term_errors.int2 \
		transform_hlds.term_util.int2 \
		hlds.make_hlds.goal_expr_to_goal.int2 \
		hlds.make_hlds.qual_info.int2 \
	\
		hlds.make_hlds.superhomogeneous_util.int \
	\
		hlds.int \
		hlds.make_hlds.int

# RULE objs_on_mihs
hlds.make_hlds.superhomogeneous_util.$O hlds.make_hlds.superhomogeneous_util.pic_o : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		cord.mih \
		enum.mih \
		hlds.mih \
		integer.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		mode_robdd.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		robdd.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stack.mih \
		term.mih \
		term_context.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		analysis.framework.mih \
		check_hlds.mode_constraint_robdd.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_clauses.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_markers.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.hlds_rtti.mih \
		hlds.inst_graph.mih \
		hlds.instmap.mih \
		hlds.make_hlds.mih \
		hlds.pred_name.mih \
		hlds.pred_table.mih \
		hlds.status.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.polyhedron.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		mode_robdd.tfeirn.mih \
		parse_tree.error_spec.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih \
		transform_hlds.term_constr_errors.mih \
		transform_hlds.term_constr_main_types.mih \
		transform_hlds.term_errors.mih \
		transform_hlds.term_util.mih \
		hlds.make_hlds.goal_expr_to_goal.mih \
		hlds.make_hlds.qual_info.mih \
		hlds.make_hlds.state_var.mih

# RULE mh_and_mih_on_c
hlds.make_hlds.superhomogeneous_util.mh hlds.make_hlds.superhomogeneous_util.mih : hlds.make_hlds.superhomogeneous_util.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hlds.make_hlds.superhomogeneous_util.module_dep : jmercury/hlds__make_hlds__superhomogeneous_util.java

else

# RULE module_dep_on_c
hlds.make_hlds.superhomogeneous_util.module_dep : hlds.make_hlds.superhomogeneous_util.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
hlds.make_hlds.superhomogeneous_util.date hlds.make_hlds.superhomogeneous_util.date0 hlds.date hlds.make_hlds.date : \
		superhomogeneous_util.m \
	\
		hlds.int0 \
		hlds.make_hlds.int0 \
	\
		builtin.int3 \
		cord.int3 \
		list.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		term.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_pred.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_data.int3 \
		hlds.make_hlds.state_var.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		check_hlds.int3 \
		enum.int3 \
		integer.int3 \
		libs.int3 \
		map.int3 \
		maybe.int3 \
		mode_robdd.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		robdd.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		term_context.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		analysis.framework.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		hlds.pred_table.int3 \
		hlds.status.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3 \
		hlds.make_hlds.goal_expr_to_goal.int3 \
		hlds.make_hlds.qual_info.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
hlds.make_hlds.superhomogeneous_util.date0 hlds.date0 hlds.make_hlds.date0 : \
		superhomogeneous_util.m \
	\
		builtin.int3 \
		cord.int3 \
		list.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		term.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_pred.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_data.int3 \
		hlds.make_hlds.state_var.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		check_hlds.int3 \
		enum.int3 \
		integer.int3 \
		libs.int3 \
		map.int3 \
		maybe.int3 \
		mode_robdd.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		robdd.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		term_context.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		analysis.framework.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_markers.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		hlds.pred_table.int3 \
		hlds.status.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3 \
		hlds.make_hlds.goal_expr_to_goal.int3 \
		hlds.make_hlds.qual_info.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
hlds.make_hlds.superhomogeneous_util.$O hlds.make_hlds.superhomogeneous_util.pic_o : \
		analysis.mh \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		check_hlds.mh \
		cord.mh \
		enum.mh \
		integer.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		mode_robdd.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		robdd.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		stack.mh \
		term.mh \
		term_context.mh \
		transform_hlds.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		analysis.framework.mh \
		check_hlds.mode_constraint_robdd.mh \
		hlds.goal_mode.mh \
		hlds.hlds_class.mh \
		hlds.hlds_clauses.mh \
		hlds.hlds_cons.mh \
		hlds.hlds_data.mh \
		hlds.hlds_goal.mh \
		hlds.hlds_llds.mh \
		hlds.hlds_markers.mh \
		hlds.hlds_module.mh \
		hlds.hlds_pred.mh \
		hlds.hlds_promise.mh \
		hlds.hlds_rtti.mh \
		hlds.inst_graph.mh \
		hlds.instmap.mh \
		hlds.pred_name.mh \
		hlds.pred_table.mh \
		hlds.status.mh \
		libs.file_util.mh \
		libs.globals.mh \
		libs.polyhedron.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.program_representation.mh \
		mdbcomp.sym_name.mh \
		mode_robdd.tfeirn.mh \
		parse_tree.error_spec.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_rename.mh \
		parse_tree.set_of_var.mh \
		parse_tree.var_db.mh \
		parse_tree.var_table.mh \
		transform_hlds.term_constr_errors.mh \
		transform_hlds.term_constr_main_types.mh \
		transform_hlds.term_errors.mh \
		transform_hlds.term_util.mh \
		hlds.make_hlds.goal_expr_to_goal.mh \
		hlds.make_hlds.qual_info.mh \
		hlds.make_hlds.state_var.mh

# RULE int0_on_date0
hlds.make_hlds.superhomogeneous_util.int0 : hlds.make_hlds.superhomogeneous_util.date0
	@:

# RULE int_on_date
hlds.make_hlds.superhomogeneous_util.int : hlds.make_hlds.superhomogeneous_util.date
	@:

# RULE int2_on_date
hlds.make_hlds.superhomogeneous_util.int2 : hlds.make_hlds.superhomogeneous_util.date
	@:

# RULE int3_on_date3
hlds.make_hlds.superhomogeneous_util.int3 : hlds.make_hlds.superhomogeneous_util.date3
	@:

# RULE opt_on_opt_date
hlds.make_hlds.superhomogeneous_util.opt : hlds.make_hlds.superhomogeneous_util.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hlds.make_hlds.superhomogeneous_util.trans_opt : hlds.make_hlds.superhomogeneous_util.trans_opt_date
	@:

# RULE date0_on_src
hlds.make_hlds.superhomogeneous_util.date0 : superhomogeneous_util.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) hlds.make_hlds.superhomogeneous_util

# RULE date_on_src
hlds.make_hlds.superhomogeneous_util.date : superhomogeneous_util.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) hlds.make_hlds.superhomogeneous_util

# RULE date3_on_src
hlds.make_hlds.superhomogeneous_util.date3 : superhomogeneous_util.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) hlds.make_hlds.superhomogeneous_util

# RULE opt_date_on_src
hlds.make_hlds.superhomogeneous_util.optdate : superhomogeneous_util.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) hlds.make_hlds.superhomogeneous_util

# RULE trans_opt_date_on_src
hlds.make_hlds.superhomogeneous_util.trans_opt_date : superhomogeneous_util.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) hlds.make_hlds.superhomogeneous_util

# RULE c_date_on_src
hlds.make_hlds.superhomogeneous_util.c_date : superhomogeneous_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) hlds.make_hlds.superhomogeneous_util $(ERR_REDIRECT)

# RULE java_date_on_src
hlds.make_hlds.superhomogeneous_util.java_date : superhomogeneous_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only hlds.make_hlds.superhomogeneous_util $(ERR_REDIRECT)

