# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `libs.va_map' in source file `va_map.m'.
# Generated by Mercury compiler version rotd-2025-07-09
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
libs.va_map.optdate libs.va_map.trans_opt_date va_map.err libs.va_map.c_date libs.va_map.java_date : \
		va_map.m \
	\
		libs.int0 \
	\
		builtin.int \
		int.int \
		private_builtin.int \
		uint.int \
		version_array.int \
	\
		array.int2 \
		assoc_list.int2 \
		enum.int2 \
		list.int2 \
		map.int2 \
		maybe.int2 \
		pair.int2 \
		pretty_printer.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		libs.va_map.int \
	\
		libs.int

# RULE objs_on_mihs
libs.va_map.pic_o libs.va_map.$O : \
		array.mih \
		assoc_list.mih \
		builtin.mih \
		enum.mih \
		int.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		uint.mih \
		univ.mih \
		version_array.mih

# RULE mh_and_mih_on_c
libs.va_map.mh libs.va_map.mih : libs.va_map.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
libs.va_map.module_dep : jmercury/libs__va_map.java

else

# RULE module_dep_on_c
libs.va_map.module_dep : libs.va_map.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
libs.va_map.date libs.va_map.date0 libs.date : \
		va_map.m \
	\
		libs.int0 \
	\
		builtin.int3 \
		int.int3 \
		private_builtin.int3 \
		uint.int3 \
		version_array.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
libs.va_map.date0 libs.date0 : \
		va_map.m \
	\
		builtin.int3 \
		int.int3 \
		private_builtin.int3 \
		uint.int3 \
		version_array.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
libs.va_map.$O libs.va_map.pic_o : \
		array.mh \
		version_array.mh

# RULE int0_on_date0
libs.va_map.int0 : libs.va_map.date0
	@:

# RULE int_on_date
libs.va_map.int : libs.va_map.date
	@:

# RULE int2_on_date
libs.va_map.int2 : libs.va_map.date
	@:

# RULE int3_on_date3
libs.va_map.int3 : libs.va_map.date3
	@:

# RULE opt_on_opt_date
libs.va_map.opt : libs.va_map.optdate
	@:

# RULE trans_opt_on_trans_opt_date
libs.va_map.trans_opt : libs.va_map.trans_opt_date
	@:

# RULE date0_on_src
libs.va_map.date0 : va_map.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) libs.va_map

# RULE date_on_src
libs.va_map.date : va_map.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) libs.va_map

# RULE date3_on_src
libs.va_map.date3 : va_map.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) libs.va_map

# RULE opt_date_on_src
libs.va_map.optdate : va_map.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) libs.va_map

# RULE trans_opt_date_on_src
libs.va_map.trans_opt_date : va_map.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) libs.va_map

# RULE c_date_on_src
libs.va_map.c_date : va_map.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) libs.va_map $(ERR_REDIRECT)

# RULE java_date_on_src
libs.va_map.java_date : va_map.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only libs.va_map $(ERR_REDIRECT)

