# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `libs.optimization_options' in source file `optimization_options.m'.
# Generated by Mercury compiler version rotd-2025-09-16
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
libs.optimization_options.optdate libs.optimization_options.trans_opt_date optimization_options.err libs.optimization_options.c_date libs.optimization_options.java_date : \
		optimization_options.m \
	\
		libs.int0 \
	\
		bool.int \
		builtin.int \
		getopt.int \
		int.int \
		list.int \
		map.int \
		private_builtin.int \
		string.int \
		libs.options.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		enum.int2 \
		io.int2 \
		maybe.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		libs.optdb_help.int2 \
		libs.option_categories.int2 \
	\
		libs.optimization_options.int \
	\
		libs.int

# RULE objs_on_mihs
libs.optimization_options.$O libs.optimization_options.pic_o : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		enum.mih \
		getopt.mih \
		int.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		libs.optdb_help.mih \
		libs.optimization_options.mih \
		libs.option_categories.mih \
		libs.options.mih

# RULE mh_and_mih_on_c
libs.optimization_options.mh libs.optimization_options.mih : libs.optimization_options.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
libs.optimization_options.module_dep : jmercury/libs__optimization_options.java

else

# RULE module_dep_on_c
libs.optimization_options.module_dep : libs.optimization_options.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
libs.optimization_options.date libs.optimization_options.date0 libs.date : \
		optimization_options.m \
	\
		libs.int0 \
	\
		bool.int3 \
		builtin.int3 \
		getopt.int3 \
		int.int3 \
		list.int3 \
		map.int3 \
		private_builtin.int3 \
		string.int3 \
		libs.options.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		io.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		libs.optdb_help.int3 \
		libs.option_categories.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
libs.optimization_options.date0 libs.date0 : \
		optimization_options.m \
	\
		bool.int3 \
		builtin.int3 \
		getopt.int3 \
		int.int3 \
		list.int3 \
		map.int3 \
		private_builtin.int3 \
		string.int3 \
		libs.options.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		io.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		libs.optdb_help.int3 \
		libs.option_categories.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
libs.optimization_options.$O libs.optimization_options.pic_o : \
		array.mh \
		assoc_list.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		deconstruct.mh \
		enum.mh \
		getopt.mh \
		int.mh \
		io.mh \
		list.mh \
		map.mh \
		maybe.mh \
		ops.mh \
		pair.mh \
		pretty_printer.mh \
		private_builtin.mh \
		set.mh \
		set_ordlist.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		univ.mh \
		io.stream_ops.mh \
		libs.optdb_help.mh \
		libs.option_categories.mh \
		libs.options.mh

# RULE int0_on_date0
libs.optimization_options.int0 : libs.optimization_options.date0
	@:

# RULE int_on_date
libs.optimization_options.int : libs.optimization_options.date
	@:

# RULE int2_on_date
libs.optimization_options.int2 : libs.optimization_options.date
	@:

# RULE int3_on_date3
libs.optimization_options.int3 : libs.optimization_options.date3
	@:

# RULE opt_on_opt_date
libs.optimization_options.opt : libs.optimization_options.optdate
	@:

# RULE trans_opt_on_trans_opt_date
libs.optimization_options.trans_opt : libs.optimization_options.trans_opt_date
	@:

# RULE date0_on_src
libs.optimization_options.date0 : optimization_options.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) libs.optimization_options

# RULE date_on_src
libs.optimization_options.date : optimization_options.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) libs.optimization_options

# RULE date3_on_src
libs.optimization_options.date3 : optimization_options.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) libs.optimization_options

# RULE opt_date_on_src
libs.optimization_options.optdate : optimization_options.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) libs.optimization_options

# RULE trans_opt_date_on_src
libs.optimization_options.trans_opt_date : optimization_options.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) libs.optimization_options

# RULE c_date_on_src
libs.optimization_options.c_date : optimization_options.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) libs.optimization_options $(ERR_REDIRECT)

# RULE java_date_on_src
libs.optimization_options.java_date : optimization_options.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only libs.optimization_options $(ERR_REDIRECT)

