# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `libs.md4' in source file `md4.m'.
# Generated by Mercury compiler version rotd-2020-05-30
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   type_repn self dep
libs.md4.optdate libs.md4.trans_opt_date md4.err libs.md4.c_date libs.md4.java_date : \
		md4.m \
	\
		libs.int0 \
	\
		builtin.int \
		private_builtin.int \
		require.int \
	\
		libs.md4.int

# RULE objs_on_mihs
libs.md4.pic_o libs.md4.$O : \
		builtin.mih \
		libs.mih \
		private_builtin.mih \
		require.mih

# RULE mh_and_mih_on_c
libs.md4.mh libs.md4.mih : libs.md4.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
libs.md4.module_dep : jmercury/libs__md4.java

else

# RULE module_dep_on_c
libs.md4.module_dep : libs.md4.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
libs.md4.date libs.md4.date0 libs.date : \
		md4.m \
	\
		libs.int0 \
	\
		builtin.int3 \
		private_builtin.int3 \
		require.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
libs.md4.date0 libs.date0 : \
		md4.m \
	\
		builtin.int3 \
		private_builtin.int3 \
		require.int3

# RULE int0_on_date0
libs.md4.int0 : libs.md4.date0
	@:

# RULE int_on_date
libs.md4.int : libs.md4.date
	@:

# RULE int2_on_date
libs.md4.int2 : libs.md4.date
	@:

# RULE int3_on_date3
libs.md4.int3 : libs.md4.date3
	@:

# RULE opt_on_opt_date
libs.md4.opt : libs.md4.optdate
	@:

# RULE trans_opt_on_trans_opt_date
libs.md4.trans_opt : libs.md4.trans_opt_date
	@:

# RULE date0_on_src
libs.md4.date0 : md4.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) libs.md4

# RULE date_on_src
libs.md4.date : md4.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) libs.md4

# RULE date3_on_src
libs.md4.date3 : md4.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) libs.md4

# RULE opt_date_on_src
libs.md4.optdate : md4.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) libs.md4

# RULE trans_opt_date_on_src
libs.md4.trans_opt_date : md4.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) libs.md4

# RULE c_date_on_src
libs.md4.c_date : md4.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) libs.md4 $(ERR_REDIRECT)

# RULE java_date_on_src
libs.md4.java_date : md4.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only libs.md4 $(ERR_REDIRECT)

