# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `libs.process_util' in source file `process_util.m'.
# Generated by Mercury compiler version rotd-2026-08-10
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
libs.process_util.optdate libs.process_util.trans_opt_date process_util.err libs.process_util.c_date libs.process_util.java_date : \
		process_util.m \
	\
		libs.int0 \
	\
		bool.int \
		builtin.int \
		io.int \
		list.int \
		maybe.int \
		private_builtin.int \
		require.int \
		string.int \
		io.call_system.int \
		libs.maybe_util.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		libs.process_util.int \
	\
		libs.int

# RULE objs_on_mihs
libs.process_util.$O libs.process_util.pic_o : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		io.call_system.mih \
		libs.maybe_util.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
libs.process_util.mh libs.process_util.mih : libs.process_util.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
libs.process_util.module_dep : jmercury/libs__process_util.java

else

# RULE module_dep_on_c
libs.process_util.module_dep : libs.process_util.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
libs.process_util.date libs.process_util.date0 libs.date : \
		process_util.m \
	\
		libs.int0 \
	\
		bool.int3 \
		builtin.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		io.call_system.int3 \
		libs.maybe_util.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
libs.process_util.date0 libs.date0 : \
		process_util.m \
	\
		bool.int3 \
		builtin.int3 \
		io.int3 \
		list.int3 \
		maybe.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		io.call_system.int3 \
		libs.maybe_util.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
libs.process_util.$O libs.process_util.pic_o : \
		array.mh \
		assoc_list.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		deconstruct.mh \
		enum.mh \
		io.mh \
		list.mh \
		map.mh \
		maybe.mh \
		ops.mh \
		pair.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		univ.mh \
		io.call_system.mh \
		io.stream_ops.mh \
		libs.maybe_util.mh \
		libs.process_util.mh \
		string.format.mh \
		string.parse_util.mh

# RULE int0_on_date0
libs.process_util.int0 : libs.process_util.date0
	@:

# RULE int_on_date
libs.process_util.int : libs.process_util.date
	@:

# RULE int2_on_date
libs.process_util.int2 : libs.process_util.date
	@:

# RULE int3_on_date3
libs.process_util.int3 : libs.process_util.date3
	@:

# RULE opt_on_opt_date
libs.process_util.opt : libs.process_util.optdate
	@:

# RULE trans_opt_on_trans_opt_date
libs.process_util.trans_opt : libs.process_util.trans_opt_date
	@:

# RULE date0_on_src
libs.process_util.date0 : process_util.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) libs.process_util

# RULE date_on_src
libs.process_util.date : process_util.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) libs.process_util

# RULE date3_on_src
libs.process_util.date3 : process_util.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) libs.process_util

# RULE opt_date_on_src
libs.process_util.optdate : process_util.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) libs.process_util

# RULE trans_opt_date_on_src
libs.process_util.trans_opt_date : process_util.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) libs.process_util

# RULE c_date_on_src
libs.process_util.c_date : process_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) libs.process_util $(ERR_REDIRECT)

# RULE java_date_on_src
libs.process_util.java_date : process_util.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only libs.process_util $(ERR_REDIRECT)

