# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `ll_backend.stdlabel' in source file `stdlabel.m'.
# Generated by Mercury compiler version rotd-2025-11-07
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
ll_backend.stdlabel.optdate ll_backend.stdlabel.trans_opt_date stdlabel.err ll_backend.stdlabel.c_date ll_backend.stdlabel.java_date : \
		stdlabel.m \
	\
		ll_backend.int0 \
	\
		bool.int \
		builtin.int \
		counter.int \
		list.int \
		map.int \
		mdbcomp.int \
		private_builtin.int \
		require.int \
		ll_backend.llds.int \
		ll_backend.opt_util.int \
		mdbcomp.prim_data.int \
	\
		array.int2 \
		assoc_list.int2 \
		backend_libs.int2 \
		bimap.int2 \
		char.int2 \
		cord.int2 \
		enum.int2 \
		hlds.int2 \
		libs.int2 \
		maybe.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		parse_tree.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		term.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		backend_libs.builtin_ops.int2 \
		backend_libs.rtti.int2 \
		hlds.code_model.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		libs.trace_params.int2 \
		ll_backend.layout.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_type.int2 \
		parse_tree.set_of_var.int2 \
	\
		ll_backend.stdlabel.int \
	\
		ll_backend.int

# RULE objs_on_mihs
ll_backend.stdlabel.$O ll_backend.stdlabel.pic_o : \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		cord.mih \
		counter.mih \
		enum.mih \
		hlds.mih \
		libs.mih \
		list.mih \
		ll_backend.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		backend_libs.builtin_ops.mih \
		backend_libs.rtti.mih \
		hlds.code_model.mih \
		hlds.hlds_data.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		libs.trace_params.mih \
		ll_backend.layout.mih \
		ll_backend.llds.mih \
		ll_backend.opt_util.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_type.mih \
		parse_tree.set_of_var.mih

# RULE mh_and_mih_on_c
ll_backend.stdlabel.mh ll_backend.stdlabel.mih : ll_backend.stdlabel.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
ll_backend.stdlabel.module_dep : jmercury/ll_backend__stdlabel.java

else

# RULE module_dep_on_c
ll_backend.stdlabel.module_dep : ll_backend.stdlabel.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
ll_backend.stdlabel.date ll_backend.stdlabel.date0 ll_backend.date : \
		stdlabel.m \
	\
		ll_backend.int0 \
	\
		bool.int3 \
		builtin.int3 \
		counter.int3 \
		list.int3 \
		map.int3 \
		mdbcomp.int3 \
		private_builtin.int3 \
		require.int3 \
		ll_backend.llds.int3 \
		ll_backend.opt_util.int3 \
		mdbcomp.prim_data.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bimap.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		hlds.int3 \
		libs.int3 \
		maybe.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		parse_tree.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.rtti.int3 \
		hlds.code_model.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		libs.trace_params.int3 \
		ll_backend.layout.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
ll_backend.stdlabel.date0 ll_backend.date0 : \
		stdlabel.m \
	\
		bool.int3 \
		builtin.int3 \
		counter.int3 \
		list.int3 \
		map.int3 \
		mdbcomp.int3 \
		private_builtin.int3 \
		require.int3 \
		ll_backend.llds.int3 \
		ll_backend.opt_util.int3 \
		mdbcomp.prim_data.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bimap.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		hlds.int3 \
		libs.int3 \
		maybe.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		parse_tree.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.rtti.int3 \
		hlds.code_model.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		libs.trace_params.int3 \
		ll_backend.layout.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
ll_backend.stdlabel.$O ll_backend.stdlabel.pic_o : \
		array.mh \
		assoc_list.mh \
		backend_libs.mh \
		bimap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		cord.mh \
		counter.mh \
		enum.mh \
		hlds.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		term.mh \
		term_context.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		backend_libs.builtin_ops.mh \
		backend_libs.rtti.mh \
		hlds.code_model.mh \
		hlds.hlds_data.mh \
		hlds.hlds_llds.mh \
		hlds.hlds_module.mh \
		hlds.hlds_pred.mh \
		libs.trace_params.mh \
		ll_backend.layout.mh \
		ll_backend.llds.mh \
		ll_backend.opt_util.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.program_representation.mh \
		mdbcomp.sym_name.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_foreign.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_type.mh \
		parse_tree.set_of_var.mh

# RULE int0_on_date0
ll_backend.stdlabel.int0 : ll_backend.stdlabel.date0
	@:

# RULE int_on_date
ll_backend.stdlabel.int : ll_backend.stdlabel.date
	@:

# RULE int2_on_date
ll_backend.stdlabel.int2 : ll_backend.stdlabel.date
	@:

# RULE int3_on_date3
ll_backend.stdlabel.int3 : ll_backend.stdlabel.date3
	@:

# RULE opt_on_opt_date
ll_backend.stdlabel.opt : ll_backend.stdlabel.optdate
	@:

# RULE trans_opt_on_trans_opt_date
ll_backend.stdlabel.trans_opt : ll_backend.stdlabel.trans_opt_date
	@:

# RULE date0_on_src
ll_backend.stdlabel.date0 : stdlabel.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) ll_backend.stdlabel

# RULE date_on_src
ll_backend.stdlabel.date : stdlabel.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) ll_backend.stdlabel

# RULE date3_on_src
ll_backend.stdlabel.date3 : stdlabel.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) ll_backend.stdlabel

# RULE opt_date_on_src
ll_backend.stdlabel.optdate : stdlabel.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) ll_backend.stdlabel

# RULE trans_opt_date_on_src
ll_backend.stdlabel.trans_opt_date : stdlabel.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) ll_backend.stdlabel

# RULE c_date_on_src
ll_backend.stdlabel.c_date : stdlabel.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) ll_backend.stdlabel $(ERR_REDIRECT)

# RULE java_date_on_src
ll_backend.stdlabel.java_date : stdlabel.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only ll_backend.stdlabel $(ERR_REDIRECT)

