# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `make.timestamp' in source file `make.timestamp.m'.
# Generated by Mercury compiler version rotd-2025-06-12
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
make.timestamp.optdate make.timestamp.trans_opt_date make.timestamp.err make.timestamp.c_date make.timestamp.java_date : \
		make.timestamp.m \
	\
		make.int0 \
	\
		analysis.int \
		builtin.int \
		dir.int \
		io.int \
		libs.int \
		list.int \
		map.int \
		maybe.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		string.int \
		transform_hlds.int \
		version_hash_table.int \
		analysis.framework.int \
		analysis.operations.int \
		libs.file_util.int \
		libs.globals.int \
		libs.timestamp.int \
		make.file_names.int \
		make.get_module_dep_info.int \
		make.hash.int \
		make.make_info.int \
		mdbcomp.sym_name.int \
		parse_tree.find_module.int \
		parse_tree.module_dep_info.int \
		string.format.int \
		string.parse_util.int \
		transform_hlds.mmc_analysis.int \
	\
		array.int2 \
		assoc_list.int2 \
		backend_libs.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		enum.int2 \
		getopt.int2 \
		hlds.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		version_array.int2 \
		backend_libs.compile_target_code.int2 \
		backend_libs.link_target_code.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		libs.maybe_util.int2 \
		libs.op_mode.int2 \
		libs.optimization_options.int2 \
		libs.options.int2 \
		libs.trace_params.int2 \
		make.build.int2 \
		make.deps_cache.int2 \
		make.deps_set.int2 \
		make.options_file.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.prim_data.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.file_names.int2 \
		parse_tree.module_baggage.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_parse_tree.int2 \
		parse_tree.read_modules.int2 \
		parse_tree.set_of_var.int2 \
	\
		make.timestamp.int \
	\
		make.int

# RULE objs_on_mihs
make.timestamp.pic_o make.timestamp.$O : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		dir.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		io.mih \
		libs.mih \
		list.mih \
		make.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		version_array.mih \
		version_hash_table.mih \
		analysis.framework.mih \
		analysis.operations.mih \
		backend_libs.compile_target_code.mih \
		backend_libs.link_target_code.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.maybe_util.mih \
		libs.op_mode.mih \
		libs.optimization_options.mih \
		libs.options.mih \
		libs.timestamp.mih \
		libs.trace_params.mih \
		make.build.mih \
		make.deps_cache.mih \
		make.deps_set.mih \
		make.file_names.mih \
		make.get_module_dep_info.mih \
		make.hash.mih \
		make.make_info.mih \
		make.options_file.mih \
		mdbcomp.feedback.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.file_names.mih \
		parse_tree.find_module.mih \
		parse_tree.module_baggage.mih \
		parse_tree.module_dep_info.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_parse_tree.mih \
		parse_tree.read_modules.mih \
		parse_tree.set_of_var.mih \
		string.format.mih \
		string.parse_util.mih \
		transform_hlds.mmc_analysis.mih

# RULE mh_and_mih_on_c
make.timestamp.mh make.timestamp.mih : make.timestamp.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
make.timestamp.module_dep : jmercury/make__timestamp.java

else

# RULE module_dep_on_c
make.timestamp.module_dep : make.timestamp.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
make.timestamp.date make.timestamp.date0 make.date : \
		make.timestamp.m \
	\
		make.int0 \
	\
		analysis.int3 \
		builtin.int3 \
		dir.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		transform_hlds.int3 \
		version_hash_table.int3 \
		analysis.framework.int3 \
		analysis.operations.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.timestamp.int3 \
		make.file_names.int3 \
		make.get_module_dep_info.int3 \
		make.hash.int3 \
		make.make_info.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.find_module.int3 \
		parse_tree.module_dep_info.int3 \
		string.format.int3 \
		string.parse_util.int3 \
		transform_hlds.mmc_analysis.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		hlds.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		version_array.int3 \
		backend_libs.compile_target_code.int3 \
		backend_libs.link_target_code.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		libs.maybe_util.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.trace_params.int3 \
		make.build.int3 \
		make.deps_cache.int3 \
		make.deps_set.int3 \
		make.options_file.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_names.int3 \
		parse_tree.module_baggage.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_parse_tree.int3 \
		parse_tree.read_modules.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
make.timestamp.date0 make.date0 : \
		make.timestamp.m \
	\
		analysis.int3 \
		builtin.int3 \
		dir.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		transform_hlds.int3 \
		version_hash_table.int3 \
		analysis.framework.int3 \
		analysis.operations.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.timestamp.int3 \
		make.file_names.int3 \
		make.get_module_dep_info.int3 \
		make.hash.int3 \
		make.make_info.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.find_module.int3 \
		parse_tree.module_dep_info.int3 \
		string.format.int3 \
		string.parse_util.int3 \
		transform_hlds.mmc_analysis.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		hlds.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		version_array.int3 \
		backend_libs.compile_target_code.int3 \
		backend_libs.link_target_code.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		libs.maybe_util.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.trace_params.int3 \
		make.build.int3 \
		make.deps_cache.int3 \
		make.deps_set.int3 \
		make.options_file.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_names.int3 \
		parse_tree.module_baggage.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_parse_tree.int3 \
		parse_tree.read_modules.int3 \
		parse_tree.set_of_var.int3

# RULE foreign_deps_for_mh
make.timestamp.$O make.timestamp.pic_o : \
		array.mh \
		bitmap.mh \
		dir.mh \
		io.mh \
		string.mh \
		time.mh \
		version_array.mh \
		io.stream_ops.mh \
		make.build.mh

# RULE int0_on_date0
make.timestamp.int0 : make.timestamp.date0
	@:

# RULE int_on_date
make.timestamp.int : make.timestamp.date
	@:

# RULE int2_on_date
make.timestamp.int2 : make.timestamp.date
	@:

# RULE int3_on_date3
make.timestamp.int3 : make.timestamp.date3
	@:

# RULE opt_on_opt_date
make.timestamp.opt : make.timestamp.optdate
	@:

# RULE trans_opt_on_trans_opt_date
make.timestamp.trans_opt : make.timestamp.trans_opt_date
	@:

