# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `make.get_module_dep_info' in source file `make.get_module_dep_info.m'.
# Generated by Mercury compiler version rotd-2025-11-20
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
make.get_module_dep_info.optdate make.get_module_dep_info.trans_opt_date make.get_module_dep_info.err make.get_module_dep_info.c_date make.get_module_dep_info.java_date : \
		make.get_module_dep_info.m \
	\
		make.int0 \
	\
		bool.int \
		builtin.int \
		dir.int \
		getopt.int \
		io.int \
		libs.int \
		list.int \
		map.int \
		maybe.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		set.int \
		stream.int \
		string.int \
		io.file.int \
		libs.file_util.int \
		libs.globals.int \
		libs.maybe_util.int \
		libs.options.int \
		libs.process_util.int \
		libs.timestamp.int \
		make.build.int \
		make.file_names.int \
		make.make_info.int \
		make.module_dep_file.int \
		make.module_target.int \
		make.timestamp.int \
		make.util.int \
		mdbcomp.sym_name.int \
		parse_tree.comp_unit_interface.int \
		parse_tree.file_names.int \
		parse_tree.find_module.int \
		parse_tree.item_util.int \
		parse_tree.maybe_error.int \
		parse_tree.module_baggage.int \
		parse_tree.module_dep_info.int \
		parse_tree.parse_error.int \
		parse_tree.parse_tree_out_sym_name.int \
		parse_tree.prog_data_foreign.int \
		parse_tree.prog_item.int \
		parse_tree.prog_parse_tree.int \
		parse_tree.read_modules.int \
		parse_tree.write_error_spec.int \
		parse_tree.write_module_interface_files.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		backend_libs.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		enum.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		recompilation.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		version_array.int2 \
		version_hash_table.int2 \
		backend_libs.compile_target_code.int2 \
		backend_libs.link_target_code.int2 \
		libs.indent.int2 \
		libs.op_mode.int2 \
		libs.optdb_help.int2 \
		libs.optimization_options.int2 \
		libs.option_categories.int2 \
		libs.trace_params.int2 \
		make.index_set.int2 \
		make.options_file.int2 \
		make.prereqs_cache.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.prim_data.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.file_kind.int2 \
		parse_tree.parse_tree_out_term.int2 \
		parse_tree.parse_tree_output.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.set_of_var.int2 \
		recompilation.item_types.int2 \
		string.builder.int2 \
		mdbcomp.feedback.feedback_info.int2 \
	\
		make.get_module_dep_info.int \
	\
		make.int

# RULE objs_on_mihs
make.get_module_dep_info.$O make.get_module_dep_info.pic_o : \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		dir.mih \
		enum.mih \
		getopt.mih \
		io.mih \
		libs.mih \
		list.mih \
		make.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		recompilation.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		version_array.mih \
		version_hash_table.mih \
		backend_libs.compile_target_code.mih \
		backend_libs.link_target_code.mih \
		io.file.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.indent.mih \
		libs.maybe_util.mih \
		libs.op_mode.mih \
		libs.optdb_help.mih \
		libs.optimization_options.mih \
		libs.option_categories.mih \
		libs.options.mih \
		libs.process_util.mih \
		libs.timestamp.mih \
		libs.trace_params.mih \
		make.build.mih \
		make.file_names.mih \
		make.index_set.mih \
		make.make_info.mih \
		make.module_dep_file.mih \
		make.module_target.mih \
		make.options_file.mih \
		make.prereqs_cache.mih \
		make.timestamp.mih \
		make.util.mih \
		mdbcomp.feedback.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.comp_unit_interface.mih \
		parse_tree.error_spec.mih \
		parse_tree.file_kind.mih \
		parse_tree.file_names.mih \
		parse_tree.find_module.mih \
		parse_tree.item_util.mih \
		parse_tree.maybe_error.mih \
		parse_tree.module_baggage.mih \
		parse_tree.module_dep_info.mih \
		parse_tree.parse_error.mih \
		parse_tree.parse_tree_out_sym_name.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.parse_tree_output.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_parse_tree.mih \
		parse_tree.read_modules.mih \
		parse_tree.set_of_var.mih \
		parse_tree.write_error_spec.mih \
		parse_tree.write_module_interface_files.mih \
		recompilation.item_types.mih \
		string.builder.mih \
		string.format.mih \
		string.parse_util.mih \
		mdbcomp.feedback.feedback_info.mih

# RULE mh_and_mih_on_c
make.get_module_dep_info.mh make.get_module_dep_info.mih : make.get_module_dep_info.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
make.get_module_dep_info.module_dep : jmercury/make__get_module_dep_info.java

else

# RULE module_dep_on_c
make.get_module_dep_info.module_dep : make.get_module_dep_info.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
make.get_module_dep_info.date make.get_module_dep_info.date0 make.date : \
		make.get_module_dep_info.m \
	\
		make.int0 \
	\
		bool.int3 \
		builtin.int3 \
		dir.int3 \
		getopt.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		set.int3 \
		stream.int3 \
		string.int3 \
		io.file.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.maybe_util.int3 \
		libs.options.int3 \
		libs.process_util.int3 \
		libs.timestamp.int3 \
		make.build.int3 \
		make.file_names.int3 \
		make.make_info.int3 \
		make.module_dep_file.int3 \
		make.module_target.int3 \
		make.timestamp.int3 \
		make.util.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.comp_unit_interface.int3 \
		parse_tree.file_names.int3 \
		parse_tree.find_module.int3 \
		parse_tree.item_util.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.module_baggage.int3 \
		parse_tree.module_dep_info.int3 \
		parse_tree.parse_error.int3 \
		parse_tree.parse_tree_out_sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_parse_tree.int3 \
		parse_tree.read_modules.int3 \
		parse_tree.write_error_spec.int3 \
		parse_tree.write_module_interface_files.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		recompilation.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		version_array.int3 \
		version_hash_table.int3 \
		backend_libs.compile_target_code.int3 \
		backend_libs.link_target_code.int3 \
		libs.indent.int3 \
		libs.op_mode.int3 \
		libs.optdb_help.int3 \
		libs.optimization_options.int3 \
		libs.option_categories.int3 \
		libs.trace_params.int3 \
		make.index_set.int3 \
		make.options_file.int3 \
		make.prereqs_cache.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_kind.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.set_of_var.int3 \
		recompilation.item_types.int3 \
		string.builder.int3 \
		mdbcomp.feedback.feedback_info.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
make.get_module_dep_info.date0 make.date0 : \
		make.get_module_dep_info.m \
	\
		bool.int3 \
		builtin.int3 \
		dir.int3 \
		getopt.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		set.int3 \
		stream.int3 \
		string.int3 \
		io.file.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.maybe_util.int3 \
		libs.options.int3 \
		libs.process_util.int3 \
		libs.timestamp.int3 \
		make.build.int3 \
		make.file_names.int3 \
		make.make_info.int3 \
		make.module_dep_file.int3 \
		make.module_target.int3 \
		make.timestamp.int3 \
		make.util.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.comp_unit_interface.int3 \
		parse_tree.file_names.int3 \
		parse_tree.find_module.int3 \
		parse_tree.item_util.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.module_baggage.int3 \
		parse_tree.module_dep_info.int3 \
		parse_tree.parse_error.int3 \
		parse_tree.parse_tree_out_sym_name.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_parse_tree.int3 \
		parse_tree.read_modules.int3 \
		parse_tree.write_error_spec.int3 \
		parse_tree.write_module_interface_files.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		recompilation.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		version_array.int3 \
		version_hash_table.int3 \
		backend_libs.compile_target_code.int3 \
		backend_libs.link_target_code.int3 \
		libs.indent.int3 \
		libs.op_mode.int3 \
		libs.optdb_help.int3 \
		libs.optimization_options.int3 \
		libs.option_categories.int3 \
		libs.trace_params.int3 \
		make.index_set.int3 \
		make.options_file.int3 \
		make.prereqs_cache.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_kind.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.set_of_var.int3 \
		recompilation.item_types.int3 \
		string.builder.int3 \
		mdbcomp.feedback.feedback_info.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
make.get_module_dep_info.$O make.get_module_dep_info.pic_o : \
		array.mh \
		assoc_list.mh \
		backend_libs.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		deconstruct.mh \
		dir.mh \
		enum.mh \
		getopt.mh \
		io.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		ops.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		recompilation.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		version_array.mh \
		version_hash_table.mh \
		backend_libs.compile_target_code.mh \
		backend_libs.link_target_code.mh \
		io.file.mh \
		io.stream_ops.mh \
		libs.file_util.mh \
		libs.globals.mh \
		libs.indent.mh \
		libs.maybe_util.mh \
		libs.op_mode.mh \
		libs.optdb_help.mh \
		libs.optimization_options.mh \
		libs.option_categories.mh \
		libs.options.mh \
		libs.process_util.mh \
		libs.timestamp.mh \
		libs.trace_params.mh \
		make.build.mh \
		make.file_names.mh \
		make.index_set.mh \
		make.make_info.mh \
		make.module_dep_file.mh \
		make.module_target.mh \
		make.options_file.mh \
		make.prereqs_cache.mh \
		make.timestamp.mh \
		make.util.mh \
		mdbcomp.feedback.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.comp_unit_interface.mh \
		parse_tree.error_spec.mh \
		parse_tree.file_kind.mh \
		parse_tree.file_names.mh \
		parse_tree.find_module.mh \
		parse_tree.item_util.mh \
		parse_tree.maybe_error.mh \
		parse_tree.module_baggage.mh \
		parse_tree.module_dep_info.mh \
		parse_tree.parse_error.mh \
		parse_tree.parse_tree_out_sym_name.mh \
		parse_tree.parse_tree_out_term.mh \
		parse_tree.parse_tree_output.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_parse_tree.mh \
		parse_tree.read_modules.mh \
		parse_tree.set_of_var.mh \
		parse_tree.write_error_spec.mh \
		parse_tree.write_module_interface_files.mh \
		recompilation.item_types.mh \
		string.builder.mh \
		string.format.mh \
		string.parse_util.mh \
		mdbcomp.feedback.feedback_info.mh

# RULE int0_on_date0
make.get_module_dep_info.int0 : make.get_module_dep_info.date0
	@:

# RULE int_on_date
make.get_module_dep_info.int : make.get_module_dep_info.date
	@:

# RULE int2_on_date
make.get_module_dep_info.int2 : make.get_module_dep_info.date
	@:

# RULE int3_on_date3
make.get_module_dep_info.int3 : make.get_module_dep_info.date3
	@:

# RULE opt_on_opt_date
make.get_module_dep_info.opt : make.get_module_dep_info.optdate
	@:

# RULE trans_opt_on_trans_opt_date
make.get_module_dep_info.trans_opt : make.get_module_dep_info.trans_opt_date
	@:

