# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `mercury_compile' in source file `mercury_compile.m'.
# Generated by Mercury compiler version rotd-2023-01-27
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
mercury_compile.optdate mercury_compile.trans_opt_date mercury_compile.err mercury_compile.c_date mercury_compile.java_date : \
		mercury_compile.m \
	\
		builtin.int \
		io.int \
		private_builtin.int \
		top_level.int \
		top_level.mercury_compile_main.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		libs.int2 \
		list.int2 \
		map.int2 \
		maybe.int2 \
		pair.int2 \
		pretty_printer.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		libs.globals.int2 \
		mdbcomp.sym_name.int2 \
	\
		mercury_compile.int

# RULE objs_on_mihs
mercury_compile.pic_o mercury_compile.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		top_level.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		libs.globals.mih \
		mdbcomp.sym_name.mih \
		top_level.mercury_compile_main.mih

# RULE mh_and_mih_on_c
mercury_compile.mh mercury_compile.mih : mercury_compile.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
mercury_compile.module_dep : jmercury/mercury_compile.java

else

# RULE module_dep_on_c
mercury_compile.module_dep : mercury_compile.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mercury_compile.date mercury_compile.date0 : \
		mercury_compile.m \
	\
		builtin.int3 \
		io.int3 \
		private_builtin.int3 \
		top_level.int3 \
		top_level.mercury_compile_main.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		libs.globals.int3 \
		mdbcomp.sym_name.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mercury_compile.date0 : \
		mercury_compile.m \
	\
		builtin.int3 \
		io.int3 \
		private_builtin.int3 \
		top_level.int3 \
		top_level.mercury_compile_main.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		libs.globals.int3 \
		mdbcomp.sym_name.int3

# RULE foreign_deps_for_mh
mercury_compile.$O mercury_compile.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
mercury_compile.int0 : mercury_compile.date0
	@:

# RULE int_on_date
mercury_compile.int : mercury_compile.date
	@:

# RULE int2_on_date
mercury_compile.int2 : mercury_compile.date
	@:

# RULE int3_on_date3
mercury_compile.int3 : mercury_compile.date3
	@:

# RULE opt_on_opt_date
mercury_compile.opt : mercury_compile.optdate
	@:

# RULE trans_opt_on_trans_opt_date
mercury_compile.trans_opt : mercury_compile.trans_opt_date
	@:

