# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `ml_backend.ml_simplify_switch' in source file `ml_simplify_switch.m'.
# Generated by Mercury compiler version rotd-2024-12-08
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
ml_backend.ml_simplify_switch.optdate ml_backend.ml_simplify_switch.trans_opt_date ml_simplify_switch.err ml_backend.ml_simplify_switch.c_date ml_backend.ml_simplify_switch.java_date : \
		ml_simplify_switch.m \
	\
		ml_backend.int0 \
	\
		backend_libs.int \
		bool.int \
		builtin.int \
		int.int \
		libs.int \
		list.int \
		map.int \
		maybe.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		backend_libs.builtin_ops.int \
		backend_libs.lookup_switch_util.int \
		libs.globals.int \
		libs.optimization_options.int \
		libs.options.int \
		ml_backend.ml_code_util.int \
		ml_backend.ml_gen_info.int \
		ml_backend.ml_target_util.int \
		ml_backend.ml_util.int \
		ml_backend.mlds.int \
		parse_tree.prog_data.int \
		parse_tree.prog_type.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		counter.int2 \
		deconstruct.int2 \
		enum.int2 \
		getopt.int2 \
		hlds.int2 \
		io.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		backend_libs.rtti.int2 \
		hlds.code_model.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_goal.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_pred.int2 \
		hlds.hlds_rtti.int2 \
		hlds.instmap.int2 \
		hlds.mark_tail_calls.int2 \
		libs.file_util.int2 \
		libs.op_mode.int2 \
		libs.trace_params.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		ml_backend.ml_global_data.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.prog_util.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_table.int2 \
	\
		ml_backend.ml_simplify_switch.int \
	\
		ml_backend.int

# RULE objs_on_mihs
ml_backend.ml_simplify_switch.pic_o ml_backend.ml_simplify_switch.$O : \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		counter.mih \
		deconstruct.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		int.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		ml_backend.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		backend_libs.builtin_ops.mih \
		backend_libs.lookup_switch_util.mih \
		backend_libs.rtti.mih \
		hlds.code_model.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_rtti.mih \
		hlds.instmap.mih \
		hlds.mark_tail_calls.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.op_mode.mih \
		libs.optimization_options.mih \
		libs.options.mih \
		libs.trace_params.mih \
		mdbcomp.feedback.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		ml_backend.ml_code_util.mih \
		ml_backend.ml_gen_info.mih \
		ml_backend.ml_global_data.mih \
		ml_backend.ml_target_util.mih \
		ml_backend.ml_util.mih \
		ml_backend.mlds.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_util.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_table.mih

# RULE mh_and_mih_on_c
ml_backend.ml_simplify_switch.mh ml_backend.ml_simplify_switch.mih : ml_backend.ml_simplify_switch.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
ml_backend.ml_simplify_switch.module_dep : jmercury/ml_backend__ml_simplify_switch.java

else

# RULE module_dep_on_c
ml_backend.ml_simplify_switch.module_dep : ml_backend.ml_simplify_switch.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
ml_backend.ml_simplify_switch.date ml_backend.ml_simplify_switch.date0 ml_backend.date : \
		ml_simplify_switch.m \
	\
		ml_backend.int0 \
	\
		backend_libs.int3 \
		bool.int3 \
		builtin.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.lookup_switch_util.int3 \
		libs.globals.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		ml_backend.ml_code_util.int3 \
		ml_backend.ml_gen_info.int3 \
		ml_backend.ml_target_util.int3 \
		ml_backend.ml_util.int3 \
		ml_backend.mlds.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		counter.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		hlds.int3 \
		io.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.rtti.int3 \
		hlds.code_model.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_rtti.int3 \
		hlds.instmap.int3 \
		hlds.mark_tail_calls.int3 \
		libs.file_util.int3 \
		libs.op_mode.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		ml_backend.ml_global_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
ml_backend.ml_simplify_switch.date0 ml_backend.date0 : \
		ml_simplify_switch.m \
	\
		backend_libs.int3 \
		bool.int3 \
		builtin.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.lookup_switch_util.int3 \
		libs.globals.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		ml_backend.ml_code_util.int3 \
		ml_backend.ml_gen_info.int3 \
		ml_backend.ml_target_util.int3 \
		ml_backend.ml_util.int3 \
		ml_backend.mlds.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		counter.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		hlds.int3 \
		io.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.rtti.int3 \
		hlds.code_model.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_rtti.int3 \
		hlds.instmap.int3 \
		hlds.mark_tail_calls.int3 \
		libs.file_util.int3 \
		libs.op_mode.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		ml_backend.ml_global_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3

# RULE foreign_deps_for_mh
ml_backend.ml_simplify_switch.$O ml_backend.ml_simplify_switch.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
ml_backend.ml_simplify_switch.int0 : ml_backend.ml_simplify_switch.date0
	@:

# RULE int_on_date
ml_backend.ml_simplify_switch.int : ml_backend.ml_simplify_switch.date
	@:

# RULE int2_on_date
ml_backend.ml_simplify_switch.int2 : ml_backend.ml_simplify_switch.date
	@:

# RULE int3_on_date3
ml_backend.ml_simplify_switch.int3 : ml_backend.ml_simplify_switch.date3
	@:

# RULE opt_on_opt_date
ml_backend.ml_simplify_switch.opt : ml_backend.ml_simplify_switch.optdate
	@:

# RULE trans_opt_on_trans_opt_date
ml_backend.ml_simplify_switch.trans_opt : ml_backend.ml_simplify_switch.trans_opt_date
	@:

# RULE date0_on_src
ml_backend.ml_simplify_switch.date0 : ml_simplify_switch.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) ml_backend.ml_simplify_switch

# RULE date_on_src
ml_backend.ml_simplify_switch.date : ml_simplify_switch.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) ml_backend.ml_simplify_switch

# RULE date3_on_src
ml_backend.ml_simplify_switch.date3 : ml_simplify_switch.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) ml_backend.ml_simplify_switch

# RULE opt_date_on_src
ml_backend.ml_simplify_switch.optdate : ml_simplify_switch.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) ml_backend.ml_simplify_switch

# RULE trans_opt_date_on_src
ml_backend.ml_simplify_switch.trans_opt_date : ml_simplify_switch.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) ml_backend.ml_simplify_switch

# RULE c_date_on_src
ml_backend.ml_simplify_switch.c_date : ml_simplify_switch.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) ml_backend.ml_simplify_switch $(ERR_REDIRECT)

# RULE java_date_on_src
ml_backend.ml_simplify_switch.java_date : ml_simplify_switch.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only ml_backend.ml_simplify_switch $(ERR_REDIRECT)

