# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `ml_backend.ml_elim_nested' in source file `ml_elim_nested.m'.
# Generated by Mercury compiler version rotd-2023-07-17
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
ml_backend.ml_elim_nested.optdate ml_backend.ml_elim_nested.trans_opt_date ml_elim_nested.err ml_backend.ml_elim_nested.c_date ml_backend.ml_elim_nested.java_date : \
		ml_elim_nested.m \
	\
		ml_backend.int0 \
	\
		bool.int \
		builtin.int \
		cord.int \
		counter.int \
		hlds.int \
		list.int \
		maybe.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		set.int \
		stream.int \
		string.int \
		hlds.hlds_data.int \
		hlds.hlds_pred.int \
		mdbcomp.builtin_modules.int \
		mdbcomp.prim_data.int \
		mdbcomp.sym_name.int \
		ml_backend.ml_code_util.int \
		ml_backend.ml_global_data.int \
		ml_backend.ml_util.int \
		ml_backend.mlds.int \
		parse_tree.prog_data.int \
		string.format.int \
		string.parse_util.int \
	\
		analysis.int2 \
		array.int2 \
		assoc_list.int2 \
		backend_libs.int2 \
		bimap.int2 \
		char.int2 \
		check_hlds.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		libs.int2 \
		map.int2 \
		mode_robdd.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		robdd.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stack.int2 \
		term.int2 \
		term_context.int2 \
		transform_hlds.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		backend_libs.builtin_ops.int2 \
		backend_libs.rtti.int2 \
		check_hlds.mode_constraint_robdd.int2 \
		check_hlds.mode_errors.int2 \
		hlds.code_model.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_clauses.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_goal.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_module.int2 \
		hlds.hlds_promise.int2 \
		hlds.hlds_rtti.int2 \
		hlds.inst_graph.int2 \
		hlds.instmap.int2 \
		hlds.pred_name.int2 \
		hlds.pred_table.int2 \
		hlds.status.int2 \
		libs.globals.int2 \
		libs.polyhedron.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
		ml_backend.ml_gen_info.int2 \
		mode_robdd.tfeirn.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.prog_type.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_table.int2 \
		parse_tree.vartypes.int2 \
		transform_hlds.term_constr_errors.int2 \
		transform_hlds.term_constr_main_types.int2 \
		transform_hlds.term_errors.int2 \
		transform_hlds.term_util.int2 \
	\
		ml_backend.ml_elim_nested.int \
	\
		ml_backend.int

# RULE objs_on_mihs
ml_backend.ml_elim_nested.pic_o ml_backend.ml_elim_nested.$O : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		counter.mih \
		deconstruct.mih \
		enum.mih \
		hlds.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		ml_backend.mih \
		mode_robdd.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		robdd.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stack.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		backend_libs.builtin_ops.mih \
		backend_libs.rtti.mih \
		check_hlds.mode_constraint_robdd.mih \
		check_hlds.mode_errors.mih \
		hlds.code_model.mih \
		hlds.goal_mode.mih \
		hlds.hlds_class.mih \
		hlds.hlds_clauses.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.hlds_rtti.mih \
		hlds.inst_graph.mih \
		hlds.instmap.mih \
		hlds.pred_name.mih \
		hlds.pred_table.mih \
		hlds.status.mih \
		libs.globals.mih \
		libs.polyhedron.mih \
		mdbcomp.builtin_modules.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		ml_backend.ml_code_util.mih \
		ml_backend.ml_gen_info.mih \
		ml_backend.ml_global_data.mih \
		ml_backend.ml_util.mih \
		ml_backend.mlds.mih \
		mode_robdd.tfeirn.mih \
		parse_tree.error_spec.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.prog_type.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_table.mih \
		parse_tree.vartypes.mih \
		string.format.mih \
		string.parse_util.mih \
		transform_hlds.term_constr_errors.mih \
		transform_hlds.term_constr_main_types.mih \
		transform_hlds.term_errors.mih \
		transform_hlds.term_util.mih

# RULE mh_and_mih_on_c
ml_backend.ml_elim_nested.mh ml_backend.ml_elim_nested.mih : ml_backend.ml_elim_nested.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
ml_backend.ml_elim_nested.module_dep : jmercury/ml_backend__ml_elim_nested.java

else

# RULE module_dep_on_c
ml_backend.ml_elim_nested.module_dep : ml_backend.ml_elim_nested.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
ml_backend.ml_elim_nested.date ml_backend.ml_elim_nested.date0 ml_backend.date : \
		ml_elim_nested.m \
	\
		ml_backend.int0 \
	\
		bool.int3 \
		builtin.int3 \
		cord.int3 \
		counter.int3 \
		hlds.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		stream.int3 \
		string.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_pred.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		ml_backend.ml_code_util.int3 \
		ml_backend.ml_global_data.int3 \
		ml_backend.ml_util.int3 \
		ml_backend.mlds.int3 \
		parse_tree.prog_data.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bimap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		libs.int3 \
		map.int3 \
		mode_robdd.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		robdd.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		term.int3 \
		term_context.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.rtti.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.mode_errors.int3 \
		hlds.code_model.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		hlds.pred_table.int3 \
		hlds.status.int3 \
		libs.globals.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		ml_backend.ml_gen_info.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
ml_backend.ml_elim_nested.date0 ml_backend.date0 : \
		ml_elim_nested.m \
	\
		bool.int3 \
		builtin.int3 \
		cord.int3 \
		counter.int3 \
		hlds.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		stream.int3 \
		string.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_pred.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		ml_backend.ml_code_util.int3 \
		ml_backend.ml_global_data.int3 \
		ml_backend.ml_util.int3 \
		ml_backend.mlds.int3 \
		parse_tree.prog_data.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		backend_libs.int3 \
		bimap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		libs.int3 \
		map.int3 \
		mode_robdd.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		robdd.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		term.int3 \
		term_context.int3 \
		transform_hlds.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.rtti.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.mode_errors.int3 \
		hlds.code_model.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.instmap.int3 \
		hlds.pred_name.int3 \
		hlds.pred_table.int3 \
		hlds.status.int3 \
		libs.globals.int3 \
		libs.polyhedron.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		ml_backend.ml_gen_info.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE foreign_deps_for_mh
ml_backend.ml_elim_nested.$O ml_backend.ml_elim_nested.pic_o : array.mh

# RULE int0_on_date0
ml_backend.ml_elim_nested.int0 : ml_backend.ml_elim_nested.date0
	@:

# RULE int_on_date
ml_backend.ml_elim_nested.int : ml_backend.ml_elim_nested.date
	@:

# RULE int2_on_date
ml_backend.ml_elim_nested.int2 : ml_backend.ml_elim_nested.date
	@:

# RULE int3_on_date3
ml_backend.ml_elim_nested.int3 : ml_backend.ml_elim_nested.date3
	@:

# RULE opt_on_opt_date
ml_backend.ml_elim_nested.opt : ml_backend.ml_elim_nested.optdate
	@:

# RULE trans_opt_on_trans_opt_date
ml_backend.ml_elim_nested.trans_opt : ml_backend.ml_elim_nested.trans_opt_date
	@:

# RULE date0_on_src
ml_backend.ml_elim_nested.date0 : ml_elim_nested.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) ml_backend.ml_elim_nested

# RULE date_on_src
ml_backend.ml_elim_nested.date : ml_elim_nested.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) ml_backend.ml_elim_nested

# RULE date3_on_src
ml_backend.ml_elim_nested.date3 : ml_elim_nested.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) ml_backend.ml_elim_nested

# RULE opt_date_on_src
ml_backend.ml_elim_nested.optdate : ml_elim_nested.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) ml_backend.ml_elim_nested

# RULE trans_opt_date_on_src
ml_backend.ml_elim_nested.trans_opt_date : ml_elim_nested.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) ml_backend.ml_elim_nested

# RULE c_date_on_src
ml_backend.ml_elim_nested.c_date : ml_elim_nested.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) ml_backend.ml_elim_nested $(ERR_REDIRECT)

# RULE java_date_on_src
ml_backend.ml_elim_nested.java_date : ml_elim_nested.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only ml_backend.ml_elim_nested $(ERR_REDIRECT)

