# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `mode_robdd.implications' in source file `mode_robdd.implications.m'.
# Generated by Mercury compiler version 2019-11-29
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
mode_robdd.implications.optdate mode_robdd.implications.trans_opt_date mode_robdd.implications.err mode_robdd.implications.c_date mode_robdd.implications.java_date : \
		mode_robdd.implications.m \
	\
		mode_robdd.int0 \
	\
		assoc_list.int \
		bool.int \
		builtin.int \
		io.int \
		list.int \
		map.int \
		pair.int \
		private_builtin.int \
		robdd.int \
		sparse_bitset.int \
		term.int \
		mode_robdd.equiv_vars.int \
		mode_robdd.tfeirn.int \
	\
		array.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		check_hlds.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		integer.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		multi_map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stack.int2 \
		stream.int2 \
		string.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		check_hlds.mode_constraint_robdd.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.set_of_var.int2

# RULE objs_on_mihs
mode_robdd.implications.pic_o mode_robdd.implications.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		integer.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		mode_robdd.mih \
		multi_map.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		robdd.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stack.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		check_hlds.mode_constraint_robdd.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		mode_robdd.equiv_vars.mih \
		mode_robdd.tfeirn.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih \
		parse_tree.set_of_var.mih

# RULE mh_and_mih_on_c
mode_robdd.implications.mh mode_robdd.implications.mih : mode_robdd.implications.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
mode_robdd.implications.module_dep : jmercury/mode_robdd__implications.java

else

# RULE module_dep_on_c
mode_robdd.implications.module_dep : mode_robdd.implications.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
mode_robdd.implications.date mode_robdd.implications.date0 mode_robdd.date : \
		mode_robdd.implications.m \
	\
		mode_robdd.int0 \
	\
		assoc_list.int3 \
		bool.int3 \
		builtin.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		pair.int3 \
		private_builtin.int3 \
		robdd.int3 \
		sparse_bitset.int3 \
		term.int3 \
		mode_robdd.equiv_vars.int3 \
		mode_robdd.tfeirn.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stack.int3 \
		stream.int3 \
		string.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mode_robdd.implications.date0 mode_robdd.date0 : \
		mode_robdd.implications.m \
	\
		assoc_list.int3 \
		bool.int3 \
		builtin.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		pair.int3 \
		private_builtin.int3 \
		robdd.int3 \
		sparse_bitset.int3 \
		term.int3 \
		mode_robdd.equiv_vars.int3 \
		mode_robdd.tfeirn.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		integer.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stack.int3 \
		stream.int3 \
		string.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.set_of_var.int3

# RULE foreign_deps_for_.mh
mode_robdd.implications.$O : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE foreign_deps_for_.mh
mode_robdd.implications.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

mode_robdd.implications.int0 : mode_robdd.implications.date0
	@:

mode_robdd.implications.int : mode_robdd.implications.date
	@:

mode_robdd.implications.int2 : mode_robdd.implications.date
	@:

mode_robdd.implications.int3 : mode_robdd.implications.date3
	@:

mode_robdd.implications.opt : mode_robdd.implications.optdate
	@:

mode_robdd.implications.trans_opt : mode_robdd.implications.trans_opt_date
	@:

