# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.set_of_var' in source file `set_of_var.m'.
# Generated by Mercury compiler version rotd-2025-06-29
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
parse_tree.set_of_var.optdate parse_tree.set_of_var.trans_opt_date set_of_var.err parse_tree.set_of_var.c_date parse_tree.set_of_var.java_date : \
		set_of_var.m \
	\
		parse_tree.int0 \
	\
		bool.int \
		builtin.int \
		list.int \
		private_builtin.int \
		require.int \
		set.int \
		sparse_bitset.int \
		term.int \
		parse_tree.prog_data.int \
	\
		assoc_list.int2 \
		char.int2 \
		cord.int2 \
		enum.int2 \
		integer.int2 \
		map.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set_ordlist.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_item.int2 \
	\
		parse_tree.set_of_var.int \
	\
		parse_tree.int

# RULE objs_on_mihs
parse_tree.set_of_var.pic_o parse_tree.set_of_var.$O : \
		assoc_list.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		cord.mih \
		enum.mih \
		integer.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih

# RULE mh_and_mih_on_c
parse_tree.set_of_var.mh parse_tree.set_of_var.mih : parse_tree.set_of_var.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.set_of_var.module_dep : jmercury/parse_tree__set_of_var.java

else

# RULE module_dep_on_c
parse_tree.set_of_var.module_dep : parse_tree.set_of_var.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
parse_tree.set_of_var.date parse_tree.set_of_var.date0 parse_tree.date : \
		set_of_var.m \
	\
		parse_tree.int0 \
	\
		bool.int3 \
		builtin.int3 \
		list.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		sparse_bitset.int3 \
		term.int3 \
		parse_tree.prog_data.int3 \
	\
		assoc_list.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_item.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
parse_tree.set_of_var.date0 parse_tree.date0 : \
		set_of_var.m \
	\
		bool.int3 \
		builtin.int3 \
		list.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		sparse_bitset.int3 \
		term.int3 \
		parse_tree.prog_data.int3 \
	\
		assoc_list.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_item.int3

# RULE int0_on_date0
parse_tree.set_of_var.int0 : parse_tree.set_of_var.date0
	@:

# RULE int_on_date
parse_tree.set_of_var.int : parse_tree.set_of_var.date
	@:

# RULE int2_on_date
parse_tree.set_of_var.int2 : parse_tree.set_of_var.date
	@:

# RULE int3_on_date3
parse_tree.set_of_var.int3 : parse_tree.set_of_var.date3
	@:

# RULE opt_on_opt_date
parse_tree.set_of_var.opt : parse_tree.set_of_var.optdate
	@:

# RULE trans_opt_on_trans_opt_date
parse_tree.set_of_var.trans_opt : parse_tree.set_of_var.trans_opt_date
	@:

# RULE date0_on_src
parse_tree.set_of_var.date0 : set_of_var.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.set_of_var

# RULE date_on_src
parse_tree.set_of_var.date : set_of_var.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.set_of_var

# RULE date3_on_src
parse_tree.set_of_var.date3 : set_of_var.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.set_of_var

# RULE opt_date_on_src
parse_tree.set_of_var.optdate : set_of_var.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.set_of_var

# RULE trans_opt_date_on_src
parse_tree.set_of_var.trans_opt_date : set_of_var.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.set_of_var

# RULE c_date_on_src
parse_tree.set_of_var.c_date : set_of_var.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.set_of_var $(ERR_REDIRECT)

# RULE java_date_on_src
parse_tree.set_of_var.java_date : set_of_var.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.set_of_var $(ERR_REDIRECT)

