# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.builtin_lib_types' in source file `builtin_lib_types.m'.
# Generated by Mercury compiler version 20.01.1-beta-2020-02-11
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
parse_tree.builtin_lib_types.optdate parse_tree.builtin_lib_types.trans_opt_date builtin_lib_types.err parse_tree.builtin_lib_types.c_date parse_tree.builtin_lib_types.java_date : \
		builtin_lib_types.m \
	\
		parse_tree.int0 \
	\
		builtin.int \
		list.int \
		mdbcomp.int \
		private_builtin.int \
		mdbcomp.builtin_modules.int \
		mdbcomp.sym_name.int \
		parse_tree.prog_data.int \
	\
		assoc_list.int2 \
		char.int2 \
		enum.int2 \
		map.int2 \
		maybe.int2 \
		multi_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		term.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		mdbcomp.prim_data.int2 \
		parse_tree.prog_item.int2

# RULE objs_on_mihs
parse_tree.builtin_lib_types.pic_o parse_tree.builtin_lib_types.$O : \
		assoc_list.mih \
		builtin.mih \
		char.mih \
		enum.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		multi_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		term.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		mdbcomp.builtin_modules.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih

# RULE mh_and_mih_on_c
parse_tree.builtin_lib_types.mh parse_tree.builtin_lib_types.mih : parse_tree.builtin_lib_types.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.builtin_lib_types.module_dep : jmercury/parse_tree__builtin_lib_types.java

else

# RULE module_dep_on_c
parse_tree.builtin_lib_types.module_dep : parse_tree.builtin_lib_types.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
parse_tree.builtin_lib_types.date parse_tree.builtin_lib_types.date0 parse_tree.date : \
		builtin_lib_types.m \
	\
		parse_tree.int0 \
	\
		builtin.int3 \
		list.int3 \
		mdbcomp.int3 \
		private_builtin.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
	\
		assoc_list.int3 \
		char.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		multi_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_item.int3

# RULE self_and_parent_date0_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
parse_tree.builtin_lib_types.date0 parse_tree.date0 : \
		builtin_lib_types.m \
	\
		builtin.int3 \
		list.int3 \
		mdbcomp.int3 \
		private_builtin.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
	\
		assoc_list.int3 \
		char.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		multi_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_item.int3

parse_tree.builtin_lib_types.int0 : parse_tree.builtin_lib_types.date0
	@:

parse_tree.builtin_lib_types.int : parse_tree.builtin_lib_types.date
	@:

parse_tree.builtin_lib_types.int2 : parse_tree.builtin_lib_types.date
	@:

parse_tree.builtin_lib_types.int3 : parse_tree.builtin_lib_types.date3
	@:

parse_tree.builtin_lib_types.opt : parse_tree.builtin_lib_types.optdate
	@:

parse_tree.builtin_lib_types.trans_opt : parse_tree.builtin_lib_types.trans_opt_date
	@:

parse_tree.builtin_lib_types.date0 : builtin_lib_types.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.builtin_lib_types

parse_tree.builtin_lib_types.date : builtin_lib_types.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.builtin_lib_types

parse_tree.builtin_lib_types.date3 : builtin_lib_types.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.builtin_lib_types

parse_tree.builtin_lib_types.optdate : builtin_lib_types.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.builtin_lib_types

parse_tree.builtin_lib_types.trans_opt_date : builtin_lib_types.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.builtin_lib_types

parse_tree.builtin_lib_types.c_date : builtin_lib_types.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.builtin_lib_types $(ERR_REDIRECT)

parse_tree.builtin_lib_types.java_date : builtin_lib_types.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.builtin_lib_types $(ERR_REDIRECT)

