# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.prog_data_pragma' in source file `prog_data_pragma.m'.
# Generated by Mercury compiler version rotd-2025-07-01
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
parse_tree.prog_data_pragma.optdate parse_tree.prog_data_pragma.trans_opt_date prog_data_pragma.err parse_tree.prog_data_pragma.c_date parse_tree.prog_data_pragma.java_date : \
		prog_data_pragma.m \
	\
		parse_tree.int0 \
	\
		bool.int \
		builtin.int \
		libs.int \
		list.int \
		maybe.int \
		one_or_more.int \
		pair.int \
		private_builtin.int \
		require.int \
		set.int \
		unit.int \
		libs.compiler_util.int \
		libs.rat.int \
		parse_tree.prog_data.int \
		parse_tree.set_of_var.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		char.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		enum.int2 \
		getopt.int2 \
		io.int2 \
		map.int2 \
		mdbcomp.int2 \
		pretty_printer.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		libs.file_util.int2 \
		libs.globals.int2 \
		libs.options.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.prog_item.int2 \
	\
		parse_tree.prog_data_pragma.int \
	\
		parse_tree.int

# RULE objs_on_mihs
parse_tree.prog_data_pragma.pic_o parse_tree.prog_data_pragma.$O : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		enum.mih \
		getopt.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		libs.compiler_util.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.options.mih \
		libs.rat.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih \
		parse_tree.set_of_var.mih

# RULE mh_and_mih_on_c
parse_tree.prog_data_pragma.mh parse_tree.prog_data_pragma.mih : parse_tree.prog_data_pragma.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.prog_data_pragma.module_dep : jmercury/parse_tree__prog_data_pragma.java

else

# RULE module_dep_on_c
parse_tree.prog_data_pragma.module_dep : parse_tree.prog_data_pragma.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
parse_tree.prog_data_pragma.date parse_tree.prog_data_pragma.date0 parse_tree.date : \
		prog_data_pragma.m \
	\
		parse_tree.int0 \
	\
		bool.int3 \
		builtin.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		one_or_more.int3 \
		pair.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		unit.int3 \
		libs.compiler_util.int3 \
		libs.rat.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		map.int3 \
		mdbcomp.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_item.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
parse_tree.prog_data_pragma.date0 parse_tree.date0 : \
		prog_data_pragma.m \
	\
		bool.int3 \
		builtin.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		one_or_more.int3 \
		pair.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		unit.int3 \
		libs.compiler_util.int3 \
		libs.rat.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		char.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		map.int3 \
		mdbcomp.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.prog_item.int3

# RULE foreign_deps_for_mh
parse_tree.prog_data_pragma.$O parse_tree.prog_data_pragma.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
parse_tree.prog_data_pragma.int0 : parse_tree.prog_data_pragma.date0
	@:

# RULE int_on_date
parse_tree.prog_data_pragma.int : parse_tree.prog_data_pragma.date
	@:

# RULE int2_on_date
parse_tree.prog_data_pragma.int2 : parse_tree.prog_data_pragma.date
	@:

# RULE int3_on_date3
parse_tree.prog_data_pragma.int3 : parse_tree.prog_data_pragma.date3
	@:

# RULE opt_on_opt_date
parse_tree.prog_data_pragma.opt : parse_tree.prog_data_pragma.optdate
	@:

# RULE trans_opt_on_trans_opt_date
parse_tree.prog_data_pragma.trans_opt : parse_tree.prog_data_pragma.trans_opt_date
	@:

# RULE date0_on_src
parse_tree.prog_data_pragma.date0 : prog_data_pragma.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.prog_data_pragma

# RULE date_on_src
parse_tree.prog_data_pragma.date : prog_data_pragma.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.prog_data_pragma

# RULE date3_on_src
parse_tree.prog_data_pragma.date3 : prog_data_pragma.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.prog_data_pragma

# RULE opt_date_on_src
parse_tree.prog_data_pragma.optdate : prog_data_pragma.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.prog_data_pragma

# RULE trans_opt_date_on_src
parse_tree.prog_data_pragma.trans_opt_date : prog_data_pragma.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.prog_data_pragma

# RULE c_date_on_src
parse_tree.prog_data_pragma.c_date : prog_data_pragma.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.prog_data_pragma $(ERR_REDIRECT)

# RULE java_date_on_src
parse_tree.prog_data_pragma.java_date : prog_data_pragma.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.prog_data_pragma $(ERR_REDIRECT)

