# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.maybe_error' in source file `maybe_error.m'.
# Generated by Mercury compiler version rotd-2022-06-25
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
parse_tree.maybe_error.optdate parse_tree.maybe_error.trans_opt_date maybe_error.err parse_tree.maybe_error.c_date parse_tree.maybe_error.java_date : \
		maybe_error.m \
	\
		parse_tree.int0 \
	\
		builtin.int \
		list.int \
		private_builtin.int \
		require.int \
		parse_tree.error_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		io.int2 \
		libs.int2 \
		map.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		libs.globals.int2 \
		libs.options.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_item.int2 \
	\
		parse_tree.maybe_error.int \
	\
		parse_tree.int

# RULE objs_on_mihs
parse_tree.maybe_error.pic_o parse_tree.maybe_error.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		libs.globals.mih \
		libs.options.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_util.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih

# RULE mh_and_mih_on_c
parse_tree.maybe_error.mh parse_tree.maybe_error.mih : parse_tree.maybe_error.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.maybe_error.module_dep : jmercury/parse_tree__maybe_error.java

else

# RULE module_dep_on_c
parse_tree.maybe_error.module_dep : parse_tree.maybe_error.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
parse_tree.maybe_error.date parse_tree.maybe_error.date0 parse_tree.date : \
		maybe_error.m \
	\
		parse_tree.int0 \
	\
		builtin.int3 \
		list.int3 \
		private_builtin.int3 \
		require.int3 \
		parse_tree.error_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		libs.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
parse_tree.maybe_error.date0 parse_tree.date0 : \
		maybe_error.m \
	\
		builtin.int3 \
		list.int3 \
		private_builtin.int3 \
		require.int3 \
		parse_tree.error_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		libs.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3

# RULE foreign_deps_for_mh
parse_tree.maybe_error.$O parse_tree.maybe_error.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
parse_tree.maybe_error.int0 : parse_tree.maybe_error.date0
	@:

# RULE int_on_date
parse_tree.maybe_error.int : parse_tree.maybe_error.date
	@:

# RULE int2_on_date
parse_tree.maybe_error.int2 : parse_tree.maybe_error.date
	@:

# RULE int3_on_date3
parse_tree.maybe_error.int3 : parse_tree.maybe_error.date3
	@:

# RULE opt_on_opt_date
parse_tree.maybe_error.opt : parse_tree.maybe_error.optdate
	@:

# RULE trans_opt_on_trans_opt_date
parse_tree.maybe_error.trans_opt : parse_tree.maybe_error.trans_opt_date
	@:

# RULE date0_on_src
parse_tree.maybe_error.date0 : maybe_error.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.maybe_error

# RULE date_on_src
parse_tree.maybe_error.date : maybe_error.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.maybe_error

# RULE date3_on_src
parse_tree.maybe_error.date3 : maybe_error.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.maybe_error

# RULE opt_date_on_src
parse_tree.maybe_error.optdate : maybe_error.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.maybe_error

# RULE trans_opt_date_on_src
parse_tree.maybe_error.trans_opt_date : maybe_error.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.maybe_error

# RULE c_date_on_src
parse_tree.maybe_error.c_date : maybe_error.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.maybe_error $(ERR_REDIRECT)

# RULE java_date_on_src
parse_tree.maybe_error.java_date : maybe_error.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.maybe_error $(ERR_REDIRECT)

