# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.parse_goal' in source file `parse_goal.m'.
# Generated by Mercury compiler version rotd-2026-07-13
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
parse_tree.parse_goal.optdate parse_tree.parse_goal.trans_opt_date parse_goal.err parse_tree.parse_goal.c_date parse_tree.parse_goal.java_date : \
		parse_goal.m \
	\
		parse_tree.int0 \
	\
		assoc_list.int \
		bag.int \
		builtin.int \
		char.int \
		cord.int \
		int.int \
		libs.int \
		list.int \
		maybe.int \
		mdbcomp.int \
		one_or_more.int \
		pair.int \
		private_builtin.int \
		require.int \
		solutions.int \
		string.int \
		term.int \
		term_context.int \
		unit.int \
		varset.int \
		libs.options.int \
		mdbcomp.sym_name.int \
		parse_tree.error_spec.int \
		parse_tree.maybe_error.int \
		parse_tree.parse_goal_util.int \
		parse_tree.parse_sym_name.int \
		parse_tree.parse_tree_out_misc.int \
		parse_tree.parse_tree_out_term.int \
		parse_tree.parse_vars.int \
		parse_tree.prog_data.int \
		parse_tree.prog_item.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		bitmap.int2 \
		bool.int2 \
		construct.int2 \
		deconstruct.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		integer.int2 \
		io.int2 \
		map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		recompilation.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		libs.file_util.int2 \
		libs.globals.int2 \
		libs.indent.int2 \
		libs.optdb_help.int2 \
		libs.optimization_options.int2 \
		libs.option_categories.int2 \
		libs.timestamp.int2 \
		mdbcomp.prim_data.int2 \
		parse_tree.file_names.int2 \
		parse_tree.find_module.int2 \
		parse_tree.parse_tree_output.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_db.int2 \
		parse_tree.var_table.int2 \
		recompilation.item_types.int2 \
		string.builder.int2 \
	\
		parse_tree.parse_goal.int \
	\
		parse_tree.int

# RULE objs_on_mihs
parse_tree.parse_goal.$O parse_tree.parse_goal.pic_o : \
		array.mih \
		assoc_list.mih \
		bag.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		int.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		recompilation.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		solutions.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.indent.mih \
		libs.optdb_help.mih \
		libs.optimization_options.mih \
		libs.option_categories.mih \
		libs.options.mih \
		libs.timestamp.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.file_names.mih \
		parse_tree.find_module.mih \
		parse_tree.maybe_error.mih \
		parse_tree.parse_goal_util.mih \
		parse_tree.parse_sym_name.mih \
		parse_tree.parse_tree_out_misc.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.parse_tree_output.mih \
		parse_tree.parse_vars.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih \
		recompilation.item_types.mih \
		string.builder.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
parse_tree.parse_goal.mh parse_tree.parse_goal.mih : parse_tree.parse_goal.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.parse_goal.module_dep : jmercury/parse_tree__parse_goal.java

else

# RULE module_dep_on_c
parse_tree.parse_goal.module_dep : parse_tree.parse_goal.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
parse_tree.parse_goal.date parse_tree.parse_goal.date0 parse_tree.date : \
		parse_goal.m \
	\
		parse_tree.int0 \
	\
		assoc_list.int3 \
		bag.int3 \
		builtin.int3 \
		char.int3 \
		cord.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		private_builtin.int3 \
		require.int3 \
		solutions.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		unit.int3 \
		varset.int3 \
		libs.options.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.parse_goal_util.int3 \
		parse_tree.parse_sym_name.int3 \
		parse_tree.parse_tree_out_misc.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_vars.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bitmap.int3 \
		bool.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		recompilation.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.indent.int3 \
		libs.optdb_help.int3 \
		libs.optimization_options.int3 \
		libs.option_categories.int3 \
		libs.timestamp.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.file_names.int3 \
		parse_tree.find_module.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		recompilation.item_types.int3 \
		string.builder.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
parse_tree.parse_goal.date0 parse_tree.date0 : \
		parse_goal.m \
	\
		assoc_list.int3 \
		bag.int3 \
		builtin.int3 \
		char.int3 \
		cord.int3 \
		int.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		pair.int3 \
		private_builtin.int3 \
		require.int3 \
		solutions.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		unit.int3 \
		varset.int3 \
		libs.options.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.parse_goal_util.int3 \
		parse_tree.parse_sym_name.int3 \
		parse_tree.parse_tree_out_misc.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_vars.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_item.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bitmap.int3 \
		bool.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		recompilation.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.indent.int3 \
		libs.optdb_help.int3 \
		libs.optimization_options.int3 \
		libs.option_categories.int3 \
		libs.timestamp.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.file_names.int3 \
		parse_tree.find_module.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		recompilation.item_types.int3 \
		string.builder.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
parse_tree.parse_goal.$O parse_tree.parse_goal.pic_o : \
		array.mh \
		assoc_list.mh \
		bag.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		deconstruct.mh \
		edit_seq.mh \
		enum.mh \
		getopt.mh \
		int.mh \
		integer.mh \
		io.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		one_or_more.mh \
		ops.mh \
		pair.mh \
		pretty_printer.mh \
		private_builtin.mh \
		recompilation.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		solutions.mh \
		sparse_bitset.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		io.stream_ops.mh \
		libs.file_util.mh \
		libs.globals.mh \
		libs.indent.mh \
		libs.optdb_help.mh \
		libs.optimization_options.mh \
		libs.option_categories.mh \
		libs.options.mh \
		libs.timestamp.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.error_spec.mh \
		parse_tree.file_names.mh \
		parse_tree.find_module.mh \
		parse_tree.maybe_error.mh \
		parse_tree.parse_goal_util.mh \
		parse_tree.parse_sym_name.mh \
		parse_tree.parse_tree_out_misc.mh \
		parse_tree.parse_tree_out_term.mh \
		parse_tree.parse_tree_output.mh \
		parse_tree.parse_vars.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.set_of_var.mh \
		parse_tree.var_db.mh \
		parse_tree.var_table.mh \
		recompilation.item_types.mh \
		string.builder.mh \
		string.format.mh \
		string.parse_util.mh

# RULE int0_on_date0
parse_tree.parse_goal.int0 : parse_tree.parse_goal.date0
	@:

# RULE int_on_date
parse_tree.parse_goal.int : parse_tree.parse_goal.date
	@:

# RULE int2_on_date
parse_tree.parse_goal.int2 : parse_tree.parse_goal.date
	@:

# RULE int3_on_date3
parse_tree.parse_goal.int3 : parse_tree.parse_goal.date3
	@:

# RULE opt_on_opt_date
parse_tree.parse_goal.opt : parse_tree.parse_goal.optdate
	@:

# RULE trans_opt_on_trans_opt_date
parse_tree.parse_goal.trans_opt : parse_tree.parse_goal.trans_opt_date
	@:

# RULE date0_on_src
parse_tree.parse_goal.date0 : parse_goal.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.parse_goal

# RULE date_on_src
parse_tree.parse_goal.date : parse_goal.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.parse_goal

# RULE date3_on_src
parse_tree.parse_goal.date3 : parse_goal.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.parse_goal

# RULE opt_date_on_src
parse_tree.parse_goal.optdate : parse_goal.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.parse_goal

# RULE trans_opt_date_on_src
parse_tree.parse_goal.trans_opt_date : parse_goal.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.parse_goal

# RULE c_date_on_src
parse_tree.parse_goal.c_date : parse_goal.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.parse_goal $(ERR_REDIRECT)

# RULE java_date_on_src
parse_tree.parse_goal.java_date : parse_goal.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.parse_goal $(ERR_REDIRECT)

