# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.module_qual' in source file `module_qual.m'.
# Generated by Mercury compiler version rotd-2026-09-06
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   int0
#   ancestors
#   direct deps
#   type_repn self dep
#   type_repn ancestor dep
parse_tree.module_qual.optdate parse_tree.module_qual.trans_opt_date module_qual.err parse_tree.module_qual.c_date parse_tree.module_qual.java_date : \
		module_qual.m \
	\
		parse_tree.module_qual.int0 \
	\
		parse_tree.int0 \
	\
		builtin.int \
		private_builtin.int \
	\
		parse_tree.module_qual.int \
	\
		parse_tree.int

# RULE objs_on_mihs
parse_tree.module_qual.$O parse_tree.module_qual.pic_o : \
		builtin.mih \
		parse_tree.mih \
		private_builtin.mih

# RULE mh_and_mih_on_c
parse_tree.module_qual.mh parse_tree.module_qual.mih : parse_tree.module_qual.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.module_qual.module_dep : jmercury/parse_tree__module_qual.java

else

# RULE module_dep_on_c
parse_tree.module_qual.module_dep : parse_tree.module_qual.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
parse_tree.module_qual.date parse_tree.module_qual.date0 parse_tree.date : \
		module_qual.m \
	\
		parse_tree.int0 \
	\
		builtin.int3 \
		private_builtin.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
parse_tree.module_qual.date0 parse_tree.date0 : \
		module_qual.m \
	\
		builtin.int3 \
		private_builtin.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
parse_tree.module_qual.$O parse_tree.module_qual.pic_o : \
		builtin.mh \
		private_builtin.mh

# RULE int0_on_date0
parse_tree.module_qual.int0 : parse_tree.module_qual.date0
	@:

# RULE int_on_date
parse_tree.module_qual.int : parse_tree.module_qual.date
	@:

# RULE int2_on_date
parse_tree.module_qual.int2 : parse_tree.module_qual.date
	@:

# RULE int3_on_date3
parse_tree.module_qual.int3 : parse_tree.module_qual.date3
	@:

# RULE opt_on_opt_date
parse_tree.module_qual.opt : parse_tree.module_qual.optdate
	@:

# RULE trans_opt_on_trans_opt_date
parse_tree.module_qual.trans_opt : parse_tree.module_qual.trans_opt_date
	@:

# RULE date0_on_src
parse_tree.module_qual.date0 : module_qual.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.module_qual

# RULE date_on_src
parse_tree.module_qual.date : module_qual.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.module_qual

# RULE date3_on_src
parse_tree.module_qual.date3 : module_qual.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.module_qual

# RULE opt_date_on_src
parse_tree.module_qual.optdate : module_qual.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.module_qual

# RULE trans_opt_date_on_src
parse_tree.module_qual.trans_opt_date : module_qual.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.module_qual

# RULE c_date_on_src
parse_tree.module_qual.c_date : module_qual.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.module_qual $(ERR_REDIRECT)

# RULE java_date_on_src
parse_tree.module_qual.java_date : module_qual.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.module_qual $(ERR_REDIRECT)

