# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `parse_tree.prog_type_test' in source file `prog_type_test.m'.
# Generated by Mercury compiler version rotd-2024-10-13
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
parse_tree.prog_type_test.optdate parse_tree.prog_type_test.trans_opt_date prog_type_test.err parse_tree.prog_type_test.c_date parse_tree.prog_type_test.java_date : \
		prog_type_test.m \
	\
		parse_tree.int0 \
	\
		builtin.int \
		list.int \
		mdbcomp.int \
		private_builtin.int \
		require.int \
		term.int \
		mdbcomp.builtin_modules.int \
		mdbcomp.prim_data.int \
		mdbcomp.sym_name.int \
		parse_tree.prog_data.int \
		parse_tree.prog_type.int \
		parse_tree.prog_type_scan.int \
	\
		assoc_list.int2 \
		bool.int2 \
		char.int2 \
		cord.int2 \
		enum.int2 \
		integer.int2 \
		map.int2 \
		maybe.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		term_context.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_util.int2 \
	\
		parse_tree.prog_type_test.int \
	\
		parse_tree.int

# RULE objs_on_mihs
parse_tree.prog_type_test.pic_o parse_tree.prog_type_test.$O : \
		assoc_list.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		cord.mih \
		enum.mih \
		integer.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		term.mih \
		term_context.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		mdbcomp.builtin_modules.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_type_scan.mih \
		parse_tree.prog_util.mih

# RULE mh_and_mih_on_c
parse_tree.prog_type_test.mh parse_tree.prog_type_test.mih : parse_tree.prog_type_test.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
parse_tree.prog_type_test.module_dep : jmercury/parse_tree__prog_type_test.java

else

# RULE module_dep_on_c
parse_tree.prog_type_test.module_dep : parse_tree.prog_type_test.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
parse_tree.prog_type_test.date parse_tree.prog_type_test.date0 parse_tree.date : \
		prog_type_test.m \
	\
		parse_tree.int0 \
	\
		builtin.int3 \
		list.int3 \
		mdbcomp.int3 \
		private_builtin.int3 \
		require.int3 \
		term.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_scan.int3 \
	\
		assoc_list.int3 \
		bool.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		map.int3 \
		maybe.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_util.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
parse_tree.prog_type_test.date0 parse_tree.date0 : \
		prog_type_test.m \
	\
		builtin.int3 \
		list.int3 \
		mdbcomp.int3 \
		private_builtin.int3 \
		require.int3 \
		term.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_scan.int3 \
	\
		assoc_list.int3 \
		bool.int3 \
		char.int3 \
		cord.int3 \
		enum.int3 \
		integer.int3 \
		map.int3 \
		maybe.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term_context.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_util.int3

# RULE int0_on_date0
parse_tree.prog_type_test.int0 : parse_tree.prog_type_test.date0
	@:

# RULE int_on_date
parse_tree.prog_type_test.int : parse_tree.prog_type_test.date
	@:

# RULE int2_on_date
parse_tree.prog_type_test.int2 : parse_tree.prog_type_test.date
	@:

# RULE int3_on_date3
parse_tree.prog_type_test.int3 : parse_tree.prog_type_test.date3
	@:

# RULE opt_on_opt_date
parse_tree.prog_type_test.opt : parse_tree.prog_type_test.optdate
	@:

# RULE trans_opt_on_trans_opt_date
parse_tree.prog_type_test.trans_opt : parse_tree.prog_type_test.trans_opt_date
	@:

# RULE date0_on_src
parse_tree.prog_type_test.date0 : prog_type_test.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) parse_tree.prog_type_test

# RULE date_on_src
parse_tree.prog_type_test.date : prog_type_test.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) parse_tree.prog_type_test

# RULE date3_on_src
parse_tree.prog_type_test.date3 : prog_type_test.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) parse_tree.prog_type_test

# RULE opt_date_on_src
parse_tree.prog_type_test.optdate : prog_type_test.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) parse_tree.prog_type_test

# RULE trans_opt_date_on_src
parse_tree.prog_type_test.trans_opt_date : prog_type_test.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) parse_tree.prog_type_test

# RULE c_date_on_src
parse_tree.prog_type_test.c_date : prog_type_test.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) parse_tree.prog_type_test $(ERR_REDIRECT)

# RULE java_date_on_src
parse_tree.prog_type_test.java_date : prog_type_test.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only parse_tree.prog_type_test $(ERR_REDIRECT)

