# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `recompilation.version' in source file `recompilation.version.m'.
# Generated by Mercury compiler version rotd-2026-06-28
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
recompilation.version.optdate recompilation.version.trans_opt_date recompilation.version.err recompilation.version.c_date recompilation.version.java_date : \
		recompilation.version.m \
	\
		recompilation.int0 \
	\
		assoc_list.int \
		builtin.int \
		cord.int \
		libs.int \
		list.int \
		map.int \
		maybe.int \
		mdbcomp.int \
		multi_map.int \
		one_or_more.int \
		pair.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		string.int \
		term.int \
		term_context.int \
		term_int.int \
		term_subst.int \
		term_unify.int \
		varset.int \
		libs.maybe_util.int \
		libs.timestamp.int \
		mdbcomp.prim_data.int \
		mdbcomp.sym_name.int \
		parse_tree.error_spec.int \
		parse_tree.item_util.int \
		parse_tree.maybe_error.int \
		parse_tree.parse_sym_name.int \
		parse_tree.parse_tree_out_info.int \
		parse_tree.parse_tree_out_sym_name.int \
		parse_tree.parse_tree_out_term.int \
		parse_tree.parse_tree_to_term.int \
		parse_tree.parse_util.int \
		parse_tree.prog_data.int \
		parse_tree.prog_data_pragma.int \
		parse_tree.prog_item.int \
		parse_tree.prog_parse_tree.int \
		parse_tree.prog_type.int \
		parse_tree.prog_type_subst.int \
		parse_tree.prog_type_unify.int \
		parse_tree.prog_util.int \
		parse_tree.type_inst_mode_map.int \
		recompilation.item_types.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		integer.int2 \
		io.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		libs.compiler_util.int2 \
		libs.file_util.int2 \
		libs.globals.int2 \
		libs.options.int2 \
		libs.rat.int2 \
		parse_tree.parse_tree_output.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_db.int2 \
		parse_tree.var_table.int2 \
		string.builder.int2 \
	\
		recompilation.version.int \
	\
		recompilation.int

# RULE objs_on_mihs
recompilation.version.$O recompilation.version.pic_o : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		multi_map.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		recompilation.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		term_int.mih \
		term_subst.mih \
		term_unify.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		libs.compiler_util.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.maybe_util.mih \
		libs.options.mih \
		libs.rat.mih \
		libs.timestamp.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.error_spec.mih \
		parse_tree.item_util.mih \
		parse_tree.maybe_error.mih \
		parse_tree.parse_sym_name.mih \
		parse_tree.parse_tree_out_info.mih \
		parse_tree.parse_tree_out_sym_name.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.parse_tree_output.mih \
		parse_tree.parse_tree_to_term.mih \
		parse_tree.parse_util.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_parse_tree.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_type_subst.mih \
		parse_tree.prog_type_unify.mih \
		parse_tree.prog_util.mih \
		parse_tree.set_of_var.mih \
		parse_tree.type_inst_mode_map.mih \
		parse_tree.var_db.mih \
		parse_tree.var_table.mih \
		recompilation.item_types.mih \
		string.builder.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
recompilation.version.mh recompilation.version.mih : recompilation.version.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
recompilation.version.module_dep : jmercury/recompilation__version.java

else

# RULE module_dep_on_c
recompilation.version.module_dep : recompilation.version.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
recompilation.version.date recompilation.version.date0 recompilation.date : \
		recompilation.version.m \
	\
		recompilation.int0 \
	\
		assoc_list.int3 \
		builtin.int3 \
		cord.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		term_int.int3 \
		term_subst.int3 \
		term_unify.int3 \
		varset.int3 \
		libs.maybe_util.int3 \
		libs.timestamp.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.item_util.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.parse_sym_name.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_out_sym_name.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_to_term.int3 \
		parse_tree.parse_util.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_parse_tree.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_type_unify.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.type_inst_mode_map.int3 \
		recompilation.item_types.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		libs.compiler_util.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		libs.rat.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		string.builder.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
recompilation.version.date0 recompilation.date0 : \
		recompilation.version.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		cord.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term.int3 \
		term_context.int3 \
		term_int.int3 \
		term_subst.int3 \
		term_unify.int3 \
		varset.int3 \
		libs.maybe_util.int3 \
		libs.timestamp.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.item_util.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.parse_sym_name.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_out_sym_name.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_to_term.int3 \
		parse_tree.parse_util.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_parse_tree.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_type_unify.int3 \
		parse_tree.prog_util.int3 \
		parse_tree.type_inst_mode_map.int3 \
		recompilation.item_types.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		libs.compiler_util.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		libs.rat.int3 \
		parse_tree.parse_tree_output.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_db.int3 \
		parse_tree.var_table.int3 \
		string.builder.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
recompilation.version.$O recompilation.version.pic_o : \
		array.mh \
		assoc_list.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		cord.mh \
		deconstruct.mh \
		edit_seq.mh \
		enum.mh \
		getopt.mh \
		integer.mh \
		io.mh \
		libs.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		multi_map.mh \
		one_or_more.mh \
		one_or_more_map.mh \
		ops.mh \
		pair.mh \
		parse_tree.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		sparse_bitset.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		term_int.mh \
		term_subst.mh \
		term_unify.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		unit.mh \
		univ.mh \
		varset.mh \
		io.stream_ops.mh \
		libs.compiler_util.mh \
		libs.file_util.mh \
		libs.globals.mh \
		libs.maybe_util.mh \
		libs.options.mh \
		libs.rat.mh \
		libs.timestamp.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		parse_tree.error_spec.mh \
		parse_tree.item_util.mh \
		parse_tree.maybe_error.mh \
		parse_tree.parse_sym_name.mh \
		parse_tree.parse_tree_out_info.mh \
		parse_tree.parse_tree_out_sym_name.mh \
		parse_tree.parse_tree_out_term.mh \
		parse_tree.parse_tree_output.mh \
		parse_tree.parse_tree_to_term.mh \
		parse_tree.parse_util.mh \
		parse_tree.prog_data.mh \
		parse_tree.prog_data_foreign.mh \
		parse_tree.prog_data_pragma.mh \
		parse_tree.prog_item.mh \
		parse_tree.prog_parse_tree.mh \
		parse_tree.prog_type.mh \
		parse_tree.prog_type_subst.mh \
		parse_tree.prog_type_unify.mh \
		parse_tree.prog_util.mh \
		parse_tree.set_of_var.mh \
		parse_tree.type_inst_mode_map.mh \
		parse_tree.var_db.mh \
		parse_tree.var_table.mh \
		recompilation.item_types.mh \
		string.builder.mh \
		string.format.mh \
		string.parse_util.mh

# RULE int0_on_date0
recompilation.version.int0 : recompilation.version.date0
	@:

# RULE int_on_date
recompilation.version.int : recompilation.version.date
	@:

# RULE int2_on_date
recompilation.version.int2 : recompilation.version.date
	@:

# RULE int3_on_date3
recompilation.version.int3 : recompilation.version.date3
	@:

# RULE opt_on_opt_date
recompilation.version.opt : recompilation.version.optdate
	@:

# RULE trans_opt_on_trans_opt_date
recompilation.version.trans_opt : recompilation.version.trans_opt_date
	@:

