# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `recompilation.version' in source file `recompilation.version.m'.
# Generated by Mercury compiler version DEV
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
recompilation.version.optdate recompilation.version.trans_opt_date recompilation.version.err recompilation.version.c_date recompilation.version.java_date : \
		recompilation.version.m \
	\
		recompilation.int0 \
	\
		assoc_list.int \
		builtin.int \
		cord.int \
		libs.int \
		list.int \
		map.int \
		maybe.int \
		multi_map.int \
		pair.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		string.int \
		term.int \
		varset.int \
		libs.timestamp.int \
		parse_tree.convert_parse_tree.int \
		parse_tree.error_util.int \
		parse_tree.item_util.int \
		parse_tree.maybe_error.int \
		parse_tree.mercury_to_mercury.int \
		parse_tree.parse_sym_name.int \
		parse_tree.parse_tree_out_info.int \
		parse_tree.parse_tree_out_term.int \
		parse_tree.parse_tree_to_term.int \
		parse_tree.parse_util.int \
		parse_tree.prog_item.int \
		parse_tree.prog_type.int \
		parse_tree.prog_type_subst.int \
		parse_tree.prog_util.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		integer.int2 \
		io.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pretty_printer.int2 \
		set_ordlist.int2 \
		stream.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		libs.globals.int2 \
		libs.options.int2 \
		parse_tree.file_kind.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.set_of_var.int2 \
	\
		recompilation.version.int \
	\
		recompilation.int

# RULE objs_on_mihs
recompilation.version.pic_o recompilation.version.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		integer.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		multi_map.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		recompilation.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		libs.globals.mih \
		libs.options.mih \
		libs.timestamp.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.convert_parse_tree.mih \
		parse_tree.error_util.mih \
		parse_tree.file_kind.mih \
		parse_tree.item_util.mih \
		parse_tree.maybe_error.mih \
		parse_tree.mercury_to_mercury.mih \
		parse_tree.parse_sym_name.mih \
		parse_tree.parse_tree_out_info.mih \
		parse_tree.parse_tree_out_term.mih \
		parse_tree.parse_tree_to_term.mih \
		parse_tree.parse_util.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_type.mih \
		parse_tree.prog_type_subst.mih \
		parse_tree.prog_util.mih \
		parse_tree.set_of_var.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
recompilation.version.mh recompilation.version.mih : recompilation.version.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
recompilation.version.module_dep : jmercury/recompilation__version.java

else

# RULE module_dep_on_c
recompilation.version.module_dep : recompilation.version.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
recompilation.version.date recompilation.version.date0 recompilation.date : \
		recompilation.version.m \
	\
		recompilation.int0 \
	\
		assoc_list.int3 \
		builtin.int3 \
		cord.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		multi_map.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		libs.timestamp.int3 \
		parse_tree.convert_parse_tree.int3 \
		parse_tree.error_util.int3 \
		parse_tree.item_util.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.mercury_to_mercury.int3 \
		parse_tree.parse_sym_name.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_to_term.int3 \
		parse_tree.parse_util.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_util.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		stream.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		parse_tree.file_kind.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.set_of_var.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
recompilation.version.date0 recompilation.date0 : \
		recompilation.version.m \
	\
		assoc_list.int3 \
		builtin.int3 \
		cord.int3 \
		libs.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		multi_map.int3 \
		pair.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term.int3 \
		varset.int3 \
		libs.timestamp.int3 \
		parse_tree.convert_parse_tree.int3 \
		parse_tree.error_util.int3 \
		parse_tree.item_util.int3 \
		parse_tree.maybe_error.int3 \
		parse_tree.mercury_to_mercury.int3 \
		parse_tree.parse_sym_name.int3 \
		parse_tree.parse_tree_out_info.int3 \
		parse_tree.parse_tree_out_term.int3 \
		parse_tree.parse_tree_to_term.int3 \
		parse_tree.parse_util.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.prog_type_subst.int3 \
		parse_tree.prog_util.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		integer.int3 \
		io.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pretty_printer.int3 \
		set_ordlist.int3 \
		stream.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		libs.globals.int3 \
		libs.options.int3 \
		parse_tree.file_kind.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.set_of_var.int3

# RULE foreign_deps_for_mh
recompilation.version.$O recompilation.version.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
recompilation.version.int0 : recompilation.version.date0
	@:

# RULE int_on_date
recompilation.version.int : recompilation.version.date
	@:

# RULE int2_on_date
recompilation.version.int2 : recompilation.version.date
	@:

# RULE int3_on_date3
recompilation.version.int3 : recompilation.version.date3
	@:

# RULE opt_on_opt_date
recompilation.version.opt : recompilation.version.optdate
	@:

# RULE trans_opt_on_trans_opt_date
recompilation.version.trans_opt : recompilation.version.trans_opt_date
	@:

