# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `top_level.mercury_compile_mlds_back_end' in source file `mercury_compile_mlds_back_end.m'.
# Generated by Mercury compiler version rotd-2024-04-20
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
top_level.mercury_compile_mlds_back_end.optdate top_level.mercury_compile_mlds_back_end.trans_opt_date mercury_compile_mlds_back_end.err top_level.mercury_compile_mlds_back_end.c_date top_level.mercury_compile_mlds_back_end.java_date : \
		mercury_compile_mlds_back_end.m \
	\
		top_level.int0 \
	\
		backend_libs.int \
		bool.int \
		builtin.int \
		hlds.int \
		io.int \
		libs.int \
		list.int \
		maybe.int \
		ml_backend.int \
		parse_tree.int \
		pprint.int \
		private_builtin.int \
		string.int \
		backend_libs.base_typeclass_info.int \
		backend_libs.type_class_info.int \
		backend_libs.type_ctor_info.int \
		hlds.hlds_dependency_graph.int \
		hlds.hlds_module.int \
		hlds.mark_static_terms.int \
		hlds.mark_tail_calls.int \
		hlds.passes_aux.int \
		libs.file_util.int \
		libs.globals.int \
		libs.maybe_util.int \
		libs.optimization_options.int \
		libs.options.int \
		ml_backend.add_heap_ops.int \
		ml_backend.add_trail_ops.int \
		ml_backend.ml_elim_nested.int \
		ml_backend.ml_optimize.int \
		ml_backend.ml_top_gen.int \
		ml_backend.mlds.int \
		ml_backend.mlds_to_c_file.int \
		ml_backend.mlds_to_c_util.int \
		ml_backend.mlds_to_cs_file.int \
		ml_backend.mlds_to_java_file.int \
		ml_backend.rtti_to_mlds.int \
		parse_tree.error_spec.int \
		parse_tree.file_names.int \
		parse_tree.write_error_spec.int \
		string.format.int \
		string.parse_util.int \
		top_level.mercury_compile_front_end.int \
		top_level.mercury_compile_llds_back_end.int \
	\
		analysis.int2 \
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		check_hlds.int2 \
		construct.int2 \
		cord.int2 \
		counter.int2 \
		deconstruct.int2 \
		digraph.int2 \
		edit_seq.int2 \
		enum.int2 \
		getopt.int2 \
		ll_backend.int2 \
		map.int2 \
		mdbcomp.int2 \
		multi_map.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		queue.int2 \
		recompilation.int2 \
		set.int2 \
		set_ordlist.int2 \
		set_tree234.int2 \
		sparse_bitset.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		backend_libs.builtin_ops.int2 \
		backend_libs.rtti.int2 \
		check_hlds.proc_requests.int2 \
		hlds.code_model.int2 \
		hlds.const_struct.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_inst_mode.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_pred.int2 \
		hlds.hlds_promise.int2 \
		hlds.make_hlds.int2 \
		hlds.pred_table.int2 \
		hlds.special_pred.int2 \
		hlds.status.int2 \
		libs.compiler_util.int2 \
		libs.dependency_graph.int2 \
		libs.indent.int2 \
		libs.op_mode.int2 \
		libs.trace_params.int2 \
		ll_backend.global_data.int2 \
		ll_backend.layout.int2 \
		ll_backend.llds.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.sym_name.int2 \
		ml_backend.ml_global_data.int2 \
		ml_backend.mlds_to_target_util.int2 \
		parse_tree.module_qual.int2 \
		parse_tree.prog_data.int2 \
		parse_tree.prog_data_event.int2 \
		parse_tree.prog_data_foreign.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_data_used_modules.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_type.int2 \
		parse_tree.set_of_var.int2 \
		recompilation.record_uses.int2 \
		hlds.make_hlds.qual_info.int2 \
	\
		top_level.mercury_compile_mlds_back_end.int \
	\
		top_level.int

# RULE objs_on_mihs
top_level.mercury_compile_mlds_back_end.pic_o top_level.mercury_compile_mlds_back_end.$O : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		backend_libs.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		counter.mih \
		deconstruct.mih \
		digraph.mih \
		edit_seq.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		io.mih \
		libs.mih \
		list.mih \
		ll_backend.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		ml_backend.mih \
		multi_map.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pprint.mih \
		pretty_printer.mih \
		private_builtin.mih \
		queue.mih \
		recompilation.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		top_level.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		backend_libs.base_typeclass_info.mih \
		backend_libs.builtin_ops.mih \
		backend_libs.rtti.mih \
		backend_libs.type_class_info.mih \
		backend_libs.type_ctor_info.mih \
		check_hlds.proc_requests.mih \
		hlds.code_model.mih \
		hlds.const_struct.mih \
		hlds.hlds_class.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_dependency_graph.mih \
		hlds.hlds_inst_mode.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.make_hlds.mih \
		hlds.mark_static_terms.mih \
		hlds.mark_tail_calls.mih \
		hlds.passes_aux.mih \
		hlds.pred_table.mih \
		hlds.special_pred.mih \
		hlds.status.mih \
		libs.compiler_util.mih \
		libs.dependency_graph.mih \
		libs.file_util.mih \
		libs.globals.mih \
		libs.indent.mih \
		libs.maybe_util.mih \
		libs.op_mode.mih \
		libs.optimization_options.mih \
		libs.options.mih \
		libs.trace_params.mih \
		ll_backend.global_data.mih \
		ll_backend.layout.mih \
		ll_backend.llds.mih \
		mdbcomp.feedback.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		ml_backend.add_heap_ops.mih \
		ml_backend.add_trail_ops.mih \
		ml_backend.ml_elim_nested.mih \
		ml_backend.ml_global_data.mih \
		ml_backend.ml_optimize.mih \
		ml_backend.ml_top_gen.mih \
		ml_backend.mlds.mih \
		ml_backend.mlds_to_c_file.mih \
		ml_backend.mlds_to_c_util.mih \
		ml_backend.mlds_to_cs_file.mih \
		ml_backend.mlds_to_java_file.mih \
		ml_backend.mlds_to_target_util.mih \
		ml_backend.rtti_to_mlds.mih \
		parse_tree.error_spec.mih \
		parse_tree.file_names.mih \
		parse_tree.module_qual.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_event.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_data_used_modules.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_type.mih \
		parse_tree.set_of_var.mih \
		parse_tree.write_error_spec.mih \
		recompilation.record_uses.mih \
		string.format.mih \
		string.parse_util.mih \
		top_level.mercury_compile_front_end.mih \
		top_level.mercury_compile_llds_back_end.mih \
		hlds.make_hlds.qual_info.mih

# RULE mh_and_mih_on_c
top_level.mercury_compile_mlds_back_end.mh top_level.mercury_compile_mlds_back_end.mih : top_level.mercury_compile_mlds_back_end.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
top_level.mercury_compile_mlds_back_end.module_dep : jmercury/top_level__mercury_compile_mlds_back_end.java

else

# RULE module_dep_on_c
top_level.mercury_compile_mlds_back_end.module_dep : top_level.mercury_compile_mlds_back_end.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   long dep int3s
#   short dep int3s
top_level.mercury_compile_mlds_back_end.date top_level.mercury_compile_mlds_back_end.date0 top_level.date : \
		mercury_compile_mlds_back_end.m \
	\
		top_level.int0 \
	\
		backend_libs.int3 \
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		ml_backend.int3 \
		parse_tree.int3 \
		pprint.int3 \
		private_builtin.int3 \
		string.int3 \
		backend_libs.base_typeclass_info.int3 \
		backend_libs.type_class_info.int3 \
		backend_libs.type_ctor_info.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_module.int3 \
		hlds.mark_static_terms.int3 \
		hlds.mark_tail_calls.int3 \
		hlds.passes_aux.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.maybe_util.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		ml_backend.add_heap_ops.int3 \
		ml_backend.add_trail_ops.int3 \
		ml_backend.ml_elim_nested.int3 \
		ml_backend.ml_optimize.int3 \
		ml_backend.ml_top_gen.int3 \
		ml_backend.mlds.int3 \
		ml_backend.mlds_to_c_file.int3 \
		ml_backend.mlds_to_c_util.int3 \
		ml_backend.mlds_to_cs_file.int3 \
		ml_backend.mlds_to_java_file.int3 \
		ml_backend.rtti_to_mlds.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_names.int3 \
		parse_tree.write_error_spec.int3 \
		string.format.int3 \
		string.parse_util.int3 \
		top_level.mercury_compile_front_end.int3 \
		top_level.mercury_compile_llds_back_end.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		cord.int3 \
		counter.int3 \
		deconstruct.int3 \
		digraph.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		ll_backend.int3 \
		map.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.rtti.int3 \
		check_hlds.proc_requests.int3 \
		hlds.code_model.int3 \
		hlds.const_struct.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_promise.int3 \
		hlds.make_hlds.int3 \
		hlds.pred_table.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.compiler_util.int3 \
		libs.dependency_graph.int3 \
		libs.indent.int3 \
		libs.op_mode.int3 \
		libs.trace_params.int3 \
		ll_backend.global_data.int3 \
		ll_backend.layout.int3 \
		ll_backend.llds.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		ml_backend.ml_global_data.int3 \
		ml_backend.mlds_to_target_util.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		recompilation.record_uses.int3 \
		hlds.make_hlds.qual_info.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   long dep int3s
#   short dep int3s
top_level.mercury_compile_mlds_back_end.date0 top_level.date0 : \
		mercury_compile_mlds_back_end.m \
	\
		backend_libs.int3 \
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		io.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		ml_backend.int3 \
		parse_tree.int3 \
		pprint.int3 \
		private_builtin.int3 \
		string.int3 \
		backend_libs.base_typeclass_info.int3 \
		backend_libs.type_class_info.int3 \
		backend_libs.type_ctor_info.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_module.int3 \
		hlds.mark_static_terms.int3 \
		hlds.mark_tail_calls.int3 \
		hlds.passes_aux.int3 \
		libs.file_util.int3 \
		libs.globals.int3 \
		libs.maybe_util.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		ml_backend.add_heap_ops.int3 \
		ml_backend.add_trail_ops.int3 \
		ml_backend.ml_elim_nested.int3 \
		ml_backend.ml_optimize.int3 \
		ml_backend.ml_top_gen.int3 \
		ml_backend.mlds.int3 \
		ml_backend.mlds_to_c_file.int3 \
		ml_backend.mlds_to_c_util.int3 \
		ml_backend.mlds_to_cs_file.int3 \
		ml_backend.mlds_to_java_file.int3 \
		ml_backend.rtti_to_mlds.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_names.int3 \
		parse_tree.write_error_spec.int3 \
		string.format.int3 \
		string.parse_util.int3 \
		top_level.mercury_compile_front_end.int3 \
		top_level.mercury_compile_llds_back_end.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		cord.int3 \
		counter.int3 \
		deconstruct.int3 \
		digraph.int3 \
		edit_seq.int3 \
		enum.int3 \
		getopt.int3 \
		ll_backend.int3 \
		map.int3 \
		mdbcomp.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		set.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		backend_libs.builtin_ops.int3 \
		backend_libs.rtti.int3 \
		check_hlds.proc_requests.int3 \
		hlds.code_model.int3 \
		hlds.const_struct.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_pred.int3 \
		hlds.hlds_promise.int3 \
		hlds.make_hlds.int3 \
		hlds.pred_table.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.compiler_util.int3 \
		libs.dependency_graph.int3 \
		libs.indent.int3 \
		libs.op_mode.int3 \
		libs.trace_params.int3 \
		ll_backend.global_data.int3 \
		ll_backend.layout.int3 \
		ll_backend.llds.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		ml_backend.ml_global_data.int3 \
		ml_backend.mlds_to_target_util.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		recompilation.record_uses.int3 \
		hlds.make_hlds.qual_info.int3

# RULE foreign_deps_for_mh
top_level.mercury_compile_mlds_back_end.$O top_level.mercury_compile_mlds_back_end.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
top_level.mercury_compile_mlds_back_end.int0 : top_level.mercury_compile_mlds_back_end.date0
	@:

# RULE int_on_date
top_level.mercury_compile_mlds_back_end.int : top_level.mercury_compile_mlds_back_end.date
	@:

# RULE int2_on_date
top_level.mercury_compile_mlds_back_end.int2 : top_level.mercury_compile_mlds_back_end.date
	@:

# RULE int3_on_date3
top_level.mercury_compile_mlds_back_end.int3 : top_level.mercury_compile_mlds_back_end.date3
	@:

# RULE opt_on_opt_date
top_level.mercury_compile_mlds_back_end.opt : top_level.mercury_compile_mlds_back_end.optdate
	@:

# RULE trans_opt_on_trans_opt_date
top_level.mercury_compile_mlds_back_end.trans_opt : top_level.mercury_compile_mlds_back_end.trans_opt_date
	@:

# RULE date0_on_src
top_level.mercury_compile_mlds_back_end.date0 : mercury_compile_mlds_back_end.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) top_level.mercury_compile_mlds_back_end

# RULE date_on_src
top_level.mercury_compile_mlds_back_end.date : mercury_compile_mlds_back_end.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) top_level.mercury_compile_mlds_back_end

# RULE date3_on_src
top_level.mercury_compile_mlds_back_end.date3 : mercury_compile_mlds_back_end.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) top_level.mercury_compile_mlds_back_end

# RULE opt_date_on_src
top_level.mercury_compile_mlds_back_end.optdate : mercury_compile_mlds_back_end.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) top_level.mercury_compile_mlds_back_end

# RULE trans_opt_date_on_src
top_level.mercury_compile_mlds_back_end.trans_opt_date : mercury_compile_mlds_back_end.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) top_level.mercury_compile_mlds_back_end

# RULE c_date_on_src
top_level.mercury_compile_mlds_back_end.c_date : mercury_compile_mlds_back_end.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) top_level.mercury_compile_mlds_back_end $(ERR_REDIRECT)

# RULE java_date_on_src
top_level.mercury_compile_mlds_back_end.java_date : mercury_compile_mlds_back_end.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only top_level.mercury_compile_mlds_back_end $(ERR_REDIRECT)

