# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `transform_hlds.pd_cost' in source file `pd_cost.m'.
# Generated by Mercury compiler version rotd-2022-02-19
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
transform_hlds.pd_cost.optdate transform_hlds.pd_cost.trans_opt_date pd_cost.err transform_hlds.pd_cost.c_date transform_hlds.pd_cost.java_date : \
		pd_cost.m \
	\
		transform_hlds.int0 \
	\
		builtin.int \
		hlds.int \
		int.int \
		list.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		hlds.hlds_goal.int \
		parse_tree.prog_data.int \
		parse_tree.prog_data_foreign.int \
		parse_tree.set_of_var.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bool.int2 \
		char.int2 \
		enum.int2 \
		libs.int2 \
		map.int2 \
		maybe.int2 \
		mdbcomp.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		sparse_bitset.int2 \
		term.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_pred.int2 \
		hlds.instmap.int2 \
		libs.globals.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.prim_data.int2 \
		mdbcomp.sym_name.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
	\
		transform_hlds.pd_cost.int \
	\
		transform_hlds.int

# RULE objs_on_mihs
transform_hlds.pd_cost.pic_o transform_hlds.pd_cost.$O : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		enum.mih \
		hlds.mih \
		int.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		sparse_bitset.mih \
		term.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		hlds.goal_mode.mih \
		hlds.hlds_data.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_pred.mih \
		hlds.instmap.mih \
		libs.globals.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.set_of_var.mih

# RULE mh_and_mih_on_c
transform_hlds.pd_cost.mh transform_hlds.pd_cost.mih : transform_hlds.pd_cost.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
transform_hlds.pd_cost.module_dep : jmercury/transform_hlds__pd_cost.java

else

# RULE module_dep_on_c
transform_hlds.pd_cost.module_dep : transform_hlds.pd_cost.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
transform_hlds.pd_cost.date transform_hlds.pd_cost.date0 transform_hlds.date : \
		pd_cost.m \
	\
		transform_hlds.int0 \
	\
		builtin.int3 \
		hlds.int3 \
		int.int3 \
		list.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		hlds.hlds_goal.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		enum.int3 \
		libs.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		libs.globals.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
transform_hlds.pd_cost.date0 transform_hlds.date0 : \
		pd_cost.m \
	\
		builtin.int3 \
		hlds.int3 \
		int.int3 \
		list.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		hlds.hlds_goal.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
		parse_tree.set_of_var.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bool.int3 \
		char.int3 \
		enum.int3 \
		libs.int3 \
		map.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		sparse_bitset.int3 \
		term.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		libs.globals.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3

# RULE foreign_deps_for_mh
transform_hlds.pd_cost.$O transform_hlds.pd_cost.pic_o : array.mh

# RULE int0_on_date0
transform_hlds.pd_cost.int0 : transform_hlds.pd_cost.date0
	@:

# RULE int_on_date
transform_hlds.pd_cost.int : transform_hlds.pd_cost.date
	@:

# RULE int2_on_date
transform_hlds.pd_cost.int2 : transform_hlds.pd_cost.date
	@:

# RULE int3_on_date3
transform_hlds.pd_cost.int3 : transform_hlds.pd_cost.date3
	@:

# RULE opt_on_opt_date
transform_hlds.pd_cost.opt : transform_hlds.pd_cost.optdate
	@:

# RULE trans_opt_on_trans_opt_date
transform_hlds.pd_cost.trans_opt : transform_hlds.pd_cost.trans_opt_date
	@:

# RULE date0_on_src
transform_hlds.pd_cost.date0 : pd_cost.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) transform_hlds.pd_cost

# RULE date_on_src
transform_hlds.pd_cost.date : pd_cost.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) transform_hlds.pd_cost

# RULE date3_on_src
transform_hlds.pd_cost.date3 : pd_cost.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) transform_hlds.pd_cost

# RULE opt_date_on_src
transform_hlds.pd_cost.optdate : pd_cost.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) transform_hlds.pd_cost

# RULE trans_opt_date_on_src
transform_hlds.pd_cost.trans_opt_date : pd_cost.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) transform_hlds.pd_cost

# RULE c_date_on_src
transform_hlds.pd_cost.c_date : pd_cost.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) transform_hlds.pd_cost $(ERR_REDIRECT)

# RULE java_date_on_src
transform_hlds.pd_cost.java_date : pd_cost.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only transform_hlds.pd_cost $(ERR_REDIRECT)

