# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `transform_hlds.granularity' in source file `granularity.m'.
# Generated by Mercury compiler version rotd-2022-11-28
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   ancestors
#   long deps
#   short deps
#   type_repn self dep
#   type_repn ancestor dep
transform_hlds.granularity.optdate transform_hlds.granularity.trans_opt_date granularity.err transform_hlds.granularity.c_date transform_hlds.granularity.java_date : \
		granularity.m \
	\
		transform_hlds.int0 \
	\
		bool.int \
		builtin.int \
		hlds.int \
		libs.int \
		list.int \
		maybe.int \
		mdbcomp.int \
		parse_tree.int \
		private_builtin.int \
		require.int \
		set.int \
		string.int \
		hlds.goal_util.int \
		hlds.hlds_dependency_graph.int \
		hlds.hlds_goal.int \
		hlds.hlds_module.int \
		hlds.hlds_pred.int \
		hlds.instmap.int \
		hlds.pred_table.int \
		hlds.quantification.int \
		libs.dependency_graph.int \
		libs.globals.int \
		mdbcomp.builtin_modules.int \
		mdbcomp.prim_data.int \
		parse_tree.prog_data.int \
		parse_tree.prog_data_foreign.int \
	\
		analysis.int2 \
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		char.int2 \
		check_hlds.int2 \
		construct.int2 \
		cord.int2 \
		deconstruct.int2 \
		digraph.int2 \
		enum.int2 \
		getopt.int2 \
		io.int2 \
		map.int2 \
		mode_robdd.int2 \
		multi_map.int2 \
		one_or_more.int2 \
		one_or_more_map.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		queue.int2 \
		recompilation.int2 \
		robdd.int2 \
		set_ordlist.int2 \
		set_tree234.int2 \
		sparse_bitset.int2 \
		stack.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		unit.int2 \
		univ.int2 \
		varset.int2 \
		check_hlds.mode_constraint_robdd.int2 \
		check_hlds.mode_errors.int2 \
		check_hlds.mode_info.int2 \
		check_hlds.proc_requests.int2 \
		hlds.const_struct.int2 \
		hlds.goal_mode.int2 \
		hlds.hlds_class.int2 \
		hlds.hlds_clauses.int2 \
		hlds.hlds_cons.int2 \
		hlds.hlds_data.int2 \
		hlds.hlds_inst_mode.int2 \
		hlds.hlds_llds.int2 \
		hlds.hlds_promise.int2 \
		hlds.hlds_rtti.int2 \
		hlds.inst_graph.int2 \
		hlds.pred_name.int2 \
		hlds.special_pred.int2 \
		hlds.status.int2 \
		libs.op_mode.int2 \
		libs.optimization_options.int2 \
		libs.options.int2 \
		libs.polyhedron.int2 \
		libs.timestamp.int2 \
		libs.trace_params.int2 \
		mdbcomp.feedback.int2 \
		mdbcomp.goal_path.int2 \
		mdbcomp.program_representation.int2 \
		mdbcomp.sym_name.int2 \
		mode_robdd.tfeirn.int2 \
		parse_tree.error_spec.int2 \
		parse_tree.file_names.int2 \
		parse_tree.module_qual.int2 \
		parse_tree.prog_data_event.int2 \
		parse_tree.prog_data_pragma.int2 \
		parse_tree.prog_data_used_modules.int2 \
		parse_tree.prog_foreign.int2 \
		parse_tree.prog_item.int2 \
		parse_tree.prog_rename.int2 \
		parse_tree.prog_type.int2 \
		parse_tree.set_of_var.int2 \
		parse_tree.var_table.int2 \
		parse_tree.vartypes.int2 \
		transform_hlds.term_constr_errors.int2 \
		transform_hlds.term_constr_main_types.int2 \
		transform_hlds.term_errors.int2 \
		transform_hlds.term_util.int2 \
	\
		transform_hlds.granularity.int \
	\
		transform_hlds.int

# RULE objs_on_mihs
transform_hlds.granularity.pic_o transform_hlds.granularity.$O : \
		analysis.mih \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		check_hlds.mih \
		construct.mih \
		cord.mih \
		deconstruct.mih \
		digraph.mih \
		enum.mih \
		getopt.mih \
		hlds.mih \
		io.mih \
		libs.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		mode_robdd.mih \
		multi_map.mih \
		one_or_more.mih \
		one_or_more_map.mih \
		ops.mih \
		pair.mih \
		parse_tree.mih \
		pretty_printer.mih \
		private_builtin.mih \
		queue.mih \
		recompilation.mih \
		require.mih \
		robdd.mih \
		set.mih \
		set_ordlist.mih \
		set_tree234.mih \
		sparse_bitset.mih \
		stack.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		time.mih \
		transform_hlds.mih \
		tree234.mih \
		type_desc.mih \
		unit.mih \
		univ.mih \
		varset.mih \
		check_hlds.mode_constraint_robdd.mih \
		check_hlds.mode_errors.mih \
		check_hlds.mode_info.mih \
		check_hlds.proc_requests.mih \
		hlds.const_struct.mih \
		hlds.goal_mode.mih \
		hlds.goal_util.mih \
		hlds.hlds_class.mih \
		hlds.hlds_clauses.mih \
		hlds.hlds_cons.mih \
		hlds.hlds_data.mih \
		hlds.hlds_dependency_graph.mih \
		hlds.hlds_goal.mih \
		hlds.hlds_inst_mode.mih \
		hlds.hlds_llds.mih \
		hlds.hlds_module.mih \
		hlds.hlds_pred.mih \
		hlds.hlds_promise.mih \
		hlds.hlds_rtti.mih \
		hlds.inst_graph.mih \
		hlds.instmap.mih \
		hlds.pred_name.mih \
		hlds.pred_table.mih \
		hlds.quantification.mih \
		hlds.special_pred.mih \
		hlds.status.mih \
		libs.dependency_graph.mih \
		libs.globals.mih \
		libs.op_mode.mih \
		libs.optimization_options.mih \
		libs.options.mih \
		libs.polyhedron.mih \
		libs.timestamp.mih \
		libs.trace_params.mih \
		mdbcomp.builtin_modules.mih \
		mdbcomp.feedback.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.program_representation.mih \
		mdbcomp.sym_name.mih \
		mode_robdd.tfeirn.mih \
		parse_tree.error_spec.mih \
		parse_tree.file_names.mih \
		parse_tree.module_qual.mih \
		parse_tree.prog_data.mih \
		parse_tree.prog_data_event.mih \
		parse_tree.prog_data_foreign.mih \
		parse_tree.prog_data_pragma.mih \
		parse_tree.prog_data_used_modules.mih \
		parse_tree.prog_foreign.mih \
		parse_tree.prog_item.mih \
		parse_tree.prog_rename.mih \
		parse_tree.prog_type.mih \
		parse_tree.set_of_var.mih \
		parse_tree.var_table.mih \
		parse_tree.vartypes.mih \
		transform_hlds.term_constr_errors.mih \
		transform_hlds.term_constr_main_types.mih \
		transform_hlds.term_errors.mih \
		transform_hlds.term_util.mih

# RULE mh_and_mih_on_c
transform_hlds.granularity.mh transform_hlds.granularity.mih : transform_hlds.granularity.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
transform_hlds.granularity.module_dep : jmercury/transform_hlds__granularity.java

else

# RULE module_dep_on_c
transform_hlds.granularity.module_dep : transform_hlds.granularity.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   ancestor int0
#   long dep int3s
#   short dep int3s
transform_hlds.granularity.date transform_hlds.granularity.date0 transform_hlds.date : \
		granularity.m \
	\
		transform_hlds.int0 \
	\
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		string.int3 \
		hlds.goal_util.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		hlds.pred_table.int3 \
		hlds.quantification.int3 \
		libs.dependency_graph.int3 \
		libs.globals.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		digraph.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		map.int3 \
		mode_robdd.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		robdd.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.mode_errors.int3 \
		check_hlds.mode_info.int3 \
		check_hlds.proc_requests.int3 \
		hlds.const_struct.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.pred_name.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.polyhedron.int3 \
		libs.timestamp.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_names.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
transform_hlds.granularity.date0 transform_hlds.date0 : \
		granularity.m \
	\
		bool.int3 \
		builtin.int3 \
		hlds.int3 \
		libs.int3 \
		list.int3 \
		maybe.int3 \
		mdbcomp.int3 \
		parse_tree.int3 \
		private_builtin.int3 \
		require.int3 \
		set.int3 \
		string.int3 \
		hlds.goal_util.int3 \
		hlds.hlds_dependency_graph.int3 \
		hlds.hlds_goal.int3 \
		hlds.hlds_module.int3 \
		hlds.hlds_pred.int3 \
		hlds.instmap.int3 \
		hlds.pred_table.int3 \
		hlds.quantification.int3 \
		libs.dependency_graph.int3 \
		libs.globals.int3 \
		mdbcomp.builtin_modules.int3 \
		mdbcomp.prim_data.int3 \
		parse_tree.prog_data.int3 \
		parse_tree.prog_data_foreign.int3 \
	\
		analysis.int3 \
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		char.int3 \
		check_hlds.int3 \
		construct.int3 \
		cord.int3 \
		deconstruct.int3 \
		digraph.int3 \
		enum.int3 \
		getopt.int3 \
		io.int3 \
		map.int3 \
		mode_robdd.int3 \
		multi_map.int3 \
		one_or_more.int3 \
		one_or_more_map.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		queue.int3 \
		recompilation.int3 \
		robdd.int3 \
		set_ordlist.int3 \
		set_tree234.int3 \
		sparse_bitset.int3 \
		stack.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		unit.int3 \
		univ.int3 \
		varset.int3 \
		check_hlds.mode_constraint_robdd.int3 \
		check_hlds.mode_errors.int3 \
		check_hlds.mode_info.int3 \
		check_hlds.proc_requests.int3 \
		hlds.const_struct.int3 \
		hlds.goal_mode.int3 \
		hlds.hlds_class.int3 \
		hlds.hlds_clauses.int3 \
		hlds.hlds_cons.int3 \
		hlds.hlds_data.int3 \
		hlds.hlds_inst_mode.int3 \
		hlds.hlds_llds.int3 \
		hlds.hlds_promise.int3 \
		hlds.hlds_rtti.int3 \
		hlds.inst_graph.int3 \
		hlds.pred_name.int3 \
		hlds.special_pred.int3 \
		hlds.status.int3 \
		libs.op_mode.int3 \
		libs.optimization_options.int3 \
		libs.options.int3 \
		libs.polyhedron.int3 \
		libs.timestamp.int3 \
		libs.trace_params.int3 \
		mdbcomp.feedback.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.program_representation.int3 \
		mdbcomp.sym_name.int3 \
		mode_robdd.tfeirn.int3 \
		parse_tree.error_spec.int3 \
		parse_tree.file_names.int3 \
		parse_tree.module_qual.int3 \
		parse_tree.prog_data_event.int3 \
		parse_tree.prog_data_pragma.int3 \
		parse_tree.prog_data_used_modules.int3 \
		parse_tree.prog_foreign.int3 \
		parse_tree.prog_item.int3 \
		parse_tree.prog_rename.int3 \
		parse_tree.prog_type.int3 \
		parse_tree.set_of_var.int3 \
		parse_tree.var_table.int3 \
		parse_tree.vartypes.int3 \
		transform_hlds.term_constr_errors.int3 \
		transform_hlds.term_constr_main_types.int3 \
		transform_hlds.term_errors.int3 \
		transform_hlds.term_util.int3

# RULE foreign_deps_for_mh
transform_hlds.granularity.$O transform_hlds.granularity.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh \
		io.stream_ops.mh

# RULE int0_on_date0
transform_hlds.granularity.int0 : transform_hlds.granularity.date0
	@:

# RULE int_on_date
transform_hlds.granularity.int : transform_hlds.granularity.date
	@:

# RULE int2_on_date
transform_hlds.granularity.int2 : transform_hlds.granularity.date
	@:

# RULE int3_on_date3
transform_hlds.granularity.int3 : transform_hlds.granularity.date3
	@:

# RULE opt_on_opt_date
transform_hlds.granularity.opt : transform_hlds.granularity.optdate
	@:

# RULE trans_opt_on_trans_opt_date
transform_hlds.granularity.trans_opt : transform_hlds.granularity.trans_opt_date
	@:

# RULE date0_on_src
transform_hlds.granularity.date0 : granularity.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) transform_hlds.granularity

# RULE date_on_src
transform_hlds.granularity.date : granularity.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) transform_hlds.granularity

# RULE date3_on_src
transform_hlds.granularity.date3 : granularity.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) transform_hlds.granularity

# RULE opt_date_on_src
transform_hlds.granularity.optdate : granularity.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) transform_hlds.granularity

# RULE trans_opt_date_on_src
transform_hlds.granularity.trans_opt_date : granularity.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) transform_hlds.granularity

# RULE c_date_on_src
transform_hlds.granularity.c_date : granularity.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) transform_hlds.granularity $(ERR_REDIRECT)

# RULE java_date_on_src
transform_hlds.granularity.java_date : granularity.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only transform_hlds.granularity $(ERR_REDIRECT)

