# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `mfilterjavac' in source file `mfilterjavac.m'.
# Generated by Mercury compiler version rotd-2021-08-14
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
mfilterjavac.optdate mfilterjavac.trans_opt_date mfilterjavac.err mfilterjavac.c_date mfilterjavac.java_date : \
		mfilterjavac.m \
	\
		builtin.int \
		char.int \
		int.int \
		io.int \
		list.int \
		map.int \
		maybe.int \
		private_builtin.int \
		stream.int \
		string.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		bool.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		mfilterjavac.int

# RULE objs_on_mihs
mfilterjavac.pic_o mfilterjavac.$O : \
		array.mih \
		assoc_list.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		int.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
mfilterjavac.mh mfilterjavac.mih : mfilterjavac.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
mfilterjavac.module_dep : jmercury/mfilterjavac.java

else

# RULE module_dep_on_c
mfilterjavac.module_dep : mfilterjavac.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mfilterjavac.date mfilterjavac.date0 : \
		mfilterjavac.m \
	\
		builtin.int3 \
		char.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		private_builtin.int3 \
		stream.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
mfilterjavac.date0 : \
		mfilterjavac.m \
	\
		builtin.int3 \
		char.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		private_builtin.int3 \
		stream.int3 \
		string.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
mfilterjavac.$O mfilterjavac.pic_o : \
		array.mh \
		bitmap.mh \
		builtin.mh \
		char.mh \
		int.mh \
		io.mh \
		private_builtin.mh \
		string.mh \
		time.mh \
		string.format.mh

# RULE int0_on_date0
mfilterjavac.int0 : mfilterjavac.date0
	@:

# RULE int_on_date
mfilterjavac.int : mfilterjavac.date
	@:

# RULE int2_on_date
mfilterjavac.int2 : mfilterjavac.date
	@:

# RULE int3_on_date3
mfilterjavac.int3 : mfilterjavac.date3
	@:

# RULE opt_on_opt_date
mfilterjavac.opt : mfilterjavac.optdate
	@:

# RULE trans_opt_on_trans_opt_date
mfilterjavac.trans_opt : mfilterjavac.trans_opt_date
	@:

