# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `mdbcomp.write_trace_counts' in source file `write_trace_counts.m'.
# Generated by Mercury compiler version rotd-2025-12-10
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   source
#   ancestors
#   direct deps
#   indirect deps
#   type_repn self dep
#   type_repn ancestor dep
mdbcomp.write_trace_counts.optdate mdbcomp.write_trace_counts.trans_opt_date write_trace_counts.err mdbcomp.write_trace_counts.c_date mdbcomp.write_trace_counts.java_date : \
		write_trace_counts.m \
	\
		mdbcomp.int0 \
	\
		builtin.int \
		io.int \
		list.int \
		map.int \
		private_builtin.int \
		require.int \
		string.int \
		term_io.int \
		mdbcomp.goal_path.int \
		mdbcomp.prim_data.int \
		mdbcomp.sym_name.int \
		mdbcomp.trace_counts.int \
		string.format.int \
		string.parse_util.int \
	\
		array.int2 \
		assoc_list.int2 \
		bimap.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		maybe.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		set.int2 \
		set_ordlist.int2 \
		stream.int2 \
		term.int2 \
		term_context.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
		varset.int2 \
		string.builder.int2 \
	\
		mdbcomp.write_trace_counts.int \
	\
		mdbcomp.int

# RULE objs_on_mihs
mdbcomp.write_trace_counts.$O mdbcomp.write_trace_counts.pic_o : \
		array.mih \
		assoc_list.mih \
		bimap.mih \
		bitmap.mih \
		bool.mih \
		builtin.mih \
		char.mih \
		construct.mih \
		deconstruct.mih \
		enum.mih \
		io.mih \
		list.mih \
		map.mih \
		maybe.mih \
		mdbcomp.mih \
		ops.mih \
		pair.mih \
		pretty_printer.mih \
		private_builtin.mih \
		require.mih \
		set.mih \
		set_ordlist.mih \
		stream.mih \
		string.mih \
		term.mih \
		term_context.mih \
		term_io.mih \
		time.mih \
		tree234.mih \
		type_desc.mih \
		univ.mih \
		varset.mih \
		mdbcomp.goal_path.mih \
		mdbcomp.prim_data.mih \
		mdbcomp.sym_name.mih \
		mdbcomp.trace_counts.mih \
		string.builder.mih \
		string.format.mih \
		string.parse_util.mih

# RULE mh_and_mih_on_c
mdbcomp.write_trace_counts.mh mdbcomp.write_trace_counts.mih : mdbcomp.write_trace_counts.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
mdbcomp.write_trace_counts.module_dep : jmercury/mdbcomp__write_trace_counts.java

else

# RULE module_dep_on_c
mdbcomp.write_trace_counts.module_dep : mdbcomp.write_trace_counts.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# target group names:
#   date files
# source group names:
#   source
#   ancestor int0
#   direct dep int3s
#   indirect dep int3s
mdbcomp.write_trace_counts.date mdbcomp.write_trace_counts.date0 mdbcomp.date : \
		write_trace_counts.m \
	\
		mdbcomp.int0 \
	\
		builtin.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term_io.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		mdbcomp.trace_counts.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		string.builder.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   source
#   direct dep int3s
#   indirect dep int3s
mdbcomp.write_trace_counts.date0 mdbcomp.date0 : \
		write_trace_counts.m \
	\
		builtin.int3 \
		io.int3 \
		list.int3 \
		map.int3 \
		private_builtin.int3 \
		require.int3 \
		string.int3 \
		term_io.int3 \
		mdbcomp.goal_path.int3 \
		mdbcomp.prim_data.int3 \
		mdbcomp.sym_name.int3 \
		mdbcomp.trace_counts.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bimap.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		set.int3 \
		set_ordlist.int3 \
		stream.int3 \
		term.int3 \
		term_context.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3 \
		varset.int3 \
		string.builder.int3

# RULE foreign_deps_for_mh
# target group names:
#   object_files
# source group names:
#   own_mh_deps
mdbcomp.write_trace_counts.$O mdbcomp.write_trace_counts.pic_o : \
		array.mh \
		assoc_list.mh \
		bimap.mh \
		bitmap.mh \
		bool.mh \
		builtin.mh \
		char.mh \
		construct.mh \
		deconstruct.mh \
		enum.mh \
		io.mh \
		list.mh \
		map.mh \
		maybe.mh \
		mdbcomp.mh \
		ops.mh \
		pair.mh \
		pretty_printer.mh \
		private_builtin.mh \
		require.mh \
		set.mh \
		set_ordlist.mh \
		stream.mh \
		string.mh \
		term.mh \
		term_context.mh \
		term_io.mh \
		time.mh \
		tree234.mh \
		type_desc.mh \
		univ.mh \
		varset.mh \
		io.stream_ops.mh \
		mdbcomp.goal_path.mh \
		mdbcomp.prim_data.mh \
		mdbcomp.sym_name.mh \
		mdbcomp.trace_counts.mh \
		string.builder.mh \
		string.format.mh \
		string.parse_util.mh

# RULE int0_on_date0
mdbcomp.write_trace_counts.int0 : mdbcomp.write_trace_counts.date0
	@:

# RULE int_on_date
mdbcomp.write_trace_counts.int : mdbcomp.write_trace_counts.date
	@:

# RULE int2_on_date
mdbcomp.write_trace_counts.int2 : mdbcomp.write_trace_counts.date
	@:

# RULE int3_on_date3
mdbcomp.write_trace_counts.int3 : mdbcomp.write_trace_counts.date3
	@:

# RULE opt_on_opt_date
mdbcomp.write_trace_counts.opt : mdbcomp.write_trace_counts.optdate
	@:

# RULE trans_opt_on_trans_opt_date
mdbcomp.write_trace_counts.trans_opt : mdbcomp.write_trace_counts.trans_opt_date
	@:

# RULE date0_on_src
mdbcomp.write_trace_counts.date0 : write_trace_counts.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) mdbcomp.write_trace_counts

# RULE date_on_src
mdbcomp.write_trace_counts.date : write_trace_counts.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) mdbcomp.write_trace_counts

# RULE date3_on_src
mdbcomp.write_trace_counts.date3 : write_trace_counts.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) mdbcomp.write_trace_counts

# RULE opt_date_on_src
mdbcomp.write_trace_counts.optdate : write_trace_counts.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) mdbcomp.write_trace_counts

# RULE trans_opt_date_on_src
mdbcomp.write_trace_counts.trans_opt_date : write_trace_counts.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) mdbcomp.write_trace_counts

# RULE c_date_on_src
mdbcomp.write_trace_counts.c_date : write_trace_counts.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) mdbcomp.write_trace_counts $(ERR_REDIRECT)

# RULE java_date_on_src
mdbcomp.write_trace_counts.java_date : write_trace_counts.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only mdbcomp.write_trace_counts $(ERR_REDIRECT)

